package io.knowledge.platform.integration;

import static org.jooq.impl.DSL.field;import static org.jooq.impl.DSL.name;import static org.jooq.impl.DSL.table;
import io.knowledge.platform.catalog.CatalogService;import io.knowledge.platform.catalog.CatalogTreeView;import io.knowledge.platform.common.DomainConflictException;import io.knowledge.platform.integration.ExternalApiModels.DocumentCreate;import io.knowledge.platform.integration.ExternalApiModels.DocumentUpdate;import io.knowledge.platform.knowledgebase.KnowledgeBaseService;import io.knowledge.platform.knowledgebase.KnowledgeBaseView;import io.knowledge.platform.page.ContentType;import io.knowledge.platform.page.CreatePageCommand;import io.knowledge.platform.page.PageService;import io.knowledge.platform.page.PageView;import io.knowledge.platform.page.UpdatePageCommand;import io.knowledge.platform.search.SearchResponse;import io.knowledge.platform.search.SearchService;import io.knowledge.platform.team.TeamService;import io.knowledge.platform.team.TeamView;import io.knowledge.platform.workspace.WorkspaceManagementService;import io.knowledge.platform.workspace.WorkspaceMemberView;import io.knowledge.platform.workspace.WorkspaceView;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Clock;import java.time.OffsetDateTime;import java.util.List;import java.util.Set;import java.util.UUID;import org.jooq.DSLContext;import org.jooq.JSONB;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;

@Service
public class ExternalApiService {
    private final WorkspaceManagementService workspaces;private final TeamService teams;private final KnowledgeBaseService knowledgeBases;private final PageService pages;private final CatalogService catalogs;private final SearchService search;private final OpenPlatformService openPlatform;private final DSLContext dsl;private final ObjectMapper mapper;private final Clock clock;
    public ExternalApiService(WorkspaceManagementService workspaces,TeamService teams,KnowledgeBaseService knowledgeBases,PageService pages,CatalogService catalogs,SearchService search,OpenPlatformService openPlatform,DSLContext dsl,ObjectMapper mapper,Clock clock){this.workspaces=workspaces;this.teams=teams;this.knowledgeBases=knowledgeBases;this.pages=pages;this.catalogs=catalogs;this.search=search;this.openPlatform=openPlatform;this.dsl=dsl;this.mapper=mapper;this.clock=clock;}

    @Transactional(readOnly=true) public List<WorkspaceView> workspaces(CredentialIdentity identity){scope(identity,"workspaces:read");return workspaces.list(identity.userId()).stream().filter(value->value.id().equals(identity.workspaceId())).toList();}
    @Transactional(readOnly=true) public List<WorkspaceMemberView> users(CredentialIdentity identity,UUID workspace){scopeWorkspace(identity,workspace,"users:read");return workspaces.members(identity.userId(),workspace);}
    @Transactional(readOnly=true) public List<TeamView> teams(CredentialIdentity identity,UUID workspace){scopeWorkspace(identity,workspace,"teams:read");return teams.list(identity.userId(),workspace);}
    @Transactional(readOnly=true) public List<KnowledgeBaseView> knowledgeBases(CredentialIdentity identity,UUID workspace){scopeWorkspace(identity,workspace,"knowledge-bases:read");return knowledgeBases.list(identity.userId(),workspace);}
    @Transactional(readOnly=true) public List<PageView> documents(CredentialIdentity identity,UUID knowledgeBase){scope(identity,"documents:read");var kb=knowledgeBases.get(identity.userId(),knowledgeBase);workspace(identity,kb.workspaceId());return pages.list(identity.userId(),knowledgeBase);}
    @Transactional public PageView document(CredentialIdentity identity,UUID page){scope(identity,"documents:read");PageView value=pages.get(identity.userId(),page);workspace(identity,value.workspaceId());return value;}
    @Transactional public PageView createDocument(CredentialIdentity identity,String idempotencyKey,DocumentCreate value){scope(identity,"documents:write");if(value==null||value.knowledgeBaseId()==null)throw new IllegalArgumentException("knowledgeBaseId is required");var kb=knowledgeBases.get(identity.userId(),value.knowledgeBaseId());workspace(identity,kb.workspaceId());return idempotent(identity,"POST /api/v2/documents",idempotencyKey,value,PageView.class,()->pages.create(identity.userId(),new CreatePageCommand(value.knowledgeBaseId(),value.title(),value.path(),value.contentType()==null?ContentType.DOCUMENT:ContentType.valueOf(value.contentType().toUpperCase(java.util.Locale.ROOT)),value.icon(),value.cover(),value.publishMode(),value.visibilityOverride(),value.documentSettings(),value.content())));}
    @Transactional public PageView updateDocument(CredentialIdentity identity,String idempotencyKey,DocumentUpdate value){scope(identity,"documents:write");if(value==null||value.pageId()==null)throw new IllegalArgumentException("pageId is required");PageView current=pages.get(identity.userId(),value.pageId());workspace(identity,current.workspaceId());return idempotent(identity,"PATCH /api/v2/documents",idempotencyKey,value,PageView.class,()->pages.update(identity.userId(),new UpdatePageCommand(value.pageId(),value.expectedRevision(),value.title(),value.path(),value.icon(),value.cover(),value.publishMode(),value.visibilityOverride(),value.documentSettings(),value.content(),value.schemaVersion(),value.revisionKind(),value.revisionDescription())));}
    @Transactional(readOnly=true) public CatalogTreeView catalog(CredentialIdentity identity,UUID knowledgeBase){scope(identity,"catalog:read");var kb=knowledgeBases.get(identity.userId(),knowledgeBase);workspace(identity,kb.workspaceId());return catalogs.list(identity.userId(),knowledgeBase);}
    @Transactional(readOnly=true) public SearchResponse search(CredentialIdentity identity,UUID workspace,String query,Set<String> types,int offset,int limit){scopeWorkspace(identity,workspace,"search:read");return search.search(identity.userId(),workspace,query,types,offset,limit);}
    @Transactional(readOnly=true) public List<OpenPlatformViews.Webhook> webhooks(CredentialIdentity identity,UUID workspace){scopeWorkspace(identity,workspace,"webhooks:read");return openPlatform.webhooks(identity.userId(),workspace);}
    @Transactional public OpenPlatformViews.Webhook createWebhook(CredentialIdentity identity,String idempotencyKey,ExternalApiModels.WebhookCreate value){scopeWorkspace(identity,value.workspaceId(),"webhooks:write");return idempotent(identity,"POST /api/v2/webhooks",idempotencyKey,value,OpenPlatformViews.Webhook.class,()->openPlatform.createWebhook(identity.userId(),value.workspaceId(),value.name(),value.endpointUrl(),value.events()));}

    private <T>T idempotent(CredentialIdentity identity,String endpoint,String key,Object request,Class<T> type,java.util.function.Supplier<T> action){String normalized=idempotencyKey(key);String lock=identity.workspaceId()+":"+identity.userId()+":"+endpoint+":"+normalized;dsl.fetch("select pg_advisory_xact_lock(hashtextextended(?,0))",lock);byte[] requestHash=hash(mapper.writeValueAsBytes(request));var existing=dsl.select(field(name("request_hash"),byte[].class),field(name("response_body"),JSONB.class)).from(table(name("integration_idempotency"))).where(field(name("workspace_id"),UUID.class).eq(identity.workspaceId()).and(field(name("actor_id"),UUID.class).eq(identity.userId())).and(field(name("endpoint"),String.class).eq(endpoint)).and(field(name("idempotency_key"),String.class).eq(normalized))).fetchOne();if(existing!=null){if(!MessageDigest.isEqual(existing.value1(),requestHash))throw new DomainConflictException("IDEMPOTENCY_KEY_REUSED","Idempotency key was already used with a different request");return mapper.readValue(existing.value2().data(),type);}T response=action.get();dsl.insertInto(table(name("integration_idempotency"))).columns(field(name("workspace_id")),field(name("actor_id")),field(name("endpoint")),field(name("idempotency_key")),field(name("request_hash")),field(name("response_body")),field(name("created_at"))).values(identity.workspaceId(),identity.userId(),endpoint,normalized,requestHash,JSONB.valueOf(mapper.writeValueAsString(response)),OffsetDateTime.now(clock)).execute();return response;}
    private static void scope(CredentialIdentity identity,String value){if(identity==null)throw new IllegalArgumentException("External API credential is required");OpenPlatformScopes.require(identity.scopes(),value);}private static void workspace(CredentialIdentity identity,UUID workspace){if(!identity.workspaceId().equals(workspace))throw new IllegalArgumentException("Credential is scoped to a different workspace");}private static void scopeWorkspace(CredentialIdentity identity,UUID workspace,String scope){scope(identity,scope);workspace(identity,workspace);}
    private static String idempotencyKey(String value){if(value==null||value.length()<8||value.length()>160||!value.matches("[A-Za-z0-9._:-]+"))throw new IllegalArgumentException("Idempotency-Key must contain 8-160 safe characters");return value;}
    private static byte[] hash(byte[] value){try{return MessageDigest.getInstance("SHA-256").digest(value);}catch(Exception exception){throw new IllegalStateException(exception);}}
}
