package io.knowledge.platform.integration;

import io.knowledge.platform.audit.AuditService;import io.knowledge.platform.authorization.AuthorizationDeniedException;import io.knowledge.platform.authorization.AuthorizationService;import io.knowledge.platform.authorization.Capability;import io.knowledge.platform.authorization.ResourceNotFoundException;import io.knowledge.platform.authorization.ResourceType;import io.knowledge.platform.common.Ids;import io.knowledge.platform.common.SecretCipher;import io.knowledge.platform.integration.OpenPlatformViews.ApiKey;import io.knowledge.platform.integration.OpenPlatformViews.AuthorizationGrant;import io.knowledge.platform.integration.OpenPlatformViews.OAuthClient;import io.knowledge.platform.integration.OpenPlatformViews.Token;import io.knowledge.platform.integration.OpenPlatformViews.Webhook;import io.knowledge.platform.integration.OpenPlatformViews.WebhookDelivery;import io.knowledge.platform.integration.OpenPlatformViews.WebhookDeliveryPage;import java.net.URI;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.security.SecureRandom;import java.time.Clock;import java.time.Duration;import java.time.OffsetDateTime;import java.util.Base64;import java.util.HexFormat;import java.util.List;import java.util.Locale;import java.util.Set;import java.util.UUID;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class OpenPlatformService {
    private static final SecureRandom RANDOM=new SecureRandom();private static final Base64.Encoder URL=Base64.getUrlEncoder().withoutPadding();private static final int API_KEY_PREFIX_LENGTH=12;private static final Duration ACCESS_TTL=Duration.ofHours(1),REFRESH_TTL=Duration.ofDays(30),CODE_TTL=Duration.ofMinutes(5);
    private final OpenPlatformRepository repository;private final AuthorizationService authorization;private final AuditService audit;private final SecretCipher cipher;private final WebhookEndpointPolicy endpoints;private final Clock clock;
    public OpenPlatformService(OpenPlatformRepository repository,AuthorizationService authorization,AuditService audit,SecretCipher cipher,WebhookEndpointPolicy endpoints,Clock clock){this.repository=repository;this.authorization=authorization;this.audit=audit;this.cipher=cipher;this.endpoints=endpoints;this.clock=clock;}

    @Transactional public ApiKey createApiKey(UUID actor,UUID workspace,String name,Set<String> requested,OffsetDateTime expiresAt){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.READ);Set<String> scopes=OpenPlatformScopes.normalize(requested);if(scopes.isEmpty())throw new IllegalArgumentException("At least one API key scope is required");OffsetDateTime now=now();if(expiresAt!=null&&!expiresAt.isAfter(now))throw new IllegalArgumentException("API key expiry must be in the future");String prefix=randomHex(6),secret="kp_live_"+prefix+"_"+random(32);UUID id=Ids.next();repository.insertApiKey(id,workspace,actor,text(name,120,"API key name"),prefix,hash(secret),scopes,expiresAt,now);audit.success(workspace,actor,"integration.api-key.create","API_KEY",id);return new ApiKey(id,workspace,name,prefix,scopes,null,expiresAt,null,now,secret);}
    @Transactional(readOnly=true) public List<ApiKey> apiKeys(UUID actor,UUID workspace){var access=authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.READ);boolean manage=access.allows(Capability.MANAGE);return repository.apiKeys(workspace).stream().filter(row->manage||row.userId().equals(actor)).map(row->new ApiKey(row.id(),row.workspaceId(),row.name(),row.prefix(),row.scopes(),row.lastUsedAt(),row.expiresAt(),row.revokedAt(),row.createdAt(),null)).toList();}
    @Transactional public void revokeApiKey(UUID actor,UUID workspace,UUID id){var row=repository.apiKeys(workspace).stream().filter(value->value.id().equals(id)).findFirst().orElseThrow(ResourceNotFoundException::new);if(!row.userId().equals(actor)&&!authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE).allows(Capability.MANAGE))throw new AuthorizationDeniedException();repository.revokeApiKey(id,workspace,now());audit.success(workspace,actor,"integration.api-key.revoke","API_KEY",id);}

    @Transactional public OAuthClient createClient(UUID actor,UUID workspace,String name,List<String> redirectUris,Set<String> requested,boolean publicClient){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);Set<String> scopes=OpenPlatformScopes.normalize(requested);if(scopes.isEmpty())throw new IllegalArgumentException("At least one OAuth scope is required");List<String> redirects=redirectUris==null?List.of():redirectUris.stream().map(OpenPlatformService::redirect).distinct().limit(20).toList();if(redirects.isEmpty())throw new IllegalArgumentException("At least one redirect URI is required");String clientId="kp_client_"+random(18),secret=publicClient?null:"kp_secret_"+random(32);UUID id=Ids.next();OffsetDateTime now=now();repository.insertClient(id,workspace,actor,clientId,secret==null?null:hash(secret),text(name,120,"OAuth client name"),redirects,scopes,publicClient,now);audit.success(workspace,actor,"integration.oauth-client.create","OAUTH_CLIENT",id);return new OAuthClient(id,workspace,clientId,name,redirects,scopes,publicClient,true,now,now,secret);}
    @Transactional(readOnly=true) public List<OAuthClient> clients(UUID actor,UUID workspace){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);return repository.clients(workspace).stream().map(row->client(row,null)).toList();}
    @Transactional(readOnly=true) public OpenPlatformViews.OAuthAuthorizationInfo authorizationInfo(String clientId,String redirectUri,String rawScopes){var client=requireClient(clientId);if(!client.redirectUris().contains(redirectUri))throw new IllegalArgumentException("OAuth redirect URI does not exactly match the registered URI");Set<String> scopes=rawScopes==null||rawScopes.isBlank()?client.scopes():OpenPlatformScopes.parse(rawScopes);if(!client.scopes().containsAll(scopes))throw new IllegalArgumentException("Requested OAuth scope is not allowed for this client");return new OpenPlatformViews.OAuthAuthorizationInfo(client.clientId(),client.name(),redirectUri,scopes,client.publicClient());}
    @Transactional public void setClientActive(UUID actor,UUID workspace,UUID id,boolean active){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);if(repository.setClientActive(id,workspace,active,now())==0)throw new ResourceNotFoundException();audit.success(workspace,actor,active?"integration.oauth-client.enable":"integration.oauth-client.disable","OAUTH_CLIENT",id);}
    @Transactional public AuthorizationGrant authorize(UUID actor,String clientId,String redirectUri,String rawScopes,String state,String challenge,String method,boolean consent){if(!consent)throw new IllegalArgumentException("OAuth consent is required");var client=requireClient(clientId);authorization.require(actor,ResourceType.WORKSPACE,client.workspaceId(),Capability.READ);if(!client.redirectUris().contains(redirectUri))throw new IllegalArgumentException("OAuth redirect URI does not exactly match the registered URI");if(!"S256".equals(method)||challenge==null||challenge.length()<43||challenge.length()>128)throw new IllegalArgumentException("OAuth PKCE S256 challenge is required");Set<String> scopes=rawScopes==null||rawScopes.isBlank()?client.scopes():OpenPlatformScopes.parse(rawScopes);if(!client.scopes().containsAll(scopes))throw new IllegalArgumentException("Requested OAuth scope is not allowed for this client");String code="kp_code_"+random(32);OffsetDateTime now=now();repository.insertCode(Ids.next(),hash(code),client.id(),actor,client.workspaceId(),redirectUri,scopes,challenge,now.plus(CODE_TTL),now);audit.success(client.workspaceId(),actor,"integration.oauth.authorize","OAUTH_CLIENT",client.id());return new AuthorizationGrant(appendCode(redirectUri,code,state),code,state,scopes);}
    @Transactional public Token exchangeCode(String clientId,String clientSecret,String code,String redirectUri,String verifier){var client=authenticatedClient(clientId,clientSecret);var grant=repository.codeForUpdate(hash(required(code,"Authorization code")));OffsetDateTime now=now();if(grant==null||!grant.clientId().equals(client.id())||grant.usedAt()!=null||!grant.expiresAt().isAfter(now)||!grant.redirectUri().equals(redirectUri))throw new IllegalArgumentException("Authorization code is invalid or expired");if(verifier==null||verifier.length()<43||verifier.length()>128||!constantTime(grant.challenge().getBytes(StandardCharsets.US_ASCII),pkce(verifier).getBytes(StandardCharsets.US_ASCII)))throw new IllegalArgumentException("PKCE verifier is invalid");repository.useCode(grant.id(),now);UUID family=Ids.next();repository.insertFamily(family,client.id(),grant.userId(),grant.workspaceId(),grant.scopes(),now);return issue(client,grant.userId(),grant.workspaceId(),grant.scopes(),family,now);}
    @Transactional(noRollbackFor=OpenPlatformTokenReuseException.class) public Token refresh(String clientId,String clientSecret,String rawRefresh){var client=authenticatedClient(clientId,clientSecret);var token=repository.refreshForUpdate(hash(required(rawRefresh,"Refresh token")));OffsetDateTime now=now();if(token==null||!token.clientId().equals(client.id()))throw new IllegalArgumentException("Refresh token is invalid");if(token.usedAt()!=null){repository.revokeFamily(token.familyId(),now);throw new OpenPlatformTokenReuseException();}if(!token.expiresAt().isAfter(now)||!repository.familyActive(token.familyId()))throw new IllegalArgumentException("Refresh token is expired or revoked");Token result=issue(client,token.userId(),token.workspaceId(),token.scopes(),token.familyId(),now);UUID replacement=repository.refreshForUpdate(hash(result.refreshToken())).id();repository.rotateRefresh(token.id(),replacement,now);return result;}
    @Transactional public void revokeTokenFamily(UUID actor,UUID workspace,UUID family){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);repository.revokeFamily(family,now());audit.success(workspace,actor,"integration.oauth-token.revoke","OAUTH_TOKEN_FAMILY",family);}

    @Transactional public Webhook createWebhook(UUID actor,UUID workspace,String name,String endpointUrl,Set<String> rawEvents){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);URI endpoint=endpoints.validate(endpointUrl);Set<String> events=events(rawEvents);String secret="whsec_"+random(32);UUID id=Ids.next();OffsetDateTime now=now();repository.insertWebhook(id,workspace,actor,text(name,120,"Webhook name"),endpoint.toASCIIString(),cipher.encrypt("webhook.secret."+id,secret),events,now);audit.success(workspace,actor,"integration.webhook.create","WEBHOOK",id);return new Webhook(id,workspace,name,endpoint.toASCIIString(),events,true,0,null,now,now,secret);}
    @Transactional(readOnly=true) public List<Webhook> webhooks(UUID actor,UUID workspace){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);return repository.webhooks(workspace).stream().map(row->webhook(row,null)).toList();}
    @Transactional public void setWebhookActive(UUID actor,UUID workspace,UUID id,boolean active){authorization.require(actor,ResourceType.WORKSPACE,workspace,Capability.MANAGE);if(repository.setWebhookActive(id,workspace,active,now())==0)throw new ResourceNotFoundException();audit.success(workspace,actor,active?"integration.webhook.enable":"integration.webhook.disable","WEBHOOK",id);}
    @Transactional(readOnly=true) public List<WebhookDelivery> deliveries(UUID actor,UUID webhook,int limit){var hook=requireWebhook(webhook);authorization.require(actor,ResourceType.WORKSPACE,hook.workspaceId(),Capability.MANAGE);return deliveryViews(repository.deliveries(webhook,Math.max(1,Math.min(limit,200)),0));}
    @Transactional(readOnly=true) public WebhookDeliveryPage deliveryPage(UUID actor,UUID webhook,int limit,int offset){var hook=requireWebhook(webhook);authorization.require(actor,ResourceType.WORKSPACE,hook.workspaceId(),Capability.MANAGE);int count=Math.max(1,Math.min(limit,50)),start=Math.max(0,Math.min(offset,1_000_000));List<WebhookDelivery> rows=deliveryViews(repository.deliveries(webhook,count+1,start));boolean more=rows.size()>count;List<WebhookDelivery> items=List.copyOf(rows.subList(0,Math.min(rows.size(),count)));return new WebhookDeliveryPage(items,start+items.size(),more);}
    @Transactional public void replay(UUID actor,UUID webhook,UUID delivery){var hook=requireWebhook(webhook);authorization.require(actor,ResourceType.WORKSPACE,hook.workspaceId(),Capability.MANAGE);repository.setWebhookActive(webhook,hook.workspaceId(),true,now());if(repository.replay(delivery,webhook,now())==0)throw new ResourceNotFoundException();audit.success(hook.workspaceId(),actor,"integration.webhook.replay","WEBHOOK_DELIVERY",delivery);}
    @Transactional public void sendTest(UUID actor,UUID webhook){var hook=requireWebhook(webhook);authorization.require(actor,ResourceType.WORKSPACE,hook.workspaceId(),Capability.MANAGE);audit.success(hook.workspaceId(),actor,"webhook.test","WEBHOOK",webhook);}

    @Transactional public CredentialIdentity authenticate(String raw){if(raw==null||raw.isBlank())return null;OffsetDateTime now=now();if(raw.startsWith("kp_live_")){int start="kp_live_".length(),separator=start+API_KEY_PREFIX_LENGTH;if(raw.length()<=separator||raw.charAt(separator)!='_')return null;var row=repository.apiCredential(raw.substring(start,separator));if(row==null||row.revokedAt()!=null||row.expiresAt()!=null&&!row.expiresAt().isAfter(now)||!constantTime(row.hash(),hash(raw)))return null;repository.touchApiKey(row.id(),now);return new CredentialIdentity(row.id(),"API_KEY",row.workspaceId(),row.userId(),row.email(),row.admin(),row.scopes());}if(raw.startsWith("kp_oauth_")){var row=repository.accessCredential(hash(raw));if(row==null||row.revokedAt()!=null||row.familyRevokedAt()!=null||!row.expiresAt().isAfter(now))return null;repository.touchAccess(row.id(),now);return new CredentialIdentity(row.id(),"OAUTH",row.workspaceId(),row.userId(),row.email(),row.admin(),row.scopes());}return null;}

    private Token issue(OpenPlatformRepository.ClientRow client,UUID user,UUID workspace,Set<String> scopes,UUID family,OffsetDateTime now){String access="kp_oauth_"+random(36);repository.insertAccess(Ids.next(),hash(access),family,client.id(),user,workspace,scopes,now.plus(ACCESS_TTL),now);String refresh=null;if(scopes.contains("offline_access")){refresh="kp_refresh_"+random(40);repository.insertRefresh(Ids.next(),hash(refresh),family,client.id(),user,workspace,scopes,now.plus(REFRESH_TTL),now);}return new Token(access,"Bearer",ACCESS_TTL.toSeconds(),refresh,scopes);}
    private OpenPlatformRepository.ClientRow authenticatedClient(String id,String secret){var client=requireClient(id);if(!client.publicClient()&&(secret==null||!constantTime(client.secretHash(),hash(secret))))throw new IllegalArgumentException("OAuth client authentication failed");return client;}
    private OpenPlatformRepository.ClientRow requireClient(String id){var value=repository.client(required(id,"Client id"));if(value==null||!value.active())throw new IllegalArgumentException("OAuth client is invalid or disabled");return value;}
    private OpenPlatformRepository.WebhookRow requireWebhook(UUID id){var value=repository.webhook(id);if(value==null)throw new ResourceNotFoundException();return value;}
    private static OAuthClient client(OpenPlatformRepository.ClientRow row,String secret){return new OAuthClient(row.id(),row.workspaceId(),row.clientId(),row.name(),row.redirectUris(),row.scopes(),row.publicClient(),row.active(),row.createdAt(),row.updatedAt(),secret);}
    private static Webhook webhook(OpenPlatformRepository.WebhookRow row,String secret){return new Webhook(row.id(),row.workspaceId(),row.name(),row.endpointUrl(),row.events(),row.active(),row.consecutiveFailures(),row.suspendedAt(),row.createdAt(),row.updatedAt(),secret);}
    private static List<WebhookDelivery> deliveryViews(List<OpenPlatformRepository.DeliveryViewRow> rows){return rows.stream().map(row->new WebhookDelivery(row.id(),row.webhookId(),row.eventId(),row.eventType(),row.status(),row.attempts(),row.nextAttemptAt(),row.responseStatus(),row.lastError(),row.deliveredAt(),row.createdAt(),row.updatedAt())).toList();}
    private static Set<String> events(Set<String> values){if(values==null||values.isEmpty())throw new IllegalArgumentException("At least one webhook event is required");var normalized=values.stream().map(value->value==null?"":value.trim().toLowerCase(Locale.ROOT)).filter(value->value.matches("\\*|[a-z0-9-]+(?:\\.[a-z0-9*-]+)+")).limit(100).collect(java.util.stream.Collectors.toUnmodifiableSet());if(normalized.isEmpty())throw new IllegalArgumentException("Webhook events are invalid");return normalized;}
    private static String redirect(String value){try{URI uri=URI.create(value);if(!uri.isAbsolute()||uri.getFragment()!=null||uri.getRawUserInfo()!=null)throw new IllegalArgumentException();boolean localhost="localhost".equalsIgnoreCase(uri.getHost())||"127.0.0.1".equals(uri.getHost());if(!"https".equalsIgnoreCase(uri.getScheme())&&!(localhost&&"http".equalsIgnoreCase(uri.getScheme())))throw new IllegalArgumentException();return uri.toASCIIString();}catch(Exception exception){throw new IllegalArgumentException("OAuth redirect URI must be an absolute HTTPS URL (HTTP is only allowed for localhost)");}}
    private static String appendCode(String redirect,String code,String state){String separator=redirect.contains("?")?"&":"?";return redirect+separator+"code="+url(code)+(state==null||state.isBlank()?"":"&state="+url(state));}
    private static String pkce(String verifier){return URL.encodeToString(hash(verifier));}private static String url(String value){return java.net.URLEncoder.encode(value,StandardCharsets.UTF_8);}
    private static String random(int bytes){byte[] value=new byte[bytes];RANDOM.nextBytes(value);return URL.encodeToString(value);}
    private static String randomHex(int bytes){byte[] value=new byte[bytes];RANDOM.nextBytes(value);return HexFormat.of().formatHex(value);}
    private static byte[] hash(String value){try{return MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));}catch(Exception exception){throw new IllegalStateException(exception);}}
    private static boolean constantTime(byte[] left,byte[] right){return left!=null&&right!=null&&MessageDigest.isEqual(left,right);}
    private static String text(String value,int max,String label){String normalized=required(value,label).trim();if(normalized.length()>max)throw new IllegalArgumentException(label+" is too long");return normalized;}private static String required(String value,String label){if(value==null||value.isBlank())throw new IllegalArgumentException(label+" is required");return value;}
    private OffsetDateTime now(){return OffsetDateTime.now(clock);}
}
