package io.knowledge.platform.integration;

import static org.jooq.impl.DSL.field;import static org.jooq.impl.DSL.name;import static org.jooq.impl.DSL.table;
import java.time.OffsetDateTime;import java.util.List;import java.util.Set;import java.util.UUID;import org.jooq.DSLContext;import org.jooq.JSONB;import org.springframework.stereotype.Repository;

@Repository
public class OpenPlatformRepository {
    private final DSLContext dsl;OpenPlatformRepository(DSLContext dsl){this.dsl=dsl;}

    void insertApiKey(UUID id,UUID workspace,UUID user,String keyName,String prefix,byte[] hash,Set<String> scopes,OffsetDateTime expires,OffsetDateTime now){dsl.insertInto(table(name("api_keys"))).columns(field(name("id")),field(name("workspace_id")),field(name("user_id")),field(name("name")),field(name("key_prefix")),field(name("secret_hash")),field(name("scopes")),field(name("expires_at")),field(name("created_at"))).values(id,workspace,user,keyName,prefix,hash,scopes.toArray(String[]::new),expires,now).execute();}
    List<ApiKeyRow> apiKeys(UUID workspace){return dsl.select(field(name("id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("user_id"),UUID.class),field(name("name"),String.class),field(name("key_prefix"),String.class),field(name("scopes"),String[].class),field(name("last_used_at"),OffsetDateTime.class),field(name("expires_at"),OffsetDateTime.class),field(name("revoked_at"),OffsetDateTime.class),field(name("created_at"),OffsetDateTime.class)).from(table(name("api_keys"))).where(field(name("workspace_id"),UUID.class).eq(workspace)).orderBy(field(name("created_at")).desc()).fetch(r->new ApiKeyRow(r.value1(),r.value2(),r.value3(),r.value4(),r.value5(),set(r.value6()),r.value7(),r.value8(),r.value9(),r.value10()));}
    ApiCredentialRow apiCredential(String prefix){return dsl.select(field(name("k","id"),UUID.class),field(name("k","workspace_id"),UUID.class),field(name("k","user_id"),UUID.class),field(name("u","email_original"),String.class),field("exists(select 1 from instance_roles ir where ir.user_id=u.id and ir.role in ('OWNER','ADMIN'))",Boolean.class),field(name("k","secret_hash"),byte[].class),field(name("k","scopes"),String[].class),field(name("k","expires_at"),OffsetDateTime.class),field(name("k","revoked_at"),OffsetDateTime.class)).from(table(name("api_keys")).as("k")).join(table(name("users")).as("u")).on(field(name("u","id"),UUID.class).eq(field(name("k","user_id"),UUID.class))).where(field(name("k","key_prefix"),String.class).eq(prefix).and(field(name("u","status"),String.class).eq("ACTIVE"))).fetchOne(r->new ApiCredentialRow(r.value1(),r.value2(),r.value3(),r.value4(),Boolean.TRUE.equals(r.value5()),r.value6(),set(r.value7()),r.value8(),r.value9()));}
    void touchApiKey(UUID id,OffsetDateTime now){dsl.update(table(name("api_keys"))).set(field(name("last_used_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id)).execute();}
    int revokeApiKey(UUID id,UUID workspace,OffsetDateTime now){return dsl.update(table(name("api_keys"))).set(field(name("revoked_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id).and(field(name("workspace_id"),UUID.class).eq(workspace)).and(field(name("revoked_at"),OffsetDateTime.class).isNull())).execute();}

    void insertClient(UUID id,UUID workspace,UUID owner,String clientId,byte[] secretHash,String clientName,List<String> redirects,Set<String> scopes,boolean publicClient,OffsetDateTime now){dsl.insertInto(table(name("oauth_clients"))).columns(field(name("id")),field(name("workspace_id")),field(name("owner_id")),field(name("client_id")),field(name("client_secret_hash")),field(name("name")),field(name("redirect_uris")),field(name("scopes")),field(name("public_client")),field(name("created_at")),field(name("updated_at"))).values(id,workspace,owner,clientId,secretHash,clientName,redirects.toArray(String[]::new),scopes.toArray(String[]::new),publicClient,now,now).execute();}
    List<ClientRow> clients(UUID workspace){return dsl.select(field(name("id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("owner_id"),UUID.class),field(name("client_id"),String.class),field(name("client_secret_hash"),byte[].class),field(name("name"),String.class),field(name("redirect_uris"),String[].class),field(name("scopes"),String[].class),field(name("public_client"),Boolean.class),field(name("active"),Boolean.class),field(name("created_at"),OffsetDateTime.class),field(name("updated_at"),OffsetDateTime.class)).from(table(name("oauth_clients"))).where(field(name("workspace_id"),UUID.class).eq(workspace)).orderBy(field(name("created_at")).desc()).fetch(OpenPlatformRepository::client);}
    ClientRow client(String clientId){return dsl.select(field(name("id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("owner_id"),UUID.class),field(name("client_id"),String.class),field(name("client_secret_hash"),byte[].class),field(name("name"),String.class),field(name("redirect_uris"),String[].class),field(name("scopes"),String[].class),field(name("public_client"),Boolean.class),field(name("active"),Boolean.class),field(name("created_at"),OffsetDateTime.class),field(name("updated_at"),OffsetDateTime.class)).from(table(name("oauth_clients"))).where(field(name("client_id"),String.class).eq(clientId)).fetchOne(OpenPlatformRepository::client);}
    int setClientActive(UUID id,UUID workspace,boolean active,OffsetDateTime now){return dsl.update(table(name("oauth_clients"))).set(field(name("active"),Boolean.class),active).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id).and(field(name("workspace_id"),UUID.class).eq(workspace))).execute();}
    void insertCode(UUID id,byte[] hash,UUID client,UUID user,UUID workspace,String redirect,Set<String> scopes,String challenge,OffsetDateTime expires,OffsetDateTime now){dsl.insertInto(table(name("oauth_authorization_codes"))).columns(field(name("id")),field(name("code_hash")),field(name("client_id")),field(name("user_id")),field(name("workspace_id")),field(name("redirect_uri")),field(name("scopes")),field(name("code_challenge")),field(name("expires_at")),field(name("created_at"))).values(id,hash,client,user,workspace,redirect,scopes.toArray(String[]::new),challenge,expires,now).execute();}
    CodeRow codeForUpdate(byte[] hash){return dsl.select(field(name("id"),UUID.class),field(name("client_id"),UUID.class),field(name("user_id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("redirect_uri"),String.class),field(name("scopes"),String[].class),field(name("code_challenge"),String.class),field(name("expires_at"),OffsetDateTime.class),field(name("used_at"),OffsetDateTime.class)).from(table(name("oauth_authorization_codes"))).where(field(name("code_hash"),byte[].class).eq(hash)).forUpdate().fetchOne(r->new CodeRow(r.value1(),r.value2(),r.value3(),r.value4(),r.value5(),set(r.value6()),r.value7(),r.value8(),r.value9()));}
    void useCode(UUID id,OffsetDateTime now){dsl.update(table(name("oauth_authorization_codes"))).set(field(name("used_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id)).execute();}
    void insertFamily(UUID id,UUID client,UUID user,UUID workspace,Set<String> scopes,OffsetDateTime now){dsl.insertInto(table(name("oauth_token_families"))).columns(field(name("id")),field(name("client_id")),field(name("user_id")),field(name("workspace_id")),field(name("scopes")),field(name("created_at"))).values(id,client,user,workspace,scopes.toArray(String[]::new),now).execute();}
    void insertAccess(UUID id,byte[] hash,UUID family,UUID client,UUID user,UUID workspace,Set<String> scopes,OffsetDateTime expires,OffsetDateTime now){dsl.insertInto(table(name("oauth_access_tokens"))).columns(field(name("id")),field(name("token_hash")),field(name("family_id")),field(name("client_id")),field(name("user_id")),field(name("workspace_id")),field(name("scopes")),field(name("expires_at")),field(name("created_at"))).values(id,hash,family,client,user,workspace,scopes.toArray(String[]::new),expires,now).execute();}
    void insertRefresh(UUID id,byte[] hash,UUID family,UUID client,UUID user,UUID workspace,Set<String> scopes,OffsetDateTime expires,OffsetDateTime now){dsl.insertInto(table(name("oauth_refresh_tokens"))).columns(field(name("id")),field(name("token_hash")),field(name("family_id")),field(name("client_id")),field(name("user_id")),field(name("workspace_id")),field(name("scopes")),field(name("expires_at")),field(name("created_at"))).values(id,hash,family,client,user,workspace,scopes.toArray(String[]::new),expires,now).execute();}
    AccessCredentialRow accessCredential(byte[] hash){return dsl.select(field(name("t","id"),UUID.class),field(name("t","workspace_id"),UUID.class),field(name("t","user_id"),UUID.class),field(name("u","email_original"),String.class),field("exists(select 1 from instance_roles ir where ir.user_id=u.id and ir.role in ('OWNER','ADMIN'))",Boolean.class),field(name("t","scopes"),String[].class),field(name("t","expires_at"),OffsetDateTime.class),field(name("t","revoked_at"),OffsetDateTime.class),field(name("f","revoked_at"),OffsetDateTime.class)).from(table(name("oauth_access_tokens")).as("t")).join(table(name("users")).as("u")).on(field(name("u","id"),UUID.class).eq(field(name("t","user_id"),UUID.class))).leftJoin(table(name("oauth_token_families")).as("f")).on(field(name("f","id"),UUID.class).eq(field(name("t","family_id"),UUID.class))).join(table(name("oauth_clients")).as("c")).on(field(name("c","id"),UUID.class).eq(field(name("t","client_id"),UUID.class))).where(field(name("t","token_hash"),byte[].class).eq(hash).and(field(name("u","status"),String.class).eq("ACTIVE")).and(field(name("c","active"),Boolean.class).eq(true))).fetchOne(r->new AccessCredentialRow(r.value1(),r.value2(),r.value3(),r.value4(),Boolean.TRUE.equals(r.value5()),set(r.value6()),r.value7(),r.value8(),r.value9()));}
    void touchAccess(UUID id,OffsetDateTime now){dsl.update(table(name("oauth_access_tokens"))).set(field(name("last_used_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id)).execute();}
    RefreshRow refreshForUpdate(byte[] hash){return dsl.select(field(name("id"),UUID.class),field(name("family_id"),UUID.class),field(name("client_id"),UUID.class),field(name("user_id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("scopes"),String[].class),field(name("expires_at"),OffsetDateTime.class),field(name("used_at"),OffsetDateTime.class)).from(table(name("oauth_refresh_tokens"))).where(field(name("token_hash"),byte[].class).eq(hash)).forUpdate().fetchOne(r->new RefreshRow(r.value1(),r.value2(),r.value3(),r.value4(),r.value5(),set(r.value6()),r.value7(),r.value8()));}
    boolean familyActive(UUID family){return dsl.fetchExists(dsl.selectOne().from(table(name("oauth_token_families"))).where(field(name("id"),UUID.class).eq(family).and(field(name("revoked_at"),OffsetDateTime.class).isNull())));}
    void rotateRefresh(UUID oldId,UUID replacement,OffsetDateTime now){dsl.update(table(name("oauth_refresh_tokens"))).set(field(name("used_at"),OffsetDateTime.class),now).set(field(name("replaced_by"),UUID.class),replacement).where(field(name("id"),UUID.class).eq(oldId)).execute();}
    void revokeFamily(UUID family,OffsetDateTime now){dsl.update(table(name("oauth_token_families"))).set(field(name("revoked_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(family).and(field(name("revoked_at"),OffsetDateTime.class).isNull())).execute();dsl.update(table(name("oauth_access_tokens"))).set(field(name("revoked_at"),OffsetDateTime.class),now).where(field(name("family_id"),UUID.class).eq(family).and(field(name("revoked_at"),OffsetDateTime.class).isNull())).execute();}

    void insertWebhook(UUID id,UUID workspace,UUID creator,String hookName,String endpoint,String encrypted,Set<String> events,OffsetDateTime now){dsl.insertInto(table(name("webhook_subscriptions"))).columns(field(name("id")),field(name("workspace_id")),field(name("created_by")),field(name("name")),field(name("endpoint_url")),field(name("secret_encrypted")),field(name("events")),field(name("created_at")),field(name("updated_at"))).values(id,workspace,creator,hookName,endpoint,encrypted,events.toArray(String[]::new),now,now).execute();}
    List<WebhookRow> webhooks(UUID workspace){return dsl.select(field(name("id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("created_by"),UUID.class),field(name("name"),String.class),field(name("endpoint_url"),String.class),field(name("secret_encrypted"),String.class),field(name("events"),String[].class),field(name("active"),Boolean.class),field(name("consecutive_failures"),Integer.class),field(name("suspended_at"),OffsetDateTime.class),field(name("created_at"),OffsetDateTime.class),field(name("updated_at"),OffsetDateTime.class)).from(table(name("webhook_subscriptions"))).where(field(name("workspace_id"),UUID.class).eq(workspace)).orderBy(field(name("created_at")).desc()).fetch(OpenPlatformRepository::webhook);}
    WebhookRow webhook(UUID id){return dsl.select(field(name("id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("created_by"),UUID.class),field(name("name"),String.class),field(name("endpoint_url"),String.class),field(name("secret_encrypted"),String.class),field(name("events"),String[].class),field(name("active"),Boolean.class),field(name("consecutive_failures"),Integer.class),field(name("suspended_at"),OffsetDateTime.class),field(name("created_at"),OffsetDateTime.class),field(name("updated_at"),OffsetDateTime.class)).from(table(name("webhook_subscriptions"))).where(field(name("id"),UUID.class).eq(id)).fetchOne(OpenPlatformRepository::webhook);}
    List<WebhookRow> activeWebhooks(){return dsl.select(field(name("id"),UUID.class),field(name("workspace_id"),UUID.class),field(name("created_by"),UUID.class),field(name("name"),String.class),field(name("endpoint_url"),String.class),field(name("secret_encrypted"),String.class),field(name("events"),String[].class),field(name("active"),Boolean.class),field(name("consecutive_failures"),Integer.class),field(name("suspended_at"),OffsetDateTime.class),field(name("created_at"),OffsetDateTime.class),field(name("updated_at"),OffsetDateTime.class)).from(table(name("webhook_subscriptions"))).where(field(name("active"),Boolean.class).eq(true).and(field(name("suspended_at"),OffsetDateTime.class).isNull())).fetch(OpenPlatformRepository::webhook);}
    int setWebhookActive(UUID id,UUID workspace,boolean active,OffsetDateTime now){return dsl.update(table(name("webhook_subscriptions"))).set(field(name("active"),Boolean.class),active).set(field(name("suspended_at"),OffsetDateTime.class),(OffsetDateTime)null).set(field(name("consecutive_failures"),Integer.class),0).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id).and(field(name("workspace_id"),UUID.class).eq(workspace))).execute();}
    List<AuditRow> undispatched(UUID webhook,UUID workspace,int limit){return dsl.fetch("select a.id,a.workspace_id,a.actor_id,a.action,a.resource_type,a.resource_id,a.details,a.occurred_at from audit_events a,webhook_subscriptions w where w.id=?::uuid and a.workspace_id=?::uuid and a.outcome='SUCCESS' and (a.occurred_at>coalesce(w.dispatch_cursor_at,w.created_at) or (a.occurred_at=coalesce(w.dispatch_cursor_at,w.created_at) and a.id>coalesce(w.dispatch_cursor_id,'00000000-0000-0000-0000-000000000000'::uuid))) order by a.occurred_at asc,a.id asc limit ?",webhook,workspace,limit).map(r->new AuditRow(r.get("id",UUID.class),r.get("workspace_id",UUID.class),r.get("actor_id",UUID.class),r.get("action",String.class),r.get("resource_type",String.class),r.get("resource_id",UUID.class),r.get("details",JSONB.class),r.get("occurred_at",OffsetDateTime.class)));}
    void advanceDispatchCursor(UUID webhook,AuditRow event){dsl.update(table(name("webhook_subscriptions"))).set(field(name("dispatch_cursor_at"),OffsetDateTime.class),event.occurredAt()).set(field(name("dispatch_cursor_id"),UUID.class),event.id()).where(field(name("id"),UUID.class).eq(webhook)).execute();}
    void insertDelivery(UUID id,UUID webhook,AuditRow event,String eventType,JSONB payload,OffsetDateTime now){dsl.insertInto(table(name("webhook_deliveries"))).columns(field(name("id")),field(name("webhook_id")),field(name("audit_event_id")),field(name("event_type")),field(name("payload")),field(name("status")),field(name("next_attempt_at")),field(name("created_at")),field(name("updated_at"))).values(id,webhook,event.id(),eventType,payload,"PENDING",now,now,now).onConflict(field(name("webhook_id")),field(name("audit_event_id"))).doNothing().execute();}
    List<DeliveryRow> due(OffsetDateTime now,int limit){return dsl.select(field(name("d","id"),UUID.class),field(name("d","webhook_id"),UUID.class),field(name("d","audit_event_id"),UUID.class),field(name("d","event_type"),String.class),field(name("d","payload"),JSONB.class),field(name("d","status"),String.class),field(name("d","attempts"),Integer.class),field(name("d","next_attempt_at"),OffsetDateTime.class),field(name("w","endpoint_url"),String.class),field(name("w","secret_encrypted"),String.class),field(name("w","workspace_id"),UUID.class)).from(table(name("webhook_deliveries")).as("d")).join(table(name("webhook_subscriptions")).as("w")).on(field(name("w","id"),UUID.class).eq(field(name("d","webhook_id"),UUID.class))).where(field(name("d","status"),String.class).in("PENDING","RETRYING").and(field(name("d","next_attempt_at"),OffsetDateTime.class).le(now)).and(field(name("w","active"),Boolean.class).eq(true)).and(field(name("w","suspended_at"),OffsetDateTime.class).isNull())).orderBy(field(name("d","next_attempt_at")).asc()).limit(limit).fetch(r->new DeliveryRow(r.value1(),r.value2(),r.value3(),r.value4(),r.value5(),r.value6(),r.value7(),r.value8(),r.value9(),r.value10(),r.value11()));}
    void beginAttempt(UUID id,int attempts,OffsetDateTime now){dsl.update(table(name("webhook_deliveries"))).set(field(name("attempts"),Integer.class),attempts).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id)).execute();}
    void delivered(UUID id,UUID webhook,int status,OffsetDateTime now){dsl.update(table(name("webhook_deliveries"))).set(field(name("status"),String.class),"DELIVERED").set(field(name("response_status"),Integer.class),status).set(field(name("last_error"),String.class),(String)null).set(field(name("delivered_at"),OffsetDateTime.class),now).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id)).execute();dsl.update(table(name("webhook_subscriptions"))).set(field(name("consecutive_failures"),Integer.class),0).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(webhook)).execute();}
    void failed(UUID id,UUID webhook,int attempts,Integer status,String error,OffsetDateTime next,boolean dead,OffsetDateTime now){dsl.update(table(name("webhook_deliveries"))).set(field(name("status"),String.class),dead?"DEAD":"RETRYING").set(field(name("response_status"),Integer.class),status).set(field(name("last_error"),String.class),error).set(field(name("next_attempt_at"),OffsetDateTime.class),next).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(id)).execute();dsl.update(table(name("webhook_subscriptions"))).set(field(name("consecutive_failures"),Integer.class),field(name("consecutive_failures"),Integer.class).plus(1)).set(field(name("suspended_at"),OffsetDateTime.class),dead?now:null).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(webhook)).execute();}
    List<DeliveryViewRow> deliveries(UUID webhook,int limit,int offset){return dsl.select(field(name("id"),UUID.class),field(name("webhook_id"),UUID.class),field(name("audit_event_id"),UUID.class),field(name("event_type"),String.class),field(name("status"),String.class),field(name("attempts"),Integer.class),field(name("next_attempt_at"),OffsetDateTime.class),field(name("response_status"),Integer.class),field(name("last_error"),String.class),field(name("delivered_at"),OffsetDateTime.class),field(name("created_at"),OffsetDateTime.class),field(name("updated_at"),OffsetDateTime.class)).from(table(name("webhook_deliveries"))).where(field(name("webhook_id"),UUID.class).eq(webhook)).orderBy(field(name("created_at")).desc(),field(name("id")).desc()).limit(limit).offset(Math.max(0,offset)).fetch(r->new DeliveryViewRow(r.value1(),r.value2(),r.value3(),r.value4(),r.value5(),r.value6(),r.value7(),r.value8(),r.value9(),r.value10(),r.value11(),r.value12()));}
    int replay(UUID delivery,UUID webhook,OffsetDateTime now){return dsl.update(table(name("webhook_deliveries"))).set(field(name("status"),String.class),"PENDING").set(field(name("attempts"),Integer.class),0).set(field(name("next_attempt_at"),OffsetDateTime.class),now).set(field(name("response_status"),Integer.class),(Integer)null).set(field(name("last_error"),String.class),(String)null).set(field(name("delivered_at"),OffsetDateTime.class),(OffsetDateTime)null).set(field(name("updated_at"),OffsetDateTime.class),now).where(field(name("id"),UUID.class).eq(delivery).and(field(name("webhook_id"),UUID.class).eq(webhook))).execute();}

    private static ClientRow client(org.jooq.Record r){return new ClientRow(r.get(field(name("id"),UUID.class)),r.get(field(name("workspace_id"),UUID.class)),r.get(field(name("owner_id"),UUID.class)),r.get(field(name("client_id"),String.class)),r.get(field(name("client_secret_hash"),byte[].class)),r.get(field(name("name"),String.class)),List.of(r.get(field(name("redirect_uris"),String[].class))),set(r.get(field(name("scopes"),String[].class))),Boolean.TRUE.equals(r.get(field(name("public_client"),Boolean.class))),Boolean.TRUE.equals(r.get(field(name("active"),Boolean.class))),r.get(field(name("created_at"),OffsetDateTime.class)),r.get(field(name("updated_at"),OffsetDateTime.class)));}
    private static WebhookRow webhook(org.jooq.Record r){return new WebhookRow(r.get(field(name("id"),UUID.class)),r.get(field(name("workspace_id"),UUID.class)),r.get(field(name("created_by"),UUID.class)),r.get(field(name("name"),String.class)),r.get(field(name("endpoint_url"),String.class)),r.get(field(name("secret_encrypted"),String.class)),set(r.get(field(name("events"),String[].class))),Boolean.TRUE.equals(r.get(field(name("active"),Boolean.class))),r.get(field(name("consecutive_failures"),Integer.class)),r.get(field(name("suspended_at"),OffsetDateTime.class)),r.get(field(name("created_at"),OffsetDateTime.class)),r.get(field(name("updated_at"),OffsetDateTime.class)));}
    private static Set<String> set(String[] values){return values==null?Set.of():Set.of(values);}
    record ApiKeyRow(UUID id,UUID workspaceId,UUID userId,String name,String prefix,Set<String> scopes,OffsetDateTime lastUsedAt,OffsetDateTime expiresAt,OffsetDateTime revokedAt,OffsetDateTime createdAt){}
    record ApiCredentialRow(UUID id,UUID workspaceId,UUID userId,String email,boolean admin,byte[] hash,Set<String> scopes,OffsetDateTime expiresAt,OffsetDateTime revokedAt){}
    record ClientRow(UUID id,UUID workspaceId,UUID ownerId,String clientId,byte[] secretHash,String name,List<String> redirectUris,Set<String> scopes,boolean publicClient,boolean active,OffsetDateTime createdAt,OffsetDateTime updatedAt){}
    record CodeRow(UUID id,UUID clientId,UUID userId,UUID workspaceId,String redirectUri,Set<String> scopes,String challenge,OffsetDateTime expiresAt,OffsetDateTime usedAt){}
    record AccessCredentialRow(UUID id,UUID workspaceId,UUID userId,String email,boolean admin,Set<String> scopes,OffsetDateTime expiresAt,OffsetDateTime revokedAt,OffsetDateTime familyRevokedAt){}
    record RefreshRow(UUID id,UUID familyId,UUID clientId,UUID userId,UUID workspaceId,Set<String> scopes,OffsetDateTime expiresAt,OffsetDateTime usedAt){}
    record WebhookRow(UUID id,UUID workspaceId,UUID createdBy,String name,String endpointUrl,String secretEncrypted,Set<String> events,boolean active,int consecutiveFailures,OffsetDateTime suspendedAt,OffsetDateTime createdAt,OffsetDateTime updatedAt){}
    record AuditRow(UUID id,UUID workspaceId,UUID actorId,String action,String resourceType,UUID resourceId,JSONB details,OffsetDateTime occurredAt){}
    record DeliveryRow(UUID id,UUID webhookId,UUID eventId,String eventType,JSONB payload,String status,int attempts,OffsetDateTime nextAttemptAt,String endpointUrl,String secretEncrypted,UUID workspaceId){}
    record DeliveryViewRow(UUID id,UUID webhookId,UUID eventId,String eventType,String status,int attempts,OffsetDateTime nextAttemptAt,Integer responseStatus,String lastError,OffsetDateTime deliveredAt,OffsetDateTime createdAt,OffsetDateTime updatedAt){}
}
