package io.knowledge.platform.integration;

import io.knowledge.platform.common.Ids;import io.knowledge.platform.common.SecretCipher;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.nio.charset.StandardCharsets;import java.time.Clock;import java.time.Duration;import java.time.OffsetDateTime;import java.util.HexFormat;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import org.jooq.JSONB;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;

@Component
public class WebhookDispatcher {
    private static final int MAX_ATTEMPTS=8;private final OpenPlatformRepository repository;private final SecretCipher cipher;private final WebhookEndpointPolicy endpoints;private final ObjectMapper mapper;private final Clock clock;private final HttpClient client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).followRedirects(HttpClient.Redirect.NEVER).build();
    public WebhookDispatcher(OpenPlatformRepository repository,SecretCipher cipher,WebhookEndpointPolicy endpoints,ObjectMapper mapper,Clock clock){this.repository=repository;this.cipher=cipher;this.endpoints=endpoints;this.mapper=mapper;this.clock=clock;}

    @Scheduled(fixedDelayString="${platform.webhooks.enqueue-delay-ms:1000}")
    @Transactional public void enqueue(){OffsetDateTime now=now();for(var hook:repository.activeWebhooks()){var events=repository.undispatched(hook.id(),hook.workspaceId(),500);for(var event:events){String type=eventType(event.action());if(!matches(hook.events(),type))continue;var payload=mapper.createObjectNode();payload.put("id",event.id().toString());payload.put("type",type);payload.put("workspaceId",event.workspaceId().toString());if(event.actorId()!=null)payload.put("actorId",event.actorId().toString());payload.put("occurredAt",event.occurredAt().toString());var data=payload.putObject("data");data.put("action",event.action());data.put("resourceType",event.resourceType());if(event.resourceId()!=null)data.put("resourceId",event.resourceId().toString());if(event.details()!=null)data.set("details",mapper.readTree(event.details().data()));repository.insertDelivery(Ids.next(),hook.id(),event,type,JSONB.valueOf(mapper.writeValueAsString(payload)),now);}if(!events.isEmpty())repository.advanceDispatchCursor(hook.id(),events.getLast());}}

    @Scheduled(fixedDelayString="${platform.webhooks.delivery-delay-ms:1000}")
    public void deliver(){for(var delivery:repository.due(now(),50))deliver(delivery);}

    private void deliver(OpenPlatformRepository.DeliveryRow delivery){int attempts=delivery.attempts()+1;OffsetDateTime now=now();repository.beginAttempt(delivery.id(),attempts,now);Integer status=null;String error=null;try{var endpoint=endpoints.validate(delivery.endpointUrl());String body=delivery.payload().data();String timestamp=Long.toString(now.toEpochSecond());String secret=cipher.decrypt("webhook.secret."+delivery.webhookId(),delivery.secretEncrypted());String signature=signature(secret,timestamp+"."+body);HttpRequest request=HttpRequest.newBuilder(endpoint).timeout(Duration.ofSeconds(10)).header("Content-Type","application/json").header("User-Agent","KnowledgePlatform-Webhooks/1.0").header("X-Knowledge-Event",delivery.eventType()).header("X-Knowledge-Delivery",delivery.id().toString()).header("X-Knowledge-Timestamp",timestamp).header("X-Knowledge-Signature","v1="+signature).POST(HttpRequest.BodyPublishers.ofString(body,StandardCharsets.UTF_8)).build();HttpResponse<Void> response=client.send(request,HttpResponse.BodyHandlers.discarding());status=response.statusCode();if(status>=200&&status<300){repository.delivered(delivery.id(),delivery.webhookId(),status,now);return;}error="Webhook returned HTTP "+status;}catch(InterruptedException exception){Thread.currentThread().interrupt();error="Webhook delivery was interrupted";}catch(Exception exception){error=abbreviate(exception.getMessage());}boolean dead=attempts>=MAX_ATTEMPTS;long delay=Math.min(3600L,1L<<Math.min(attempts,12));repository.failed(delivery.id(),delivery.webhookId(),attempts,status,error,now.plusSeconds(delay),dead,now);}

    private static String eventType(String action){return switch(action){case"page.create"->"document.created";case"page.update","collaboration.materialize"->"document.updated";case"page.trash"->"document.trashed";case"page.restore"->"document.restored";case"page.delete-permanently"->"document.deleted";case"page.publish","page.publish-auto"->"document.published";case"page.unpublish"->"document.unpublished";case"comment.create","comment.create-via-share"->"comment.created";case"comment.update"->"comment.updated";case"comment.resolve"->"comment.resolved";case"comment.reopen"->"comment.reopened";case"comment.delete","comment.delete-via-share"->"comment.deleted";case"webhook.test"->"webhook.test";default->action;};}
    private static boolean matches(java.util.Set<String> subscriptions,String type){if(subscriptions.contains("*")||subscriptions.contains(type))return true;int separator=type.indexOf('.');return separator>0&&subscriptions.contains(type.substring(0,separator)+".*");}
    private static String signature(String secret,String input){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return HexFormat.of().formatHex(mac.doFinal(input.getBytes(StandardCharsets.UTF_8)));}catch(Exception exception){throw new IllegalStateException("Unable to sign webhook",exception);}}
    private static String abbreviate(String value){String normalized=value==null?"Webhook delivery failed":value;return normalized.length()>1000?normalized.substring(0,1000):normalized;}
    private OffsetDateTime now(){return OffsetDateTime.now(clock);}
}
