package io.knowledge.platform.socialapi;

import io.knowledge.platform.common.PrivacyHasher;import io.knowledge.platform.security.PlatformPrincipal;import io.knowledge.platform.social.ExploreView;import io.knowledge.platform.social.FeedItemView;import io.knowledge.platform.social.FollowStateView;import io.knowledge.platform.social.GardenView;import io.knowledge.platform.social.PublicContentView;import io.knowledge.platform.social.PublicProfileView;import io.knowledge.platform.social.PublicReaderView;import io.knowledge.platform.social.ReportView;import io.knowledge.platform.social.SocialPageView;import io.knowledge.platform.social.SocialService;import jakarta.servlet.http.HttpServletRequest;import java.util.List;import org.springframework.http.MediaType;import org.springframework.http.ResponseEntity;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.GetMapping;import org.springframework.web.bind.annotation.PathVariable;import org.springframework.web.bind.annotation.PostMapping;import org.springframework.web.bind.annotation.RequestBody;import org.springframework.web.bind.annotation.RestController;

@RestController
final class SocialController {
    private final SocialService service;private final PrivacyHasher privacyHasher;SocialController(SocialService service,PrivacyHasher privacyHasher){this.service=service;this.privacyHasher=privacyHasher;}
    @PostMapping("/api/v1/social/profile/save") PublicProfileView saveProfile(@RequestBody SocialRequests.ProfileSave r,@AuthenticationPrincipal PlatformPrincipal p){return service.saveProfile(p.userId(),r.slug(),r.displayName(),r.bio(),r.avatarUrl(),r.coverUrl(),r.theme(),r.navigation(),r.seoTitle(),r.seoDescription(),r.discoverable(),r.rssEnabled());}
    @PostMapping("/api/v1/social/profile/me") PublicProfileView myProfile(@AuthenticationPrincipal PlatformPrincipal p){return service.myProfile(p.userId());}
    @PostMapping("/api/public/v1/social/profile") PublicProfileView profile(@RequestBody SocialRequests.Slug r,@AuthenticationPrincipal PlatformPrincipal p){return service.profile(user(p),r.slug());}
    @PostMapping("/api/public/v1/social/profile/content") List<PublicContentView> profileContent(@RequestBody SocialRequests.Slug r,@AuthenticationPrincipal PlatformPrincipal p){return service.profileContent(user(p),r.slug(),limit(r.limit()));}
    @PostMapping("/api/public/v1/social/profile/content/page") SocialPageView<PublicContentView> profileContentPage(@RequestBody SocialRequests.Slug r,@AuthenticationPrincipal PlatformPrincipal p){return service.profileContentPage(user(p),r.slug(),offset(r.offset()),limit(r.limit()));}
    @PostMapping("/api/v1/social/gardens/create") GardenView createGarden(@RequestBody SocialRequests.GardenSave r,@AuthenticationPrincipal PlatformPrincipal p){return service.createGarden(p.userId(),r.slug(),r.title(),r.description(),r.icon(),r.coverUrl(),r.theme(),r.navigation(),r.seoTitle(),r.seoDescription(),r.discoverable(),r.rssEnabled(),r.knowledgeBaseIds());}
    @PostMapping("/api/v1/social/gardens/update") GardenView updateGarden(@RequestBody SocialRequests.GardenSave r,@AuthenticationPrincipal PlatformPrincipal p){return service.updateGarden(p.userId(),r.gardenId(),r.slug(),r.title(),r.description(),r.icon(),r.coverUrl(),r.theme(),r.navigation(),r.seoTitle(),r.seoDescription(),r.discoverable(),r.rssEnabled(),r.knowledgeBaseIds());}
    @PostMapping("/api/v1/social/gardens/delete") ResponseEntity<Void> deleteGarden(@RequestBody SocialRequests.Garden r,@AuthenticationPrincipal PlatformPrincipal p){service.deleteGarden(p.userId(),r.gardenId());return ResponseEntity.noContent().build();}
    @PostMapping("/api/v1/social/gardens/mine") List<GardenView> myGardens(@AuthenticationPrincipal PlatformPrincipal p){return service.myGardens(p.userId());}
    @PostMapping("/api/public/v1/social/garden") GardenView garden(@RequestBody SocialRequests.Slug r,@AuthenticationPrincipal PlatformPrincipal p){return service.publicGarden(user(p),r.slug());}
    @PostMapping("/api/public/v1/social/garden/content") List<PublicContentView> gardenContent(@RequestBody SocialRequests.Slug r,@AuthenticationPrincipal PlatformPrincipal p){return service.gardenContent(user(p),r.slug(),limit(r.limit()));}
    @PostMapping("/api/public/v1/social/garden/content/page") SocialPageView<PublicContentView> gardenContentPage(@RequestBody SocialRequests.Slug r,@AuthenticationPrincipal PlatformPrincipal p){return service.gardenContentPage(user(p),r.slug(),r.knowledgeBaseId(),offset(r.offset()),limit(r.limit()));}
    @PostMapping("/api/v1/social/follow") boolean follow(@RequestBody SocialRequests.Follow r,@AuthenticationPrincipal PlatformPrincipal p){return service.follow(p.userId(),r.targetType(),r.targetId(),!Boolean.FALSE.equals(r.notificationsEnabled()));}
    @PostMapping("/api/v1/social/unfollow") boolean unfollow(@RequestBody SocialRequests.Follow r,@AuthenticationPrincipal PlatformPrincipal p){return service.unfollow(p.userId(),r.targetType(),r.targetId());}
    @PostMapping("/api/v1/social/follow/status") FollowStateView followState(@RequestBody SocialRequests.Follow r,@AuthenticationPrincipal PlatformPrincipal p){return service.followState(p.userId(),r.targetType(),r.targetId());}
    @PostMapping("/api/v1/social/reactions/toggle") PublicContentView react(@RequestBody SocialRequests.Reaction r,@AuthenticationPrincipal PlatformPrincipal p){return service.react(p.userId(),r.publicationId(),r.reactionType());}
    @PostMapping("/api/v1/social/feed") List<FeedItemView> feed(@RequestBody SocialRequests.Page r,@AuthenticationPrincipal PlatformPrincipal p){return service.feed(p.userId(),limit(r.limit()));}
    @PostMapping("/api/v1/social/feed/page") SocialPageView<FeedItemView> feedPage(@RequestBody SocialRequests.Page r,@AuthenticationPrincipal PlatformPrincipal p){return service.feedPage(p.userId(),offset(r.offset()),limit(r.limit()));}
    @PostMapping("/api/public/v1/social/explore") ExploreView explore(@RequestBody SocialRequests.Page r,@AuthenticationPrincipal PlatformPrincipal p){return service.explore(user(p),limit(r.limit()));}
    @PostMapping("/api/public/v1/social/publication") PublicReaderView publication(@RequestBody SocialRequests.Publication r,@AuthenticationPrincipal PlatformPrincipal p,HttpServletRequest request){return service.reader(user(p),r.publicationId(),privacyHasher.hash("content.analytics.ip",request.getRemoteAddr()));}
    @PostMapping("/api/v1/social/block") void block(@RequestBody SocialRequests.Block r,@AuthenticationPrincipal PlatformPrincipal p){service.block(p.userId(),r.userId());}
    @PostMapping("/api/v1/social/unblock") void unblock(@RequestBody SocialRequests.Block r,@AuthenticationPrincipal PlatformPrincipal p){service.unblock(p.userId(),r.userId());}
    @PostMapping("/api/v1/social/reports/create") ReportView report(@RequestBody SocialRequests.Report r,@AuthenticationPrincipal PlatformPrincipal p){return service.report(p.userId(),r.targetType(),r.targetId(),r.reason(),r.details());}
    @PostMapping("/api/v1/admin/social/reports/list") List<ReportView> reports(@RequestBody SocialRequests.Reports r){return service.reports(r.status(),limit(r.limit()));}
    @PostMapping("/api/v1/admin/social/reports/page") SocialPageView<ReportView> reportsPage(@RequestBody SocialRequests.Reports r){return service.reportsPage(r.status(),offset(r.offset()),limit(r.limit()));}
    @PostMapping("/api/v1/admin/social/reports/review") void review(@RequestBody SocialRequests.Review r,@AuthenticationPrincipal PlatformPrincipal p){service.reviewReport(p.userId(),r.reportId(),r.status(),r.resolution());}
    @GetMapping(value="/api/public/v1/social/profiles/{slug}/sitemap.xml",produces=MediaType.APPLICATION_XML_VALUE) ResponseEntity<String> sitemap(@PathVariable String slug){return ResponseEntity.ok(service.profileSitemap(slug));}
    @GetMapping(value="/api/public/v1/social/profiles/{slug}/rss.xml",produces=MediaType.APPLICATION_XML_VALUE) ResponseEntity<String> rss(@PathVariable String slug){return ResponseEntity.ok(service.profileRss(slug));}
    private static java.util.UUID user(PlatformPrincipal value){return value==null?null:value.userId();}private static int limit(Integer value){return value==null?20:value;}private static int offset(Integer value){return value==null?0:value;}
}
