[versions]
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
spring-modulith = "2.1.0"
jooq = "3.21.0"
flyway = "12.0.1"
testcontainers = "2.0.5"
bouncycastle = "1.85.2"
poi = "5.4.1"
pdfbox = "3.0.5"
jsoup = "1.21.1"

[libraries]
spring-boot-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-mail = { module = "org.springframework.boot:spring-boot-starter-mail" }
spring-boot-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-security-crypto = { module = "org.springframework.security:spring-security-crypto" }
spring-context = { module = "org.springframework:spring-context" }
spring-tx = { module = "org.springframework:spring-tx" }
spring-web = { module = "org.springframework:spring-web" }
spring-jdbc = { module = "org.springframework:spring-jdbc" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core", version.ref = "spring-modulith" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test", version.ref = "spring-modulith" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgresql = { module = "org.postgresql:postgresql" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
bouncycastle-provider = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
apache-pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
