<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { FeedItem, SocialPage } from '../../../src/types'
import { messageOf, post } from '../../services/api'
const items=ref<FeedItem[]>([]);const loading=ref(true);const error=ref('');const offset=ref(0);const more=ref(false)
onMounted(load)
async function load(){loading.value=true;try{const page=await post<SocialPage<FeedItem>>('/api/v1/social/feed/page',{offset:offset.value,limit:25});items.value=offset.value?[...items.value,...page.items]:page.items;offset.value=page.nextOffset;more.value=page.hasMore}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function react(publicationId:string,type:string){await post('/api/v1/social/reactions/toggle',{publicationId,reactionType:type});await load()}
</script>
<template><div class="page-shell"><header class="page-heading"><div><h1>关注动态</h1><p>查看你关注的创作者、知识库和花园最近发布的内容。</p></div><v-btn to="/explore" prepend-icon="mdi-compass-outline" variant="outlined">发现更多</v-btn></header><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><div class="feed-column"><v-card v-for="entry in items" :key="entry.content.publicationId" class="section-card pa-6"><div class="d-flex align-center mb-4"><v-avatar color="primary" class="mr-3">{{entry.content.authorName.slice(0,1)}}</v-avatar><div><strong>{{entry.content.authorName}}</strong><p class="muted text-body-2 mb-0">{{entry.reason}} · {{new Date(entry.content.publishedAt).toLocaleString('zh-CN')}}</p></div></div><router-link :to="`/p/${entry.content.publicationId}`" class="text-decoration-none text-high-emphasis"><h2>{{entry.content.title}}</h2><p class="muted">{{entry.content.preview}}</p></router-link><div class="d-flex ga-2"><v-btn size="small" variant="tonal" prepend-icon="mdi-thumb-up-outline" @click="react(entry.content.publicationId,'LIKE')">{{entry.content.reactions.LIKE||0}}</v-btn><v-btn size="small" variant="tonal" prepend-icon="mdi-heart-outline" @click="react(entry.content.publicationId,'HEART')">{{entry.content.reactions.HEART||0}}</v-btn></div></v-card></div><div v-if="!items.length&&!loading" class="empty-state"><div><v-icon size="48">mdi-rss-off</v-icon><h3>关注流还是空的</h3><p>去发现页关注创作者或知识库。</p></div></div><v-btn v-if="more" block variant="outlined" class="mt-4" :loading="loading" @click="load">加载更多</v-btn></div></template>
<style scoped>.feed-column{display:grid;gap:16px;max-width:820px}.feed-column h2{font-size:22px;margin-bottom:10px}</style>
