<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { KnowledgeBase, Page, Team, WorkspaceMember } from '../../../src/types'
import { messageOf, post } from '../../services/api'
import { useSessionStore } from '../../stores/session'
import { useUiStore } from '../../stores/ui'
import KnowledgeBaseSharesPanel from '../../components/knowledge-base-settings/KnowledgeBaseSharesPanel.vue'

interface Member {userId:string;email:string;displayName:string|null;role:'READER'|'EDITOR'|'MANAGER'}
interface MergePlan {fingerprint:string;pageCount:number;catalogNodeCount:number;pathConflicts:Array<unknown>;warnings:string[]}
const route=useRoute();const router=useRouter();const session=useSessionStore();const ui=useUiStore();const id=String(route.params.knowledgeBaseId)
const kb=ref<KnowledgeBase|null>(null);const pages=ref<Page[]>([]);const members=ref<Member[]>([]);const workspaceMembers=ref<WorkspaceMember[]>([]);const teams=ref<Team[]>([]);const allKbs=ref<KnowledgeBase[]>([]);const tab=ref('general');const loading=ref(false);const error=ref('');const candidate=ref('');const memberRole=ref<Member['role']>('READER');const targetOwner=ref('');const mergeTarget=ref('');const mergePlan=ref<MergePlan|null>(null);const confirmName=ref('')
const form=reactive({name:'',slug:'',description:'',icon:'',visibility:'PRIVATE',allowPublicIndex:false,publishMode:'MANUAL',homepagePageId:'',appearanceConfig:'{}',watermarkConfig:'{}',catalogConfig:'{}'})
const workspace=computed(()=>session.workspaces.find(item=>item.id===kb.value?.workspaceId))
onMounted(load)
async function load(){loading.value=true;error.value='';try{kb.value=await post('/api/v1/knowledge-bases/get',{knowledgeBaseId:id});[pages.value,members.value,workspaceMembers.value,teams.value,allKbs.value]=await Promise.all([post('/api/v1/pages/list',{knowledgeBaseId:id}),post('/api/v1/knowledge-bases/members',{knowledgeBaseId:id}),post('/api/v1/workspaces/members',{workspaceId:kb.value.workspaceId}),post('/api/v1/teams/list',{workspaceId:kb.value.workspaceId}),post('/api/v1/knowledge-bases/list',{workspaceId:kb.value.workspaceId})]);Object.assign(form,{name:kb.value.name,slug:kb.value.slug,description:kb.value.description??'',icon:kb.value.icon??'',visibility:kb.value.visibility,allowPublicIndex:kb.value.allowPublicIndex,publishMode:kb.value.publishMode,homepagePageId:kb.value.homepagePageId??'',appearanceConfig:kb.value.appearanceConfig||'{}',watermarkConfig:kb.value.watermarkConfig||'{}',catalogConfig:kb.value.catalogConfig||'{}'});targetOwner.value=`${kb.value.ownerType}:${kb.value.ownerId}`}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function save(){if(!kb.value)return;loading.value=true;try{kb.value=await post('/api/v1/knowledge-bases/update',{knowledgeBaseId:id,...form,description:form.description||null,icon:form.icon||null,homepagePageId:form.homepagePageId||null});await session.loadNavigation();ui.notify('知识库设置已保存')}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function addMember(){await post('/api/v1/knowledge-bases/members/upsert',{knowledgeBaseId:id,userId:candidate.value,role:memberRole.value});candidate.value='';await load()}
async function removeMember(userId:string){await post('/api/v1/knowledge-bases/members/remove',{knowledgeBaseId:id,userId,role:null});await load()}
async function transfer(){const [ownerType,ownerId]=targetOwner.value.split(':');await post('/api/v1/knowledge-bases/transfer',{knowledgeBaseId:id,ownerType,ownerId});await load();ui.notify('归属已转移')}
async function planMerge(){mergePlan.value=await post('/api/v1/knowledge-bases/merge/plan',{sourceKnowledgeBaseId:id,targetKnowledgeBaseId:mergeTarget.value})}
async function executeMerge(){if(!mergePlan.value||confirmName.value!==kb.value?.name)return;await post('/api/v1/knowledge-bases/merge/execute',{sourceKnowledgeBaseId:id,targetKnowledgeBaseId:mergeTarget.value,planFingerprint:mergePlan.value.fingerprint,idempotencyKey:crypto.randomUUID()});await session.loadNavigation();await router.replace(`/app/kb/${mergeTarget.value}`)}
async function archive(){if(confirmName.value!==kb.value?.name)return;await post('/api/v1/knowledge-bases/archive',{knowledgeBaseId:id});await session.loadNavigation();await router.replace(`/app/w/${kb.value?.workspaceId}`)}
</script>
<template><div class="page-shell"><header class="page-heading"><div><v-btn :to="`/app/kb/${id}`" variant="text" prepend-icon="mdi-arrow-left" class="mb-2">返回知识库</v-btn><h1>{{kb?.name}} · 设置</h1><p>管理基础信息、外观、成员、分享访问、归属和生命周期。</p></div></header><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-tabs v-model="tab" color="primary" class="mb-5"><v-tab value="general">基础</v-tab><v-tab value="appearance">外观</v-tab><v-tab value="members">成员</v-tab><v-tab value="sharing">分享与访问</v-tab><v-tab value="ownership">归属</v-tab><v-tab value="danger">高级</v-tab></v-tabs>
<v-card v-if="tab==='general'" class="section-card pa-6"><div class="surface-grid"><v-text-field v-model="form.name" label="名称"/><v-text-field v-model="form.slug" label="路径"/><v-text-field v-model="form.icon" label="图标"/><v-select v-model="form.visibility" label="可见性" :items="['PRIVATE','WORKSPACE','PUBLIC']"/><v-select v-model="form.publishMode" label="发布模式" :items="['MANUAL','AUTO']"/><v-select v-model="form.homepagePageId" label="首页" :items="pages" item-title="title" item-value="id" clearable/></div><v-textarea v-model="form.description" label="知识库介绍" class="mt-4"/><v-switch v-model="form.allowPublicIndex" color="primary" inset label="允许公开搜索收录" :disabled="form.visibility!=='PUBLIC'" hint="仅在知识库公开时生效；关闭后公开地址仍可访问，但应输出 noindex。" persistent-hint class="mb-5"/><v-btn color="primary" :loading="loading" :disabled="!form.name.trim()||!form.slug.trim()" @click="save">保存基础信息</v-btn></v-card>
<v-card v-else-if="tab==='appearance'" class="section-card pa-6"><v-alert type="info" variant="tonal" class="mb-5">外观、水印和目录策略使用 JSON 配置保存，发布阅读器会同步应用。</v-alert><v-textarea v-model="form.appearanceConfig" label="外观配置 JSON" rows="6" class="mb-4"/><v-textarea v-model="form.watermarkConfig" label="水印配置 JSON" rows="5" class="mb-4"/><v-textarea v-model="form.catalogConfig" label="目录配置 JSON" rows="5" class="mb-4"/><v-btn color="primary" :loading="loading" @click="save">保存外观设置</v-btn></v-card>
<v-card v-else-if="tab==='members'" class="section-card"><div class="d-flex ga-3 pa-5"><v-select v-model="candidate" :items="workspaceMembers.filter(person=>!members.some(m=>m.userId===person.userId))" item-title="email" item-value="userId" label="空间成员"/><v-select v-model="memberRole" :items="['READER','EDITOR','MANAGER']" label="角色" max-width="170"/><v-btn color="primary" :disabled="!candidate" @click="addMember">添加</v-btn></div><v-divider/><v-list lines="two" class="pa-3"><v-list-item v-for="member in members" :key="member.userId" prepend-icon="mdi-account-circle-outline" :title="member.displayName||member.email" :subtitle="member.email"><template #append><v-chip>{{member.role}}</v-chip><v-btn icon="mdi-account-remove-outline" variant="text" color="error" @click="removeMember(member.userId)"/></template></v-list-item></v-list></v-card>
<KnowledgeBaseSharesPanel v-else-if="tab==='sharing'&&kb" :knowledge-base="kb"/>
<v-card v-else-if="tab==='ownership'" class="section-card pa-6"><h3 class="mb-2">知识库归属</h3><p class="muted mb-5">当前归属：{{kb?.ownerType}}。转移不会改变内容和链接。</p><v-select v-model="targetOwner" :items="[{title:workspace?.name||'工作区',value:`WORKSPACE:${kb?.workspaceId}`},...teams.map(team=>({title:`团队 · ${team.name}`,value:`TEAM:${team.id}`}))]" label="目标归属"/><v-btn color="primary" class="mt-4" @click="transfer">确认转移</v-btn></v-card>
<v-card v-else class="section-card pa-6"><h3>合并到其他知识库</h3><p class="muted">先预检页面、目录和路径冲突，再执行不可逆合并。</p><div class="d-flex ga-3 mt-4"><v-select v-model="mergeTarget" :items="allKbs.filter(item=>item.id!==id)" item-title="name" item-value="id" label="目标知识库"/><v-btn variant="outlined" :disabled="!mergeTarget" @click="planMerge">预检</v-btn></div><v-alert v-if="mergePlan" type="warning" variant="tonal" class="my-4">将移动 {{mergePlan.pageCount}} 篇内容和 {{mergePlan.catalogNodeCount}} 个目录项；检测到 {{mergePlan.pathConflicts.length}} 个路径冲突。</v-alert><v-divider class="my-6"/><h3 class="text-error">危险操作</h3><v-text-field v-model="confirmName" :label="`输入 ${kb?.name} 确认`" class="mt-4"/><div class="d-flex ga-3"><v-btn v-if="mergePlan" color="error" :disabled="confirmName!==kb?.name" @click="executeMerge">执行合并</v-btn><v-btn color="error" variant="outlined" :disabled="confirmName!==kb?.name" @click="archive">归档知识库</v-btn></div></v-card></div></template>
