<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { Garden, KnowledgeBase, PublicProfile } from '../../../src/types'
import { messageOf, post } from '../../services/api'
import { useSessionStore } from '../../stores/session'
import { useUiStore } from '../../stores/ui'
import { displayOptions, themeLabel } from '../../utils/displayLabels'
const session=useSessionStore();const ui=useUiStore();const profile=ref<PublicProfile|null>(null);const gardens=ref<Garden[]>([]);const publicKbs=ref<KnowledgeBase[]>([]);const loading=ref(false);const error=ref('');const tab=ref('profile');const dialog=ref(false)
const form=reactive({slug:'',displayName:'',bio:'',avatarUrl:'',coverUrl:'',theme:'MINIMAL',navigation:[] as Array<{label:string;url:string}>,seoTitle:'',seoDescription:'',discoverable:true,rssEnabled:true})
const garden=reactive({id:'',slug:'',title:'',description:'',icon:'🌿',coverUrl:'',theme:'MINIMAL',navigation:[] as Array<{label:string;url:string}>,seoTitle:'',seoDescription:'',discoverable:true,rssEnabled:true,knowledgeBaseIds:[] as string[]})
const themeOptions=displayOptions(['PAPER','MINIMAL','MAGAZINE','DARK'] as const,themeLabel)
onMounted(load)
async function load(){loading.value=true;try{[profile.value,gardens.value]=await Promise.all([post('/api/v1/social/profile/me',{}),post('/api/v1/social/gardens/mine',{})]);publicKbs.value=session.knowledgeBases.filter(kb=>kb.visibility==='PUBLIC');if(profile.value)Object.assign(form,{...profile.value,bio:profile.value.bio??'',avatarUrl:profile.value.avatarUrl??'',coverUrl:profile.value.coverUrl??'',seoTitle:profile.value.seoTitle??'',seoDescription:profile.value.seoDescription??''})}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function saveProfile(){loading.value=true;try{profile.value=await post('/api/v1/social/profile/save',{...form,bio:form.bio||null,avatarUrl:form.avatarUrl||null,coverUrl:form.coverUrl||null,seoTitle:form.seoTitle||null,seoDescription:form.seoDescription||null});ui.notify('公开主页已保存')}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
function editGarden(value?:Garden){Object.assign(garden,{id:value?.id??'',slug:value?.slug??'',title:value?.title??'',description:value?.description??'',icon:value?.icon??'🌿',coverUrl:value?.coverUrl??'',theme:value?.theme??'MINIMAL',navigation:value?.navigation??[],seoTitle:value?.seoTitle??'',seoDescription:value?.seoDescription??'',discoverable:value?.discoverable??true,rssEnabled:value?.rssEnabled??true,knowledgeBaseIds:value?.knowledgeBases.map(kb=>kb.id)??[]});dialog.value=true}
async function saveGarden(){await post(garden.id?'/api/v1/social/gardens/update':'/api/v1/social/gardens/create',{...garden,gardenId:garden.id||undefined,description:garden.description||null,coverUrl:garden.coverUrl||null,seoTitle:garden.seoTitle||null,seoDescription:garden.seoDescription||null});dialog.value=false;await load()}
async function removeGarden(value:Garden){if(confirm(`删除花园「${value.title}」？`)){await post('/api/v1/social/gardens/delete',{gardenId:value.id});await load()}}
</script>
<template><div class="page-shell"><header class="page-heading"><div><h1>公开主页</h1><p>管理个人身份、公开内容入口和主题花园。</p></div><v-btn v-if="profile" :to="`/u/${profile.slug}`" target="_blank" prepend-icon="mdi-open-in-new" variant="outlined">查看主页</v-btn></header><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-tabs v-model="tab" color="primary" class="mb-5"><v-tab value="profile">主页资料</v-tab><v-tab value="gardens">知识花园</v-tab></v-tabs><v-card v-if="tab==='profile'" class="section-card pa-6"><div class="surface-grid"><v-text-field v-model="form.displayName" label="显示名称"/><v-text-field v-model="form.slug" label="主页路径" prefix="/u/"/><v-select v-model="form.theme" label="主题" :items="themeOptions"/><v-text-field v-model="form.avatarUrl" label="头像 URL"/><v-text-field v-model="form.coverUrl" label="封面 URL"/></div><v-textarea v-model="form.bio" label="个人简介" class="mt-4"/><div class="d-flex ga-5 my-4"><v-switch v-model="form.discoverable" label="允许被发现" color="primary"/><v-switch v-model="form.rssEnabled" label="启用 RSS" color="primary"/></div><v-text-field v-model="form.seoTitle" label="SEO 标题" class="mb-4"/><v-textarea v-model="form.seoDescription" label="SEO 描述"/><v-btn color="primary" :loading="loading" @click="saveProfile">保存主页</v-btn></v-card><template v-else><div class="d-flex justify-end mb-4"><v-btn color="primary" prepend-icon="mdi-plus" @click="editGarden()">创建花园</v-btn></div><div class="surface-grid"><v-card v-for="value in gardens" :key="value.id" class="section-card pa-5"><div class="d-flex"><span class="text-h4 mr-4">{{value.icon||'🌿'}}</span><div><h3>{{value.title}}</h3><p class="muted">/{{value.slug}} · {{value.knowledgeBases.length}} 个知识库</p></div><v-spacer/><v-btn icon="mdi-pencil-outline" variant="text" @click="editGarden(value)"/><v-btn icon="mdi-delete-outline" variant="text" color="error" @click="removeGarden(value)"/></div></v-card></div></template><v-dialog v-model="dialog"><v-card><v-card-title class="pa-6">{{garden.id?'编辑花园':'创建花园'}}</v-card-title><v-card-text class="px-6"><v-text-field v-model="garden.title" label="名称" class="mb-4"/><v-text-field v-model="garden.slug" label="路径" class="mb-4"/><v-textarea v-model="garden.description" label="介绍" class="mb-4"/><v-select v-model="garden.knowledgeBaseIds" :items="publicKbs" item-title="name" item-value="id" label="公开知识库" multiple chips/><v-select v-model="garden.theme" :items="themeOptions" label="主题" class="mt-4"/></v-card-text><v-card-actions class="pa-6"><v-spacer/><v-btn @click="dialog=false">取消</v-btn><v-btn color="primary" :disabled="!garden.title||!garden.slug" @click="saveGarden">保存</v-btn></v-card-actions></v-card></v-dialog></div></template>
