<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { KnowledgeBase, Team, WorkspaceMember } from '../../../src/types'
import { messageOf, post } from '../../services/api'
import { useSessionStore } from '../../stores/session'
import { displayOptions, roleLabel, visibilityLabel } from '../../utils/displayLabels'

interface TeamMember extends WorkspaceMember { teamId:string; role:'MANAGER'|'MEMBER'; joinedAt:string }
interface AuditPage {items:Array<{id:string;action:string;actorEmail:string;createdAt:string}>;nextOffset:number;hasMore:boolean}
const route=useRoute();const router=useRouter();const session=useSessionStore();const workspaceId=String(route.params.workspaceId);const teamId=String(route.params.teamId)
const team=ref<Team|null>(null);const members=ref<TeamMember[]>([]);const workspaceMembers=ref<WorkspaceMember[]>([]);const kbs=ref<KnowledgeBase[]>([]);const activity=ref<AuditPage['items']>([]);const tab=ref('knowledge');const error=ref('');const loading=ref(false);const candidate=ref('')
const form=reactive({name:'',slug:'',description:'',avatar:'',visibility:'WORKSPACE'})
const teamRoleOptions=displayOptions(['MANAGER','MEMBER'] as const,roleLabel);const teamVisibilityOptions=displayOptions(['WORKSPACE','PRIVATE'] as const,visibilityLabel)
const me=computed(()=>members.value.find(item=>item.userId===session.user?.userId));const canManage=computed(()=>me.value?.role==='MANAGER'||['OWNER','ADMIN'].includes(session.workspaces.find(item=>item.id===workspaceId)?.membershipRole??''))
onMounted(load)
async function load(){loading.value=true;try{const [teams,memberValues,kbValues,workspaceMemberValues]=await Promise.all([post<Team[]>('/api/v1/teams/list',{workspaceId}),post<TeamMember[]>('/api/v1/teams/members',{teamId}),post<KnowledgeBase[]>('/api/v1/knowledge-bases/list',{workspaceId}),post<WorkspaceMember[]>('/api/v1/workspaces/members',{workspaceId})]);team.value=teams.find(item=>item.id===teamId)??null;members.value=memberValues;kbs.value=kbValues.filter(item=>item.teamId===teamId||item.ownerId===teamId);workspaceMembers.value=workspaceMemberValues;if(team.value)Object.assign(form,{name:team.value.name,slug:team.value.slug,description:team.value.description??'',avatar:team.value.avatar??'',visibility:team.value.visibility})}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function addMember(){if(!candidate.value)return;await post('/api/v1/teams/members/add',{teamId,userId:candidate.value,role:'MEMBER'});candidate.value='';await load()}
async function updateMember(member:TeamMember,role:string){await post('/api/v1/teams/members/update',{teamId,userId:member.userId,role});await load()}
async function removeMember(member:TeamMember){if(!confirm(`移除 ${member.email}？`))return;await post('/api/v1/teams/members/remove',{teamId,userId:member.userId,role:member.role});await load()}
async function save(){team.value=await post('/api/v1/teams/update',{teamId,...form,avatar:form.avatar||null});await load()}
async function loadActivity(){activity.value=(await post<AuditPage>('/api/v1/teams/activity/page',{teamId,limit:50,offset:0})).items}
async function leave(){await post('/api/v1/teams/members/leave',{teamId});await router.replace(`/app/w/${workspaceId}`)}
</script>
<template><div class="page-shell"><header class="page-heading"><div class="d-flex align-center"><v-avatar color="secondary" size="52" class="mr-4">{{team?.name.slice(0,1)}}</v-avatar><div><h1>{{team?.name||'团队'}}</h1><p>{{team?.description||'团队知识和成员协作。'}}</p></div></div><v-btn variant="outlined" prepend-icon="mdi-exit-to-app" @click="leave">退出团队</v-btn></header><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-tabs v-model="tab" color="primary" class="mb-5" @update:model-value="value=>{if(value==='activity')loadActivity()}"><v-tab value="knowledge">知识库</v-tab><v-tab value="members">成员</v-tab><v-tab value="activity">动态</v-tab><v-tab v-if="canManage" value="settings">设置</v-tab></v-tabs>
<div v-if="tab==='knowledge'" class="surface-grid"><v-card v-for="kb in kbs" :key="kb.id" class="section-card clickable pa-5" @click="router.push(`/app/kb/${kb.id}`)"><h3>{{kb.icon||'📘'}} {{kb.name}}</h3><p class="muted mb-0">{{kb.description||'团队知识库'}}</p></v-card><div v-if="!kbs.length" class="empty-state"><div><v-icon size="44">mdi-book-open-blank-variant-outline</v-icon><h3>还没有团队知识库</h3></div></div></div>
<v-card v-else-if="tab==='members'" class="section-card"><div v-if="canManage" class="d-flex ga-3 pa-4"><v-select v-model="candidate" :items="workspaceMembers.filter(person=>!members.some(m=>m.userId===person.userId))" item-title="email" item-value="userId" label="添加空间成员"/><v-btn color="primary" :disabled="!candidate" @click="addMember">添加</v-btn></div><v-divider/><v-list lines="two" class="pa-3"><v-list-item v-for="member in members" :key="member.userId" prepend-icon="mdi-account-circle-outline" :title="member.displayName||member.email" :subtitle="member.email"><template #append><v-select v-if="canManage" :model-value="member.role" :items="teamRoleOptions" density="compact" max-width="140" @update:model-value="updateMember(member,$event)"/><v-chip v-else size="small">{{roleLabel(member.role)}}</v-chip><v-btn v-if="canManage" icon="mdi-account-remove-outline" variant="text" color="error" @click="removeMember(member)"/></template></v-list-item></v-list></v-card>
<v-card v-else-if="tab==='activity'" class="section-card"><v-list lines="two"><v-list-item v-for="event in activity" :key="event.id" prepend-icon="mdi-history" :title="event.action" :subtitle="`${event.actorEmail} · ${new Date(event.createdAt).toLocaleString('zh-CN')}`"/></v-list></v-card>
<v-card v-else class="section-card pa-6"><v-text-field v-model="form.name" label="团队名称" class="mb-4"/><v-text-field v-model="form.slug" label="路径" class="mb-4"/><v-textarea v-model="form.description" label="介绍" class="mb-4"/><v-select v-model="form.visibility" :items="teamVisibilityOptions" label="可见性" class="mb-4"/><v-btn color="primary" :loading="loading" @click="save">保存设置</v-btn></v-card></div></template>
