<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { Page, Team, WorkspaceMember } from '../../../src/types'
import { messageOf, post } from '../../services/api'
import { useSessionStore } from '../../stores/session'
import { useUiStore } from '../../stores/ui'
import { displayOptions, publishModeLabel, resourceTypeLabel, roleLabel, visibilityLabel } from '../../utils/displayLabels'

interface Group {id:string;workspaceId:string;name:string;description:string|null;memberCount?:number}
interface Audit {id:string;action:string;resourceType:string;resourceId:string;actorEmail:string;createdAt:string;payload?:unknown}
interface AuditPage {items:Audit[];nextOffset:number;hasMore:boolean}
const route=useRoute();const router=useRouter();const session=useSessionStore();const ui=useUiStore();const id=String(route.params.workspaceId)
const workspace=computed(()=>session.workspaces.find(item=>item.id===id));const tab=ref(String(route.query.tab??'general'));const loading=ref(false);const error=ref('');const members=ref<WorkspaceMember[]>([]);const groups=ref<Group[]>([]);const teams=ref<Team[]>([]);const trash=ref<Page[]>([]);const audit=ref<Audit[]>([])
const form=reactive({name:'',defaultVisibility:'PRIVATE',defaultPublishMode:'MANUAL'});const dialog=ref<'group'|'team'|'transfer'|'delete'|null>(null);const draft=reactive({name:'',slug:'',description:'',visibility:'WORKSPACE',targetUserId:'',confirmation:''})
const visibilityOptions=displayOptions(['PRIVATE','WORKSPACE','PUBLIC'] as const,visibilityLabel);const publishModeOptions=displayOptions(['MANUAL','AUTO'] as const,publishModeLabel);const workspaceRoleOptions=displayOptions(['ADMIN','MEMBER','EXTERNAL'] as const,roleLabel)
const organization=computed(()=>workspace.value?.workspaceType==='ORGANIZATION');const canManage=computed(()=>['OWNER','ADMIN'].includes(workspace.value?.membershipRole??''))
onMounted(async()=>{if(workspace.value)Object.assign(form,{name:workspace.value.name,defaultVisibility:workspace.value.defaultVisibility,defaultPublishMode:workspace.value.defaultPublishMode});await loadTab()})
async function loadTab(){loading.value=true;error.value='';try{if(tab.value==='members')members.value=await post('/api/v1/workspaces/members',{workspaceId:id});if(tab.value==='groups')groups.value=await post('/api/v1/user-groups/list',{workspaceId:id});if(tab.value==='teams')teams.value=await post('/api/v1/teams/list',{workspaceId:id});if(tab.value==='trash')trash.value=await post('/api/v1/pages/trash/list',{workspaceId:id});if(tab.value==='audit')audit.value=(await post<AuditPage>('/api/v1/audit/page',{workspaceId:id,limit:50,offset:0})).items}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function saveGeneral(){await post('/api/v1/workspaces/update',{workspaceId:id,...form});await session.loadNavigation();ui.notify('工作区设置已保存')}
async function memberRole(member:WorkspaceMember,role:string){members.value=await post('/api/v1/workspaces/members/update',{workspaceId:id,userId:member.userId,role})}
async function removeMember(member:WorkspaceMember){if(!confirm(`移除 ${member.email}？`))return;await post('/api/v1/workspaces/members/remove',{workspaceId:id,userId:member.userId,role:null});await loadTab()}
async function createGroup(){await post('/api/v1/user-groups/create',{workspaceId:id,name:draft.name,description:draft.description||null});dialog.value=null;resetDraft();await loadTab()}
async function deleteGroup(group:Group){if(confirm(`删除用户组「${group.name}」？`)){await post('/api/v1/user-groups/delete',{groupId:group.id});await loadTab()}}
async function createTeam(){await post('/api/v1/teams/create',{workspaceId:id,name:draft.name,slug:draft.slug,description:draft.description,avatar:null,visibility:draft.visibility});dialog.value=null;resetDraft();await loadTab()}
async function deleteTeam(team:Team){if(confirm(`删除团队「${team.name}」？`)){await post('/api/v1/teams/delete',{teamId:team.id});await loadTab()}}
async function restorePage(page:Page){await post('/api/v1/pages/restore',{pageId:page.id});await loadTab()}
async function transfer(){await post('/api/v1/workspaces/ownership/transfer',{workspaceId:id,targetUserId:draft.targetUserId,confirmationName:draft.confirmation});dialog.value=null;await session.loadNavigation();ui.notify('所有权已转移')}
async function removeWorkspace(){await post('/api/v1/workspaces/delete',{workspaceId:id,confirmationName:draft.confirmation});await session.loadNavigation();await router.replace('/app')}
function resetDraft(){Object.assign(draft,{name:'',slug:'',description:'',visibility:'WORKSPACE',targetUserId:'',confirmation:''})}
</script>
<template><div class="page-shell"><header class="page-heading"><div><v-btn :to="`/app/w/${id}`" variant="text" prepend-icon="mdi-arrow-left" class="mb-2">返回空间</v-btn><h1>{{workspace?.name}} · 设置</h1><p>统一管理空间策略、成员、组织和审计。</p></div></header><v-alert v-if="!canManage" type="warning" variant="tonal" class="mb-4">你可以查看部分设置，但只有空间所有者或管理员可以修改。</v-alert><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-tabs v-model="tab" color="primary" class="mb-5" @update:model-value="loadTab"><v-tab value="general">基本信息</v-tab><v-tab v-if="organization" value="members">成员</v-tab><v-tab v-if="organization" value="groups">用户组</v-tab><v-tab v-if="organization" value="teams">团队</v-tab><v-tab value="trash">回收站</v-tab><v-tab value="audit">审计日志</v-tab></v-tabs><v-progress-linear v-if="loading" indeterminate color="primary"/>
<v-card v-if="tab==='general'" class="section-card pa-6"><v-text-field v-model="form.name" label="空间名称" class="mb-4"/><div class="surface-grid"><v-select v-model="form.defaultVisibility" label="默认可见性" :items="visibilityOptions"/><v-select v-model="form.defaultPublishMode" label="默认发布方式" :items="publishModeOptions"/></div><v-btn color="primary" class="mt-5" :disabled="!canManage" @click="saveGeneral">保存设置</v-btn><template v-if="organization&&workspace?.membershipRole==='OWNER'"><v-divider class="my-7"/><h3>所有权与删除</h3><p class="muted">高影响操作会再次要求输入空间名称。</p><div class="d-flex ga-3 mt-4"><v-btn variant="outlined" @click="dialog='transfer'">转移所有权</v-btn><v-btn color="error" variant="outlined" @click="dialog='delete'">删除空间</v-btn></div></template></v-card>
<v-card v-else-if="tab==='members'" class="section-card"><v-list lines="two" class="pa-3"><v-list-item v-for="member in members" :key="member.userId" prepend-icon="mdi-account-circle-outline" :title="member.displayName||member.email" :subtitle="member.email"><template #append><v-chip v-if="member.role==='OWNER'" size="small">{{roleLabel(member.role)}}</v-chip><v-select v-else :model-value="member.role" :items="workspaceRoleOptions" density="compact" max-width="150" :disabled="!canManage" @update:model-value="memberRole(member,$event)"/><v-btn icon="mdi-account-remove-outline" variant="text" color="error" :disabled="!canManage||member.role==='OWNER'" @click="removeMember(member)"/></template></v-list-item></v-list></v-card>
<div v-else-if="tab==='groups'"><div class="d-flex justify-end mb-4"><v-btn color="primary" prepend-icon="mdi-plus" @click="dialog='group'">新建用户组</v-btn></div><div class="surface-grid"><v-card v-for="group in groups" :key="group.id" class="section-card pa-5"><div class="d-flex"><v-avatar color="primary" variant="tonal" class="mr-4"><v-icon>mdi-account-multiple-outline</v-icon></v-avatar><div><h3>{{group.name}}</h3><p class="muted mb-0">{{group.description||`${group.memberCount??0} 名成员`}}</p></div><v-spacer/><v-btn icon="mdi-delete-outline" variant="text" color="error" @click="deleteGroup(group)"/></div></v-card></div></div>
<div v-else-if="tab==='teams'"><div class="d-flex justify-end mb-4"><v-btn color="primary" prepend-icon="mdi-plus" @click="dialog='team'">新建团队</v-btn></div><div class="surface-grid"><v-card v-for="team in teams" :key="team.id" class="section-card pa-5"><div class="d-flex align-center"><v-avatar color="secondary" class="mr-4">{{team.name.slice(0,1)}}</v-avatar><div><h3>{{team.name}}</h3><p class="muted mb-0">{{visibilityLabel(team.visibility)}}</p></div><v-spacer/><v-btn :to="`/app/w/${id}/teams/${team.id}`" icon="mdi-open-in-new" variant="text"/><v-btn icon="mdi-delete-outline" variant="text" color="error" @click="deleteTeam(team)"/></div></v-card></div></div>
<v-card v-else-if="tab==='trash'" class="section-card"><v-list lines="two" class="pa-3"><v-list-item v-for="page in trash" :key="page.id" prepend-icon="mdi-file-remove-outline" :title="page.title" :subtitle="new Date(page.updatedAt).toLocaleString('zh-CN')"><template #append><v-btn variant="tonal" prepend-icon="mdi-restore" @click="restorePage(page)">恢复</v-btn></template></v-list-item></v-list><div v-if="!trash.length&&!loading" class="empty-state"><div><v-icon size="44">mdi-trash-can-outline</v-icon><h3>回收站为空</h3></div></div></v-card>
<v-card v-else class="section-card"><v-list lines="two"><v-list-item v-for="event in audit" :key="event.id" prepend-icon="mdi-shield-search-outline" :title="event.action" :subtitle="`${event.actorEmail} · ${resourceTypeLabel(event.resourceType)} · ${new Date(event.createdAt).toLocaleString('zh-CN')}`"/></v-list></v-card>
<v-dialog :model-value="Boolean(dialog)" @update:model-value="value=>{if(!value){dialog=null;resetDraft()}}"><v-card><v-card-title class="pa-6">{{dialog==='group'?'新建用户组':dialog==='team'?'新建团队':dialog==='transfer'?'转移空间所有权':'删除工作区'}}</v-card-title><v-card-text class="px-6"><template v-if="dialog==='group'||dialog==='team'"><v-text-field v-model="draft.name" label="名称" class="mb-4"/><v-text-field v-if="dialog==='team'" v-model="draft.slug" label="路径" class="mb-4"/><v-textarea v-model="draft.description" label="说明"/></template><template v-else><v-select v-if="dialog==='transfer'" v-model="draft.targetUserId" :items="members.filter(m=>m.role!=='OWNER')" item-title="email" item-value="userId" label="新所有者"/><v-text-field v-model="draft.confirmation" :label="`输入 ${workspace?.name} 确认`" class="mt-4"/></template></v-card-text><v-card-actions class="pa-6"><v-spacer/><v-btn @click="dialog=null">取消</v-btn><v-btn :color="dialog==='delete'?'error':'primary'" :disabled="dialog==='delete'&&draft.confirmation!==workspace?.name" @click="dialog==='group'?createGroup():dialog==='team'?createTeam():dialog==='transfer'?transfer():removeWorkspace()">确认</v-btn></v-card-actions></v-card></v-dialog></div></template>
