<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { KnowledgeBase, Team } from '../../../src/types'
import { messageOf, post } from '../../services/api'
import { useSessionStore } from '../../stores/session'
import { useUiStore } from '../../stores/ui'

const route=useRoute();const router=useRouter();const session=useSessionStore();const ui=useUiStore();const id=computed(()=>String(route.params.workspaceId))
const teams=ref<Team[]>([]);const knowledgeBases=ref<KnowledgeBase[]>([]);const tab=ref('knowledge');const dialog=ref(false);const loading=ref(false);const error=ref('')
const form=reactive({name:'',slug:'',visibility:'WORKSPACE'})
const workspace=computed(()=>session.workspaces.find(item=>item.id===id.value));const canManage=computed(()=>['OWNER','ADMIN'].includes(workspace.value?.membershipRole??''))
onMounted(load);watch(id,load);watch(()=>form.name,value=>form.slug=value.toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'').slice(0,80))
async function load(){loading.value=true;try{[teams.value,knowledgeBases.value]=await Promise.all([workspace.value?.workspaceType==='ORGANIZATION'?post('/api/v1/teams/list',{workspaceId:id.value}):Promise.resolve([]),post('/api/v1/knowledge-bases/list',{workspaceId:id.value})]);session.selectWorkspace(id.value)}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
async function createTeam(){loading.value=true;try{await post('/api/v1/teams/create',{workspaceId:id.value,name:form.name,slug:form.slug,description:'',avatar:null,visibility:form.visibility});dialog.value=false;form.name='';await load()}catch(value){error.value=messageOf(value)}finally{loading.value=false}}
</script>
<template><div class="page-shell"><header class="page-heading"><div><h1>{{workspace?.name||'工作区'}}</h1><p>{{workspace?.workspaceType==='PERSONAL'?'你的个人知识与内容空间。':'管理团队、知识库和成员协作。'}}</p></div><div class="d-flex ga-2"><v-btn v-if="canManage" :to="`/app/w/${id}/settings`" prepend-icon="mdi-cog-outline" variant="outlined">空间设置</v-btn><v-btn color="primary" prepend-icon="mdi-plus" @click="ui.createOpen=true">新建知识库</v-btn></div></header>
<v-tabs v-if="workspace?.workspaceType==='ORGANIZATION'" v-model="tab" color="primary" class="mb-5"><v-tab value="knowledge">知识库</v-tab><v-tab value="teams">团队</v-tab></v-tabs><v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{error}}</v-alert><v-progress-linear v-if="loading" indeterminate color="primary"/>
<div v-if="tab==='knowledge'" class="surface-grid"><v-card v-for="kb in knowledgeBases" :key="kb.id" class="section-card clickable pa-5" @click="router.push(`/app/kb/${kb.id}`)"><div class="d-flex"><v-avatar color="primary" variant="tonal" rounded="lg" class="mr-4">{{kb.icon||'📘'}}</v-avatar><div><h3 class="mb-1">{{kb.name}}</h3><p class="muted text-body-2 mb-0">{{kb.description||`${kb.visibility} · ${kb.ownerType}`}}</p></div></div></v-card><v-card class="section-card clickable pa-5" @click="ui.createOpen=true"><div class="d-flex align-center"><v-avatar variant="tonal" rounded="lg" class="mr-4"><v-icon>mdi-plus</v-icon></v-avatar><strong>新建知识库</strong></div></v-card></div>
<div v-else class="surface-grid"><v-card v-for="team in teams" :key="team.id" class="section-card clickable pa-5" @click="router.push(`/app/w/${id}/teams/${team.id}`)"><div class="d-flex align-center"><v-avatar color="secondary" rounded="lg" class="mr-4">{{team.name.slice(0,1)}}</v-avatar><div><h3 class="mb-1">{{team.name}}</h3><p class="muted text-body-2 mb-0">{{team.description||team.visibility}}</p></div><v-spacer/><v-icon>mdi-chevron-right</v-icon></div></v-card><v-card v-if="canManage" class="section-card clickable pa-5" @click="dialog=true"><div class="d-flex align-center"><v-avatar variant="tonal" rounded="lg" class="mr-4"><v-icon>mdi-account-multiple-plus-outline</v-icon></v-avatar><strong>新建团队</strong></div></v-card></div>
<v-dialog v-model="dialog"><v-card><v-card-title class="pa-6">新建团队</v-card-title><v-card-text class="px-6"><v-text-field v-model="form.name" label="团队名称" class="mb-4"/><v-text-field v-model="form.slug" label="路径" prefix="/teams/" class="mb-4"/><v-select v-model="form.visibility" label="可见性" :items="[{title:'空间内可见',value:'WORKSPACE'},{title:'仅团队成员',value:'PRIVATE'}]"/></v-card-text><v-card-actions class="pa-6"><v-spacer/><v-btn @click="dialog=false">取消</v-btn><v-btn color="primary" :loading="loading" :disabled="!form.name||!form.slug" @click="createTeam">创建</v-btn></v-card-actions></v-card></v-dialog></div></template>
