package io.knowledge.platform.social;

import static org.jooq.impl.DSL.field;import static org.jooq.impl.DSL.name;import static org.jooq.impl.DSL.table;
import java.math.BigDecimal;import java.time.OffsetDateTime;import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.LinkedHashSet;import java.util.List;import java.util.Map;import java.util.Set;import java.util.UUID;import org.jooq.DSLContext;import org.jooq.JSONB;import org.jooq.Record;import org.jooq.Table;import org.springframework.stereotype.Repository;import tools.jackson.databind.JsonNode;import tools.jackson.databind.ObjectMapper;

@Repository
class SocialRepository {
    private static final Table<Record> PROFILES=table(name("public_profiles")),GARDENS=table(name("public_gardens")),GARDEN_KBS=table(name("garden_knowledge_bases")),FOLLOWS=table(name("social_follows")),REACTIONS=table(name("publication_reactions")),BLOCKS=table(name("social_blocks")),REPORTS=table(name("social_reports"));
    private final DSLContext dsl;private final ObjectMapper mapper;SocialRepository(DSLContext dsl,ObjectMapper mapper){this.dsl=dsl;this.mapper=mapper;}

    void upsertProfile(UUID user,String slug,String displayName,String bio,String avatar,String cover,String theme,JsonNode navigation,String seoTitle,String seoDescription,boolean discoverable,boolean rss,OffsetDateTime now){JSONB nav=jsonValue(navigation);dsl.insertInto(PROFILES).columns(uuid("user_id"),string("slug"),string("display_name"),string("bio"),string("avatar_url"),string("cover_url"),string("theme"),json("navigation"),string("seo_title"),string("seo_description"),bool("discoverable"),bool("rss_enabled"),time("created_at"),time("updated_at")).values(user,slug,displayName,bio,avatar,cover,theme,nav,seoTitle,seoDescription,discoverable,rss,now,now).onConflict(uuid("user_id")).doUpdate().set(string("slug"),slug).set(string("display_name"),displayName).set(string("bio"),bio).set(string("avatar_url"),avatar).set(string("cover_url"),cover).set(string("theme"),theme).set(json("navigation"),nav).set(string("seo_title"),seoTitle).set(string("seo_description"),seoDescription).set(bool("discoverable"),discoverable).set(bool("rss_enabled"),rss).set(time("updated_at"),now).execute();dsl.update(table(name("users"))).set(string("display_name"),displayName).set(time("updated_at"),now).where(uuid("id").eq(user)).execute();}
    ProfileRow profileBySlug(String slug){return profile("p.slug=?",slug);}ProfileRow profileByUser(UUID user){return profile("p.user_id=?::uuid",user);}
    List<ProfileRow> creatorProfiles(int limit){return dsl.fetch("select p.*,(select count(*) from social_follows f where f.target_type='USER' and f.target_id=p.user_id) follower_count,(select count(*) from social_follows f where f.follower_id=p.user_id) following_count from public_profiles p where p.discoverable order by follower_count desc,p.updated_at desc limit ?",limit).map(this::profileRow);}
    private ProfileRow profile(String condition,Object binding){Record r=dsl.fetchOne("select p.*,(select count(*) from social_follows f where f.target_type='USER' and f.target_id=p.user_id) follower_count,(select count(*) from social_follows f where f.follower_id=p.user_id) following_count from public_profiles p where "+condition,binding);return r==null?null:profileRow(r);}private ProfileRow profileRow(Record r){return new ProfileRow(r.get("user_id",UUID.class),r.get("slug",String.class),r.get("display_name",String.class),r.get("bio",String.class),r.get("avatar_url",String.class),r.get("cover_url",String.class),r.get("theme",String.class),read(r.get("navigation",JSONB.class)),r.get("seo_title",String.class),r.get("seo_description",String.class),Boolean.TRUE.equals(r.get("discoverable",Boolean.class)),Boolean.TRUE.equals(r.get("rss_enabled",Boolean.class)),value(r.get("follower_count",Number.class)),value(r.get("following_count",Number.class)),r.get("updated_at",OffsetDateTime.class));}

    void insertGarden(UUID id,UUID user,String slug,String title,String description,String icon,String cover,String theme,JsonNode navigation,String seoTitle,String seoDescription,boolean discoverable,boolean rss,OffsetDateTime now){dsl.insertInto(GARDENS).columns(uuid("id"),uuid("user_id"),string("slug"),string("title"),string("description"),string("icon"),string("cover_url"),string("theme"),json("navigation"),string("seo_title"),string("seo_description"),bool("discoverable"),bool("rss_enabled"),time("created_at"),time("updated_at")).values(id,user,slug,title,description,icon,cover,theme,jsonValue(navigation),seoTitle,seoDescription,discoverable,rss,now,now).execute();}
    void updateGarden(UUID id,String slug,String title,String description,String icon,String cover,String theme,JsonNode navigation,String seoTitle,String seoDescription,boolean discoverable,boolean rss,OffsetDateTime now){dsl.update(GARDENS).set(string("slug"),slug).set(string("title"),title).set(string("description"),description).set(string("icon"),icon).set(string("cover_url"),cover).set(string("theme"),theme).set(json("navigation"),jsonValue(navigation)).set(string("seo_title"),seoTitle).set(string("seo_description"),seoDescription).set(bool("discoverable"),discoverable).set(bool("rss_enabled"),rss).set(time("updated_at"),now).where(uuid("id").eq(id)).execute();}
    GardenRow gardenBySlug(String slug){return garden("g.slug=?",slug);}GardenRow gardenById(UUID id){return garden("g.id=?::uuid",id);}List<GardenRow> gardensByUser(UUID user){return gardens("g.user_id=?::uuid",new Object[]{user},false,50);}List<GardenRow> exploreGardens(int limit){return gardens("g.discoverable",new Object[]{},true,limit);}private GardenRow garden(String condition,Object binding){List<GardenRow> rows=gardens(condition,new Object[]{binding},false,1);return rows.isEmpty()?null:rows.get(0);}private List<GardenRow> gardens(String condition,Object[] bindings,boolean popularity,int limit){List<Object> args=new ArrayList<>(List.of(bindings));args.add(limit);return dsl.fetch("select g.*,p.slug owner_slug,p.display_name owner_name,(select count(*) from social_follows f where f.target_type='GARDEN' and f.target_id=g.id) follower_count from public_gardens g join public_profiles p on p.user_id=g.user_id where "+condition+" order by "+(popularity?"follower_count desc,":"")+"g.updated_at desc limit ?",args.toArray()).map(r->new GardenRow(r.get("id",UUID.class),r.get("user_id",UUID.class),r.get("owner_slug",String.class),r.get("owner_name",String.class),r.get("slug",String.class),r.get("title",String.class),r.get("description",String.class),r.get("icon",String.class),r.get("cover_url",String.class),r.get("theme",String.class),read(r.get("navigation",JSONB.class)),r.get("seo_title",String.class),r.get("seo_description",String.class),Boolean.TRUE.equals(r.get("discoverable",Boolean.class)),Boolean.TRUE.equals(r.get("rss_enabled",Boolean.class)),value(r.get("follower_count",Number.class)),r.get("updated_at",OffsetDateTime.class)));}
    List<GardenKnowledgeBaseView> gardenKnowledgeBases(UUID garden){return dsl.fetch("select kb.id,kb.name,kb.slug,kb.description,kb.icon from garden_knowledge_bases gk join knowledge_bases kb on kb.id=gk.knowledge_base_id where gk.garden_id=?::uuid and kb.archived_at is null order by gk.position",garden).map(r->new GardenKnowledgeBaseView(r.get("id",UUID.class),r.get("name",String.class),r.get("slug",String.class),r.get("description",String.class),r.get("icon",String.class)));}
    void replaceGardenKnowledgeBases(UUID garden,List<UUID> ids){dsl.deleteFrom(GARDEN_KBS).where(uuid("garden_id").eq(garden)).execute();for(int i=0;i<ids.size();i++)dsl.insertInto(GARDEN_KBS).columns(uuid("garden_id"),uuid("knowledge_base_id"),decimal("position")).values(garden,ids.get(i),BigDecimal.valueOf(i+1L)).execute();}
    boolean deleteGarden(UUID garden,UUID user){dsl.deleteFrom(FOLLOWS).where(string("target_type").eq("GARDEN").and(uuid("target_id").eq(garden))).execute();return dsl.deleteFrom(GARDENS).where(uuid("id").eq(garden).and(uuid("user_id").eq(user))).execute()==1;}
    boolean knowledgeBasePublic(UUID id){return Boolean.TRUE.equals(dsl.selectCount().from(table(name("knowledge_bases"))).where(uuid("id").eq(id).and(string("visibility").eq("PUBLIC")).and(time("archived_at").isNull())).fetchOne(0,Integer.class)>0);}

    boolean followed(UUID actor,String type,UUID target){return followState(actor,type,target).followed();}
    FollowStateView followState(UUID actor,String type,UUID target){if(actor==null)return new FollowStateView(false,false);Record row=dsl.select(bool("notifications_enabled")).from(FOLLOWS).where(uuid("follower_id").eq(actor).and(string("target_type").eq(type)).and(uuid("target_id").eq(target))).fetchOne();return row==null?new FollowStateView(false,false):new FollowStateView(true,Boolean.TRUE.equals(row.get(bool("notifications_enabled"))));}
    void follow(UUID actor,String type,UUID target,boolean notifications,OffsetDateTime now){dsl.insertInto(FOLLOWS).columns(uuid("follower_id"),string("target_type"),uuid("target_id"),bool("notifications_enabled"),time("created_at")).values(actor,type,target,notifications,now).onConflict(uuid("follower_id"),string("target_type"),uuid("target_id")).doUpdate().set(bool("notifications_enabled"),notifications).execute();}
    void unfollow(UUID actor,String type,UUID target){dsl.deleteFrom(FOLLOWS).where(uuid("follower_id").eq(actor).and(string("target_type").eq(type)).and(uuid("target_id").eq(target))).execute();}
    List<UUID> publicationNotificationRecipients(UUID author,UUID knowledgeBase){return dsl.fetch("select distinct f.follower_id from social_follows f where f.notifications_enabled and f.follower_id<>?::uuid and ((f.target_type='USER' and f.target_id=?::uuid) or (f.target_type='KNOWLEDGE_BASE' and f.target_id=?::uuid) or (f.target_type='GARDEN' and exists(select 1 from garden_knowledge_bases gk where gk.garden_id=f.target_id and gk.knowledge_base_id=?::uuid))) and not exists(select 1 from social_blocks b where (b.blocker_id=f.follower_id and b.blocked_id=?::uuid) or (b.blocker_id=?::uuid and b.blocked_id=f.follower_id)) order by f.follower_id",author,author,knowledgeBase,knowledgeBase,author,author).getValues("follower_id",UUID.class);}
    boolean userExists(UUID id){return dsl.fetchExists(dsl.selectOne().from(table(name("users"))).where(uuid("id").eq(id).and(string("status").eq("ACTIVE"))));}

    PublicationIdentity publication(UUID id){Record r=dsl.fetchOne("select pub.id,pub.workspace_id,pub.knowledge_base_id,pub.page_id,pub.published_by,case when p.visibility_override='INHERIT' then kb.visibility else p.visibility_override end visibility from page_publications pub join pages p on p.id=pub.page_id join knowledge_bases kb on kb.id=pub.knowledge_base_id where pub.id=?::uuid and pub.superseded_at is null and p.deleted_at is null",id);return r==null?null:new PublicationIdentity(r.get("id",UUID.class),r.get("workspace_id",UUID.class),r.get("knowledge_base_id",UUID.class),r.get("page_id",UUID.class),r.get("published_by",UUID.class),r.get("visibility",String.class));}
    boolean toggleReaction(UUID user,UUID publication,String type,OffsetDateTime now){int deleted=dsl.deleteFrom(REACTIONS).where(uuid("user_id").eq(user).and(uuid("publication_id").eq(publication)).and(string("reaction_type").eq(type))).execute();if(deleted>0)return false;dsl.insertInto(REACTIONS).columns(uuid("user_id"),uuid("publication_id"),string("reaction_type"),time("created_at")).values(user,publication,type,now).execute();return true;}
    Map<String,Long> reactionCounts(UUID publication){Map<String,Long> result=new LinkedHashMap<>();var count=org.jooq.impl.DSL.count();for(Record r:dsl.select(string("reaction_type"),count).from(REACTIONS).where(uuid("publication_id").eq(publication)).groupBy(string("reaction_type")).fetch())result.put(r.get(string("reaction_type")),r.get(count).longValue());return Map.copyOf(result);}Set<String> viewerReactions(UUID user,UUID publication){return user==null?Set.of():new LinkedHashSet<>(dsl.select(string("reaction_type")).from(REACTIONS).where(uuid("user_id").eq(user).and(uuid("publication_id").eq(publication))).fetch(string("reaction_type")));}

    List<ContentRow> profileContent(UUID user,int offset,int limit){return content("pub.published_by=?::uuid",new Object[]{user},false,offset,limit);}
    List<ContentRow> gardenContent(UUID garden,UUID knowledgeBase,int offset,int limit){String filter="exists(select 1 from garden_knowledge_bases gk where gk.garden_id=?::uuid and gk.knowledge_base_id=pub.knowledge_base_id)";Object[] bindings=new Object[]{garden};if(knowledgeBase!=null){filter+=" and pub.knowledge_base_id=?::uuid";bindings=new Object[]{garden,knowledgeBase};}return content(filter,bindings,false,offset,limit);}
    List<ContentRow> feed(UUID user,int offset,int limit){return content("(exists(select 1 from social_follows f where f.follower_id=?::uuid and ((f.target_type='USER' and f.target_id=pub.published_by) or (f.target_type='KNOWLEDGE_BASE' and f.target_id=pub.knowledge_base_id) or (f.target_type='GARDEN' and exists(select 1 from garden_knowledge_bases gk where gk.garden_id=f.target_id and gk.knowledge_base_id=pub.knowledge_base_id)))) and not exists(select 1 from social_blocks b where (b.blocker_id=?::uuid and b.blocked_id=pub.published_by) or (b.blocker_id=pub.published_by and b.blocked_id=?::uuid)))",new Object[]{user,user,user},false,offset,limit);}
    ContentRow contentByPublication(UUID publication){List<ContentRow> rows=content("pub.id=?::uuid",new Object[]{publication},false,0,1);return rows.isEmpty()?null:rows.getFirst();}
    List<ContentRow> exploreContent(boolean trending,int limit){return content("prof.discoverable and kb.allow_public_index",new Object[]{},trending,0,limit);}
    ReaderRow reader(UUID publication){Record r=dsl.fetchOne("select pub.id publication_id,pub.page_id,pub.knowledge_base_id,kb.name knowledge_base_name,pub.title_snapshot title,p.path,pub.content_type,left(pub.plain_text_snapshot,600) preview,pub.plain_text_snapshot,pub.content_snapshot,pub.schema_version,pub.metadata_snapshot,kb.appearance_config,kb.watermark_config,pub.published_by author_id,prof.slug author_slug,prof.display_name author_name,prof.avatar_url author_avatar,pub.published_at from page_publications pub join pages p on p.id=pub.page_id join knowledge_bases kb on kb.id=pub.knowledge_base_id join public_profiles prof on prof.user_id=pub.published_by where pub.id=?::uuid and pub.superseded_at is null and p.deleted_at is null and (case when p.visibility_override='INHERIT' then kb.visibility else p.visibility_override end)='PUBLIC'",publication);if(r==null)return null;JsonNode pageMetadata=read(r.get("metadata_snapshot",JSONB.class));return new ReaderRow(new ContentRow(r.get("publication_id",UUID.class),r.get("page_id",UUID.class),r.get("knowledge_base_id",UUID.class),r.get("knowledge_base_name",String.class),r.get("title",String.class),r.get("path",String.class),r.get("content_type",String.class),r.get("preview",String.class),r.get("author_id",UUID.class),r.get("author_slug",String.class),r.get("author_name",String.class),r.get("author_avatar",String.class),r.get("published_at",OffsetDateTime.class)),read(r.get("content_snapshot",JSONB.class)),r.get("plain_text_snapshot",String.class),r.get("schema_version",Integer.class),pageMetadata.path("documentSettings"),pageMetadata,read(r.get("appearance_config",JSONB.class)),read(r.get("watermark_config",JSONB.class)));}
    private List<ContentRow> content(String extra,Object[] bindings,boolean trending,int offset,int limit){String score=trending?"((select count(*)*5 from publication_reactions r where r.publication_id=pub.id)+(select count(*) from content_events e where e.resource_type='PAGE' and e.resource_id=pub.page_id and e.event_type='VIEW' and e.occurred_at>now()-interval '30 days'))":"0";String sql="select pub.id publication_id,pub.page_id,pub.knowledge_base_id,kb.name knowledge_base_name,pub.title_snapshot title,p.path,pub.content_type,left(pub.plain_text_snapshot,600) preview,pub.published_by author_id,prof.slug author_slug,prof.display_name author_name,prof.avatar_url author_avatar,pub.published_at,"+score+" score from page_publications pub join pages p on p.id=pub.page_id join knowledge_bases kb on kb.id=pub.knowledge_base_id join public_profiles prof on prof.user_id=pub.published_by where pub.superseded_at is null and p.deleted_at is null and (case when p.visibility_override='INHERIT' then kb.visibility else p.visibility_override end)='PUBLIC' and "+extra+" order by "+(trending?"score desc,":"")+"pub.published_at desc,pub.id desc limit ? offset ?";List<Object> args=new ArrayList<>(List.of(bindings));args.add(limit);args.add(offset);return dsl.fetch(sql,args.toArray()).map(r->new ContentRow(r.get("publication_id",UUID.class),r.get("page_id",UUID.class),r.get("knowledge_base_id",UUID.class),r.get("knowledge_base_name",String.class),r.get("title",String.class),r.get("path",String.class),r.get("content_type",String.class),r.get("preview",String.class),r.get("author_id",UUID.class),r.get("author_slug",String.class),r.get("author_name",String.class),r.get("author_avatar",String.class),r.get("published_at",OffsetDateTime.class)));}

    void block(UUID actor,UUID target,OffsetDateTime now){dsl.insertInto(BLOCKS).columns(uuid("blocker_id"),uuid("blocked_id"),time("created_at")).values(actor,target,now).onConflictDoNothing().execute();dsl.deleteFrom(FOLLOWS).where(uuid("follower_id").eq(actor).and(string("target_type").eq("USER")).and(uuid("target_id").eq(target)).or(uuid("follower_id").eq(target).and(string("target_type").eq("USER")).and(uuid("target_id").eq(actor)))).execute();}
    void unblock(UUID actor,UUID target){dsl.deleteFrom(BLOCKS).where(uuid("blocker_id").eq(actor).and(uuid("blocked_id").eq(target))).execute();}boolean blockedEither(UUID left,UUID right){return dsl.fetchExists(dsl.selectOne().from(BLOCKS).where(uuid("blocker_id").eq(left).and(uuid("blocked_id").eq(right)).or(uuid("blocker_id").eq(right).and(uuid("blocked_id").eq(left)))));}
    void report(UUID id,UUID actor,String type,UUID target,String reason,String details,OffsetDateTime now){dsl.insertInto(REPORTS).columns(uuid("id"),uuid("reporter_id"),string("target_type"),uuid("target_id"),string("reason"),string("details"),string("status"),time("created_at")).values(id,actor,type,target,reason,details,"OPEN",now).execute();}
    List<ReportView> reports(String status,int offset,int limit){return reportSelect().where(status==null?uuid("id").isNotNull():string("status").eq(status)).orderBy(time("created_at").asc(),uuid("id").asc()).limit(limit).offset(Math.max(0,offset)).fetch(this::reportView);}
    ReportView report(UUID id){return reportSelect().where(uuid("id").eq(id)).fetchOne(this::reportView);}
    boolean reviewReport(UUID id,UUID reviewer,String status,String resolution,OffsetDateTime now){return dsl.update(REPORTS).set(string("status"),status).set(uuid("reviewed_by"),reviewer).set(time("reviewed_at"),now).set(string("resolution"),resolution).where(uuid("id").eq(id)).execute()==1;}

    private org.jooq.SelectJoinStep<org.jooq.Record11<UUID,UUID,String,UUID,String,String,String,UUID,OffsetDateTime,String,OffsetDateTime>> reportSelect(){return dsl.select(uuid("id"),uuid("reporter_id"),string("target_type"),uuid("target_id"),string("reason"),string("details"),string("status"),uuid("reviewed_by"),time("reviewed_at"),string("resolution"),time("created_at")).from(REPORTS);}private ReportView reportView(org.jooq.Record11<UUID,UUID,String,UUID,String,String,String,UUID,OffsetDateTime,String,OffsetDateTime> r){return new ReportView(r.value1(),r.value2(),r.value3(),r.value4(),r.value5(),r.value6(),r.value7(),r.value8(),r.value9(),r.value10(),r.value11());}
    private JSONB jsonValue(JsonNode value){return JSONB.valueOf(mapper.writeValueAsString(value==null?mapper.createArrayNode():value));}private JsonNode read(JSONB value){return value==null?mapper.createArrayNode():mapper.readTree(value.data());}private static long value(Number n){return n==null?0:n.longValue();}
    record ProfileRow(UUID userId,String slug,String displayName,String bio,String avatarUrl,String coverUrl,String theme,JsonNode navigation,String seoTitle,String seoDescription,boolean discoverable,boolean rssEnabled,long followerCount,long followingCount,OffsetDateTime updatedAt){}record GardenRow(UUID id,UUID userId,String ownerSlug,String ownerName,String slug,String title,String description,String icon,String coverUrl,String theme,JsonNode navigation,String seoTitle,String seoDescription,boolean discoverable,boolean rssEnabled,long followerCount,OffsetDateTime updatedAt){}record ContentRow(UUID publicationId,UUID pageId,UUID knowledgeBaseId,String knowledgeBaseName,String title,String path,String contentType,String preview,UUID authorId,String authorSlug,String authorName,String authorAvatar,OffsetDateTime publishedAt){}record ReaderRow(ContentRow content,JsonNode document,String plainText,int schemaVersion,JsonNode documentSettings,JsonNode pageMetadata,JsonNode appearanceConfig,JsonNode watermarkConfig){}record PublicationIdentity(UUID id,UUID workspaceId,UUID knowledgeBaseId,UUID pageId,UUID authorId,String visibility){}
    private static org.jooq.Field<UUID> uuid(String v){return field(name(v),UUID.class);}private static org.jooq.Field<String> string(String v){return field(name(v),String.class);}private static org.jooq.Field<Boolean> bool(String v){return field(name(v),Boolean.class);}private static org.jooq.Field<OffsetDateTime> time(String v){return field(name(v),OffsetDateTime.class);}private static org.jooq.Field<JSONB> json(String v){return field(name(v),JSONB.class);}private static org.jooq.Field<BigDecimal> decimal(String v){return field(name(v),BigDecimal.class);}
}
