package io.knowledge.platform.social;

import io.knowledge.platform.analytics.AnalyticsEventCommand;import io.knowledge.platform.analytics.AnalyticsRecorder;import io.knowledge.platform.audit.AuditService;import io.knowledge.platform.authorization.AuthorizationService;import io.knowledge.platform.authorization.Capability;import io.knowledge.platform.authorization.ResourceNotFoundException;import io.knowledge.platform.authorization.ResourceType;import io.knowledge.platform.common.Ids;import java.net.URI;import java.time.Clock;import java.time.OffsetDateTime;import java.util.List;import java.util.Locale;import java.util.Set;import java.util.UUID;import java.util.regex.Pattern;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.JsonNode;import tools.jackson.databind.ObjectMapper;

@Service
public class SocialService {
    private static final Pattern SLUG=Pattern.compile("[a-z0-9]+(?:-[a-z0-9]+)*");private static final Set<String> THEMES=Set.of("PAPER","MINIMAL","MAGAZINE","DARK"),TARGETS=Set.of("USER","KNOWLEDGE_BASE","GARDEN"),REACTIONS=Set.of("LIKE","CLAP","HEART","INSIGHTFUL"),REPORT_TARGETS=Set.of("USER","GARDEN","PUBLICATION"),REPORT_STATUSES=Set.of("REVIEWING","RESOLVED","DISMISSED");
    private final SocialRepository repository;private final AuthorizationService authorization;private final AnalyticsRecorder analytics;private final AuditService audit;private final ObjectMapper mapper;private final Clock clock;private final String publicBaseUrl;
    public SocialService(SocialRepository repository,AuthorizationService authorization,AnalyticsRecorder analytics,AuditService audit,ObjectMapper mapper,Clock clock,@Value("${platform.public-base-url:http://localhost:3000}")String publicBaseUrl){this.repository=repository;this.authorization=authorization;this.analytics=analytics;this.audit=audit;this.mapper=mapper;this.clock=clock;this.publicBaseUrl=publicBaseUrl.replaceAll("/+$","");}

    @Transactional public PublicProfileView saveProfile(UUID actor,String slug,String displayName,String bio,String avatar,String cover,String theme,JsonNode navigation,String seoTitle,String seoDescription,Boolean discoverable,Boolean rss){String normalizedSlug=slug(slug);String name=text(displayName,1,200,"Display name");repository.upsertProfile(actor,normalizedSlug,name,textOrNull(bio,1000,"Bio"),url(avatar),url(cover),theme(theme),navigation(mapper,navigation),textOrNull(seoTitle,200,"SEO title"),textOrNull(seoDescription,500,"SEO description"),!Boolean.FALSE.equals(discoverable),!Boolean.FALSE.equals(rss),now());audit.success(null,actor,"social.profile.update","USER",actor);return profile(actor,normalizedSlug);}
    @Transactional(readOnly=true) public PublicProfileView profile(UUID viewer,String slug){var row=repository.profileBySlug(slug(slug));if(row==null)throw new ResourceNotFoundException();return profileView(viewer,row);}
    @Transactional(readOnly=true) public PublicProfileView myProfile(UUID actor){var row=repository.profileByUser(actor);if(row==null)throw new ResourceNotFoundException();return profileView(actor,row);}
    @Transactional(readOnly=true) public List<PublicContentView> profileContent(UUID viewer,String slug,int limit){var row=repository.profileBySlug(slug(slug));if(row==null)throw new ResourceNotFoundException();return contents(viewer,repository.profileContent(row.userId(),0,bounded(limit)));}
    @Transactional(readOnly=true) public SocialPageView<PublicContentView> profileContentPage(UUID viewer,String slug,int offset,int limit){var row=repository.profileBySlug(slug(slug));if(row==null)throw new ResourceNotFoundException();int start=offset(offset),count=pageSize(limit);return contentPage(viewer,repository.profileContent(row.userId(),start,count+1),start,count);}

    @Transactional public GardenView createGarden(UUID actor,String slug,String title,String description,String icon,String cover,String theme,JsonNode navigation,String seoTitle,String seoDescription,Boolean discoverable,Boolean rss,List<UUID> knowledgeBases){if(repository.profileByUser(actor)==null)throw new IllegalArgumentException("Create a public profile before creating a garden");UUID id=Ids.next();repository.insertGarden(id,actor,slug(slug),text(title,1,160,"Garden title"),textOrNull(description,1000,"Garden description"),textOrNull(icon,2000,"Garden icon"),url(cover),theme(theme),navigation(mapper,navigation),textOrNull(seoTitle,200,"SEO title"),textOrNull(seoDescription,500,"SEO description"),!Boolean.FALSE.equals(discoverable),!Boolean.FALSE.equals(rss),now());replaceGardenKnowledgeBases(actor,id,knowledgeBases);audit.success(null,actor,"social.garden.create","GARDEN",id);return garden(actor,repository.gardenById(id));}
    @Transactional public GardenView updateGarden(UUID actor,UUID id,String slug,String title,String description,String icon,String cover,String theme,JsonNode navigation,String seoTitle,String seoDescription,Boolean discoverable,Boolean rss,List<UUID> knowledgeBases){var existing=requireOwnedGarden(actor,id);repository.updateGarden(id,slug(slug),text(title,1,160,"Garden title"),textOrNull(description,1000,"Garden description"),textOrNull(icon,2000,"Garden icon"),url(cover),theme(theme),navigation(mapper,navigation),textOrNull(seoTitle,200,"SEO title"),textOrNull(seoDescription,500,"SEO description"),!Boolean.FALSE.equals(discoverable),!Boolean.FALSE.equals(rss),now());replaceGardenKnowledgeBases(actor,id,knowledgeBases);audit.success(null,actor,"social.garden.update","GARDEN",existing.id());return garden(actor,repository.gardenById(id));}
    @Transactional public void deleteGarden(UUID actor,UUID id){var existing=requireOwnedGarden(actor,id);if(!repository.deleteGarden(existing.id(),actor))throw new ResourceNotFoundException();audit.success(null,actor,"social.garden.delete","GARDEN",id);}
    @Transactional(readOnly=true) public GardenView publicGarden(UUID viewer,String slug){var row=repository.gardenBySlug(slug(slug));if(row==null)throw new ResourceNotFoundException();return garden(viewer,row);}
    @Transactional(readOnly=true) public List<GardenView> myGardens(UUID actor){return repository.gardensByUser(actor).stream().map(row->garden(actor,row)).toList();}
    @Transactional(readOnly=true) public List<PublicContentView> gardenContent(UUID viewer,String slug,int limit){var row=repository.gardenBySlug(slug(slug));if(row==null)throw new ResourceNotFoundException();return contents(viewer,repository.gardenContent(row.id(),null,0,bounded(limit)));}
    @Transactional(readOnly=true) public SocialPageView<PublicContentView> gardenContentPage(UUID viewer,String slug,UUID knowledgeBase,int offset,int limit){var row=repository.gardenBySlug(slug(slug));if(row==null)throw new ResourceNotFoundException();if(knowledgeBase!=null&&repository.gardenKnowledgeBases(row.id()).stream().noneMatch(value->value.id().equals(knowledgeBase)))throw new ResourceNotFoundException();int start=offset(offset),count=pageSize(limit);return contentPage(viewer,repository.gardenContent(row.id(),knowledgeBase,start,count+1),start,count);}

    @Transactional public boolean follow(UUID actor,String type,UUID target,boolean notifications){String normalized=normalize(type,TARGETS,"Follow target type");if("USER".equals(normalized)&&actor.equals(target))throw new IllegalArgumentException("You cannot follow yourself");validateTarget(normalized,target);UUID owner=targetOwner(normalized,target);if(owner!=null&&repository.blockedEither(actor,owner))throw new IllegalArgumentException("Follow is unavailable because one account blocked the other");repository.follow(actor,normalized,target,notifications,now());audit.success(null,actor,"social.follow",normalized,target);return true;}
    @Transactional public boolean unfollow(UUID actor,String type,UUID target){String normalized=normalize(type,TARGETS,"Follow target type");repository.unfollow(actor,normalized,target);return false;}
    @Transactional(readOnly=true) public FollowStateView followState(UUID actor,String type,UUID target){String normalized=normalize(type,TARGETS,"Follow target type");validateTarget(normalized,target);return repository.followState(actor,normalized,target);}
    @Transactional public PublicContentView react(UUID actor,UUID publication,String reaction){String type=normalize(reaction,REACTIONS,"Reaction type");var identity=repository.publication(publication);if(identity==null||!"PUBLIC".equals(identity.visibility()))throw new ResourceNotFoundException();if(repository.blockedEither(actor,identity.authorId()))throw new ResourceNotFoundException();boolean active=repository.toggleReaction(actor,publication,type,now());if(active)analytics.record(new AnalyticsEventCommand(identity.workspaceId(),actor,null,"PAGE",identity.pageId(),identity.knowledgeBaseId(),"REACTION",null,mapper.createObjectNode().put("reactionType",type)));audit.success(identity.workspaceId(),actor,active?"social.reaction.add":"social.reaction.remove","PUBLICATION",publication);var row=repository.contentByPublication(publication);if(row==null)throw new ResourceNotFoundException();return content(actor,row);}
    @Transactional(readOnly=true) public List<FeedItemView> feed(UUID actor,int limit){return feedItems(actor,repository.feed(actor,0,bounded(limit)));}
    @Transactional(readOnly=true) public SocialPageView<FeedItemView> feedPage(UUID actor,int offset,int limit){int start=offset(offset),count=pageSize(limit);List<SocialRepository.ContentRow> rows=repository.feed(actor,start,count+1);boolean more=rows.size()>count;List<FeedItemView> items=feedItems(actor,rows.subList(0,Math.min(rows.size(),count)));return new SocialPageView<>(items,start+items.size(),more);}
    @Transactional(readOnly=true) public ExploreView explore(UUID viewer,int limit){int count=bounded(limit);return new ExploreView(contents(viewer,repository.exploreContent(true,count)),contents(viewer,repository.exploreContent(false,count)),repository.creatorProfiles(Math.min(count,20)).stream().map(row->profileView(viewer,row)).toList(),repository.exploreGardens(Math.min(count,20)).stream().map(row->garden(viewer,row)).toList());}
    @Transactional public PublicReaderView reader(UUID viewer,UUID publication,String visitorHash){var row=repository.reader(publication);if(row==null)throw new ResourceNotFoundException();var identity=repository.publication(publication);if(identity==null)throw new ResourceNotFoundException();analytics.record(new AnalyticsEventCommand(identity.workspaceId(),viewer,viewer==null?visitorHash:null,"PAGE",identity.pageId(),identity.knowledgeBaseId(),"VIEW",null,mapper.createObjectNode().put("source","PUBLICATION")));return new PublicReaderView(content(viewer,row.content()),row.document(),row.plainText(),row.schemaVersion(),row.documentSettings(),row.pageMetadata(),row.appearanceConfig(),row.watermarkConfig());}
    @Transactional public void block(UUID actor,UUID target){if(actor.equals(target)||!repository.userExists(target))throw new IllegalArgumentException("Blocked user is invalid");repository.block(actor,target,now());audit.success(null,actor,"social.block","USER",target);}
    @Transactional public void unblock(UUID actor,UUID target){repository.unblock(actor,target);}
    @Transactional public ReportView report(UUID actor,String targetType,UUID target,String reason,String details){String type=normalize(targetType,REPORT_TARGETS,"Report target type");validateReportTarget(type,target);UUID id=Ids.next();repository.report(id,actor,type,target,text(reason,1,64,"Report reason"),textOrNull(details,2000,"Report details"),now());audit.success(null,actor,"social.report","REPORT",id);return repository.report(id);}
    @Transactional(readOnly=true) public List<ReportView> reports(String status,int limit){String normalized=status==null||status.isBlank()?null:status.toUpperCase(Locale.ROOT);return repository.reports(normalized,0,Math.max(1,Math.min(limit,200)));}
    @Transactional(readOnly=true) public SocialPageView<ReportView> reportsPage(String status,int offset,int limit){String normalized=status==null||status.isBlank()?null:status.toUpperCase(Locale.ROOT);int start=offset(offset),count=pageSize(limit);List<ReportView> rows=repository.reports(normalized,start,count+1);boolean more=rows.size()>count;List<ReportView> items=List.copyOf(rows.subList(0,Math.min(rows.size(),count)));return new SocialPageView<>(items,start+items.size(),more);}
    @Transactional public void reviewReport(UUID reviewer,UUID id,String status,String resolution){String normalized=normalize(status,REPORT_STATUSES,"Report status");if(!repository.reviewReport(id,reviewer,normalized,textOrNull(resolution,1000,"Resolution"),now()))throw new ResourceNotFoundException();audit.success(null,reviewer,"social.report.review","REPORT",id);}

    @Transactional(readOnly=true) public String profileSitemap(String slug){PublicProfileView profile=profile(null,slug);StringBuilder xml=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">");xml.append(urlEntry(publicBaseUrl+"/u/"+profile.slug(),profile.updatedAt()));for(PublicContentView item:profileContent(null,slug,200))xml.append(urlEntry(publicBaseUrl+"/p/"+item.publicationId(),item.publishedAt()));return xml.append("</urlset>").toString();}
    @Transactional(readOnly=true) public String profileRss(String slug){PublicProfileView profile=profile(null,slug);if(!profile.rssEnabled())throw new ResourceNotFoundException();StringBuilder xml=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><rss version=\"2.0\"><channel><title>").append(escape(profile.displayName())).append("</title><link>").append(publicBaseUrl).append("/u/").append(profile.slug()).append("</link><description>").append(escape(profile.bio()==null?"":profile.bio())).append("</description>");for(PublicContentView item:profileContent(null,slug,50))xml.append("<item><guid>").append(item.publicationId()).append("</guid><title>").append(escape(item.title())).append("</title><link>").append(publicBaseUrl).append("/p/").append(item.publicationId()).append("</link><description>").append(escape(item.preview())).append("</description><pubDate>").append(java.time.format.DateTimeFormatter.RFC_1123_DATE_TIME.format(item.publishedAt())).append("</pubDate></item>");return xml.append("</channel></rss>").toString();}

    private PublicProfileView profileView(UUID viewer,SocialRepository.ProfileRow row){return new PublicProfileView(row.userId(),row.slug(),row.displayName(),row.bio(),row.avatarUrl(),row.coverUrl(),row.theme(),row.navigation(),row.seoTitle(),row.seoDescription(),row.discoverable(),row.rssEnabled(),row.followerCount(),row.followingCount(),repository.followed(viewer,"USER",row.userId()),row.updatedAt());}
    private GardenView garden(UUID viewer,SocialRepository.GardenRow row){return new GardenView(row.id(),row.userId(),row.ownerSlug(),row.ownerName(),row.slug(),row.title(),row.description(),row.icon(),row.coverUrl(),row.theme(),row.navigation(),row.seoTitle(),row.seoDescription(),row.discoverable(),row.rssEnabled(),row.followerCount(),repository.followed(viewer,"GARDEN",row.id()),repository.gardenKnowledgeBases(row.id()),row.updatedAt());}
    private List<PublicContentView> contents(UUID viewer,List<SocialRepository.ContentRow> rows){return rows.stream().map(row->content(viewer,row)).toList();}private PublicContentView content(UUID viewer,SocialRepository.ContentRow row){return new PublicContentView(row.publicationId(),row.pageId(),row.knowledgeBaseId(),row.knowledgeBaseName(),row.title(),row.path(),row.contentType(),row.preview(),row.authorId(),row.authorSlug(),row.authorName(),row.authorAvatar(),repository.reactionCounts(row.publicationId()),repository.viewerReactions(viewer,row.publicationId()),row.publishedAt());}
    private SocialPageView<PublicContentView> contentPage(UUID viewer,List<SocialRepository.ContentRow> rows,int offset,int limit){boolean more=rows.size()>limit;List<PublicContentView> items=contents(viewer,rows.subList(0,Math.min(rows.size(),limit)));return new SocialPageView<>(items,offset+items.size(),more);}private List<FeedItemView> feedItems(UUID viewer,List<SocialRepository.ContentRow> rows){return rows.stream().map(row->new FeedItemView("FOLLOWING",content(viewer,row))).toList();}
    private void replaceGardenKnowledgeBases(UUID actor,UUID garden,List<UUID> ids){List<UUID> values=ids==null?List.of():ids.stream().distinct().limit(100).toList();for(UUID kb:values){authorization.require(actor,ResourceType.KNOWLEDGE_BASE,kb,Capability.MANAGE);if(!repository.knowledgeBasePublic(kb))throw new IllegalArgumentException("Only public knowledge bases can be added to a garden");}repository.replaceGardenKnowledgeBases(garden,values);}
    private SocialRepository.GardenRow requireOwnedGarden(UUID actor,UUID id){var row=repository.gardenById(id);if(row==null||!actor.equals(row.userId()))throw new ResourceNotFoundException();return row;}
    private void validateTarget(String type,UUID target){boolean valid=switch(type){case"USER"->repository.profileByUser(target)!=null;case"KNOWLEDGE_BASE"->repository.knowledgeBasePublic(target);case"GARDEN"->repository.gardenById(target)!=null;default->false;};if(!valid)throw new ResourceNotFoundException();}private UUID targetOwner(String type,UUID target){return switch(type){case"USER"->target;case"GARDEN"->{var row=repository.gardenById(target);yield row==null?null:row.userId();}default->null;};}
    private void validateReportTarget(String type,UUID target){boolean valid=switch(type){case"USER"->repository.userExists(target);case"GARDEN"->repository.gardenById(target)!=null;case"PUBLICATION"->repository.publication(target)!=null;default->false;};if(!valid)throw new ResourceNotFoundException();}
    private static String normalize(String value,Set<String> allowed,String label){String normalized=value==null?"":value.toUpperCase(Locale.ROOT);if(!allowed.contains(normalized))throw new IllegalArgumentException(label+" is invalid");return normalized;}private static String slug(String value){String normalized=value==null?"":value.trim().toLowerCase(Locale.ROOT);if(normalized.length()<2||normalized.length()>80||!SLUG.matcher(normalized).matches())throw new IllegalArgumentException("Public slug is invalid");return normalized;}private static String theme(String value){return normalize(value==null?"PAPER":value,THEMES,"Theme");}
    static JsonNode navigation(ObjectMapper mapper,JsonNode value){if(value==null)return mapper.createArrayNode();if(!value.isArray()||value.size()>30)throw new IllegalArgumentException("Navigation must be an array with at most 30 entries");var normalized=mapper.createArrayNode();for(JsonNode item:value){if(!item.isObject())throw new IllegalArgumentException("Navigation entry is invalid");String label=text(item.path("label").stringValue(null),1,100,"Navigation label");String destination=navigationUrl(item.path("url").stringValue(null));normalized.addObject().put("label",label).put("url",destination);}return normalized;}
    static String navigationUrl(String value){String normalized=text(value,1,2000,"Navigation URL");if(hasControlCharacter(normalized))throw new IllegalArgumentException("Navigation URL is invalid");if((normalized.startsWith("/")&&!normalized.startsWith("//"))||normalized.startsWith("#"))return normalized;return secureHttpsUrl(normalized,"Navigation URL");}
    private static String text(String value,int min,int max,String label){String normalized=value==null?"":value.trim();if(normalized.length()<min||normalized.length()>max)throw new IllegalArgumentException(label+" is invalid");return normalized;}private static String textOrNull(String value,int max,String label){if(value==null||value.isBlank())return null;return text(value,1,max,label);}static String url(String value){String normalized=textOrNull(value,2000,"URL");return normalized==null?null:secureHttpsUrl(normalized,"URL");}private static String secureHttpsUrl(String value,String label){try{URI uri=URI.create(value);if(!"https".equalsIgnoreCase(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null||hasControlCharacter(value))throw new IllegalArgumentException(label+" must use HTTPS");return uri.toString();}catch(IllegalArgumentException exception){if((label+" must use HTTPS").equals(exception.getMessage()))throw exception;throw new IllegalArgumentException(label+" is invalid",exception);}}private static boolean hasControlCharacter(String value){return value.chars().anyMatch(Character::isISOControl);}private static int bounded(int value){return Math.max(1,Math.min(value,100));}private static int pageSize(int value){return Math.max(1,Math.min(value,50));}private static int offset(int value){return Math.max(0,Math.min(value,1_000_000));}private OffsetDateTime now(){return OffsetDateTime.now(clock);}private static String escape(String value){return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}private static String urlEntry(String location,OffsetDateTime modified){return "<url><loc>"+escape(location)+"</loc><lastmod>"+modified.toLocalDate()+"</lastmod></url>";}
}
