<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import type { Page } from '../../../src/types'

type BoardElement = { id: string; kind: 'RECT'|'ELLIPSE'|'STICKY'|'TEXT'|'ARROW'; x: number; y: number; width: number; height: number; text: string; color: string }
type Board = { type: 'whiteboard'; viewport: { x: number; y: number; zoom: number }; elements: BoardElement[] }
type Sheet = { id: string; name: string; rows: string[][]; styles: Record<string, unknown>; frozenRows: number; frozenColumns: number; hiddenRows: number[]; hiddenColumns: number[]; protectedCells: string[]; dropdowns: Record<string,string[]>; filter: string }
type Workbook = { type:'workbook'; activeSheetId:string; sheets:Sheet[] }
type Field = { id:string; name:string; type:string; options?:string[] }
type Row = { id:string; values:Record<string,unknown> }
type Database = { type:'database'; fields:Field[]; rows:Row[]; view:string; filter:string; sortFieldId:string|null; views?:unknown[]; activeViewId?:string; form?:unknown }

const props = defineProps<{ type: Page['contentType']; modelValue: string }>()
const emit = defineEmits<{ 'update:modelValue': [value:string] }>()
const selected = ref(''); const boardTool = ref<BoardElement['kind']>('STICKY'); const databaseView = ref('TABLE')
const drag = reactive({ id:'', startX:0, startY:0, x:0, y:0 })
function parse<T>(fallback:T):T { try { const value=JSON.parse(props.modelValue) as T; return value && typeof value==='object' ? value : fallback } catch { return fallback } }
function save(value: unknown) { emit('update:modelValue', JSON.stringify(value)) }
const board = computed<Board>(() => { const raw=parse<Partial<Board>>({}); return { type:'whiteboard', viewport:raw.viewport && typeof raw.viewport==='object' ? { x:Number(raw.viewport.x)||0,y:Number(raw.viewport.y)||0,zoom:Math.max(.25,Math.min(3,Number(raw.viewport.zoom)||1)) } : {x:0,y:0,zoom:1}, elements:Array.isArray(raw.elements)?raw.elements:[] } })
function addBoard() { const kind=boardTool.value; const element:BoardElement={id:crypto.randomUUID(),kind,x:180+board.value.elements.length*18,y:120+board.value.elements.length*18,width:kind==='ARROW'?200:180,height:kind==='STICKY'?140:kind==='TEXT'?60:110,text:kind==='STICKY'?'新便签':'',color:kind==='STICKY'?'#fef3a7':'#ffffff'}; save({...board.value,elements:[...board.value.elements,element]});selected.value=element.id }
function patchBoard(id:string, patch:Partial<BoardElement>){ save({...board.value,elements:board.value.elements.map(item=>item.id===id?{...item,...patch}:item)}) }
function pointerMove(event:PointerEvent){ if(!drag.id)return; patchBoard(drag.id,{x:drag.x+(event.clientX-drag.startX)/board.value.viewport.zoom,y:drag.y+(event.clientY-drag.startY)/board.value.viewport.zoom}) }
function startDrag(event:PointerEvent,item:BoardElement){ selected.value=item.id;drag.id=item.id;drag.startX=event.clientX;drag.startY=event.clientY;drag.x=item.x;drag.y=item.y }
function removeBoard(){save({...board.value,elements:board.value.elements.filter(item=>item.id!==selected.value)});selected.value='' }

function emptySheet(name='工作表 1'):Sheet{return{id:crypto.randomUUID(),name,rows:[],styles:{},frozenRows:0,frozenColumns:0,hiddenRows:[],hiddenColumns:[],protectedCells:[],dropdowns:{},filter:''}}
const workbook=computed<Workbook>(()=>{const raw=parse<Partial<Workbook>>({});const sheets=Array.isArray(raw.sheets)&&raw.sheets.length?raw.sheets:[emptySheet()];return{type:'workbook',activeSheetId:sheets.some(s=>s.id===raw.activeSheetId)?raw.activeSheetId!:sheets[0]!.id,sheets}})
const sheet=computed(()=>workbook.value.sheets.find(item=>item.id===workbook.value.activeSheetId)??workbook.value.sheets[0]!)
const columns=Array.from({length:12},(_,i)=>i);const rows=Array.from({length:30},(_,i)=>i)
function columnName(index:number){let value='';for(let i=index+1;i>0;i=Math.floor((i-1)/26))value=String.fromCharCode(65+(i-1)%26)+value;return value}
function updateCell(row:number,column:number,value:string){const data=sheet.value.rows.map(cells=>[...cells]);while(data.length<=row)data.push([]);while(data[row]!.length<=column)data[row]!.push('');data[row]![column]=value;save({...workbook.value,sheets:workbook.value.sheets.map(item=>item.id===sheet.value.id?{...item,rows:data}:item)})}
function addSheet(){const next=emptySheet(`工作表 ${workbook.value.sheets.length+1}`);save({...workbook.value,activeSheetId:next.id,sheets:[...workbook.value.sheets,next]})}

const database=computed<Database>(()=>{const raw=parse<Partial<Database>>({});const fields=Array.isArray(raw.fields)&&raw.fields.length?raw.fields:[{id:'name',name:'名称',type:'TEXT'},{id:'status',name:'状态',type:'SELECT',options:['待处理','进行中','已完成']},{id:'date',name:'日期',type:'DATE'}];return{type:'database',fields,rows:Array.isArray(raw.rows)?raw.rows:[],view:raw.view??'TABLE',filter:raw.filter??'',sortFieldId:raw.sortFieldId??null,views:raw.views,activeViewId:raw.activeViewId,form:raw.form}})
const visibleRows=computed(()=>database.value.rows.filter(row=>!database.value.filter||Object.values(row.values).some(value=>String(value??'').toLowerCase().includes(database.value.filter.toLowerCase()))))
function addField(){const name=prompt('字段名称');if(!name)return;save({...database.value,fields:[...database.value.fields,{id:crypto.randomUUID(),name,type:'TEXT'}]})}
function addRow(){save({...database.value,rows:[...database.value.rows,{id:crypto.randomUUID(),values:{name:'新记录'}}]})}
function updateValue(rowId:string,fieldId:string,value:unknown){save({...database.value,rows:database.value.rows.map(row=>row.id===rowId?{...row,values:{...row.values,[fieldId]:value}}:row)})}
function removeRow(rowId:string){save({...database.value,rows:database.value.rows.filter(row=>row.id!==rowId)})}
</script>

<template>
  <div v-if="type==='WHITEBOARD'" class="structured-editor board-wrap">
    <v-toolbar density="compact" color="surface" flat border="bottom" class="px-3"><v-btn-toggle v-model="boardTool" mandatory color="primary" density="compact"><v-btn value="STICKY" prepend-icon="mdi-note-outline">便签</v-btn><v-btn value="RECT" prepend-icon="mdi-rectangle-outline">矩形</v-btn><v-btn value="ELLIPSE" prepend-icon="mdi-circle-outline">椭圆</v-btn><v-btn value="TEXT" prepend-icon="mdi-format-text">文本</v-btn><v-btn value="ARROW" prepend-icon="mdi-arrow-right">箭头</v-btn></v-btn-toggle><v-divider vertical class="mx-3"/><v-btn data-testid="add-board" prepend-icon="mdi-plus" @click="addBoard">添加</v-btn><v-btn v-if="selected" color="error" variant="text" prepend-icon="mdi-trash-can-outline" @click="removeBoard">删除</v-btn><v-spacer/><v-btn icon="mdi-minus" @click="save({...board,viewport:{...board.viewport,zoom:Math.max(.25,board.viewport.zoom-.1)}})"/><span class="text-caption mx-2">{{Math.round(board.viewport.zoom*100)}}%</span><v-btn icon="mdi-plus" @click="save({...board,viewport:{...board.viewport,zoom:Math.min(3,board.viewport.zoom+.1)}})"/></v-toolbar>
    <div class="board-canvas" @pointermove="pointerMove" @pointerup="drag.id=''" @pointerleave="drag.id=''">
      <div class="board-surface" :style="{transform:`translate(${board.viewport.x}px,${board.viewport.y}px) scale(${board.viewport.zoom})`}"><div v-for="item in board.elements" :key="item.id" class="board-item" :class="[{selected:selected===item.id},`kind-${item.kind.toLowerCase()}`]" :style="{left:`${item.x}px`,top:`${item.y}px`,width:`${item.width}px`,height:`${item.height}px`,background:item.kind==='ARROW'?'transparent':item.color}" @pointerdown.stop="startDrag($event,item)"><span v-if="item.kind==='ARROW'" class="arrow-line">→</span><textarea v-else :value="item.text" @pointerdown.stop @input="patchBoard(item.id,{text:($event.target as HTMLTextAreaElement).value})" /></div></div>
      <div v-if="!board.elements.length" class="empty-state"><div><v-icon size="48">mdi-drawing-box</v-icon><h3>无限白板</h3><p>选择元素类型并添加到画布。</p><v-btn color="primary" @click="addBoard">添加便签</v-btn></div></div>
    </div>
  </div>

  <div v-else-if="type==='SPREADSHEET'" class="structured-editor sheet-wrap">
    <v-toolbar density="compact" color="surface" flat border="bottom" class="px-3"><v-btn icon="mdi-format-bold"/><v-btn icon="mdi-format-italic"/><v-btn icon="mdi-format-align-left"/><v-divider vertical class="mx-2"/><v-btn prepend-icon="mdi-table-row-plus-after">插入行</v-btn><v-spacer/><v-chip size="small" variant="tonal">{{sheet.name}}</v-chip></v-toolbar>
    <div class="sheet-scroll"><table><thead><tr><th class="corner"></th><th v-for="column in columns" :key="column">{{columnName(column)}}</th></tr></thead><tbody><tr v-for="row in rows" :key="row"><th>{{row+1}}</th><td v-for="column in columns" :key="column"><input :aria-label="`${columnName(column)}${row+1}`" :value="sheet.rows[row]?.[column]??''" @input="updateCell(row,column,($event.target as HTMLInputElement).value)" /></td></tr></tbody></table></div>
    <div class="sheet-tabs"><v-btn v-for="item in workbook.sheets" :key="item.id" :color="item.id===workbook.activeSheetId?'primary':undefined" variant="text" @click="save({...workbook,activeSheetId:item.id})">{{item.name}}</v-btn><v-btn icon="mdi-plus" variant="text" @click="addSheet"/></div>
  </div>

  <div v-else class="structured-editor database-wrap">
    <v-toolbar density="compact" color="surface" flat border="bottom" class="px-3"><v-btn-toggle v-model="databaseView" mandatory color="primary" density="compact"><v-btn value="TABLE" prepend-icon="mdi-table">表格</v-btn><v-btn value="KANBAN" prepend-icon="mdi-view-column-outline">看板</v-btn><v-btn value="GALLERY" prepend-icon="mdi-view-grid-outline">画廊</v-btn><v-btn value="CALENDAR" prepend-icon="mdi-calendar-outline">日历</v-btn></v-btn-toggle><v-divider vertical class="mx-3"/><v-text-field :model-value="database.filter" placeholder="筛选记录" prepend-inner-icon="mdi-filter-outline" max-width="260" hide-details @update:model-value="save({...database,filter:$event})"/><v-spacer/><v-btn prepend-icon="mdi-table-column-plus-after" @click="addField">字段</v-btn><v-btn color="primary" prepend-icon="mdi-plus" @click="addRow">记录</v-btn></v-toolbar>
    <div v-if="databaseView==='TABLE'" class="database-table"><table><thead><tr><th v-for="field in database.fields" :key="field.id">{{field.name}}<small>{{field.type}}</small></th><th></th></tr></thead><tbody><tr v-for="row in visibleRows" :key="row.id"><td v-for="field in database.fields" :key="field.id"><v-checkbox v-if="field.type==='CHECKBOX'" :model-value="Boolean(row.values[field.id])" hide-details density="compact" @update:model-value="updateValue(row.id,field.id,$event)"/><v-select v-else-if="field.type==='SELECT'" :model-value="row.values[field.id]" :items="field.options??[]" variant="plain" hide-details @update:model-value="updateValue(row.id,field.id,$event)"/><input v-else :type="field.type==='DATE'?'date':field.type==='NUMBER'?'number':'text'" :value="String(row.values[field.id]??'')" @input="updateValue(row.id,field.id,($event.target as HTMLInputElement).value)" /></td><td><v-btn icon="mdi-delete-outline" variant="text" color="error" size="small" @click="removeRow(row.id)"/></td></tr></tbody></table></div>
    <div v-else-if="databaseView==='KANBAN'" class="kanban"><v-card v-for="status in (database.fields.find(f=>f.type==='SELECT')?.options??['未分组'])" :key="status" class="section-card pa-3"><strong>{{status}}</strong><v-card v-for="row in visibleRows.filter(row=>row.values[database.fields.find(f=>f.type==='SELECT')?.id??'']===status)" :key="row.id" class="mt-3 pa-3" variant="tonal">{{row.values.name||'无标题记录'}}</v-card></v-card></div>
    <div v-else class="surface-grid pa-5"><v-card v-for="row in visibleRows" :key="row.id" class="section-card pa-4"><strong>{{row.values.name||'无标题记录'}}</strong><p v-for="field in database.fields.slice(1,4)" :key="field.id" class="muted text-body-2 mt-2 mb-0">{{field.name}}：{{row.values[field.id]||'—'}}</p></v-card></div>
  </div>
</template>

<style scoped>
.structured-editor{height:calc(100vh - 65px);background:#f8fafc;overflow:hidden}.board-canvas{height:calc(100% - 48px);position:relative;overflow:hidden;background-color:#f8fafc;background-image:radial-gradient(#cbd5e1 1px,transparent 1px);background-size:20px 20px}.board-surface{position:absolute;inset:0;transform-origin:0 0}.board-item{position:absolute;border:1px solid #cbd5e1;border-radius:10px;box-shadow:0 8px 20px #0f172a12;touch-action:none}.board-item.selected{outline:2px solid #2563eb}.board-item.kind-ellipse{border-radius:999px}.board-item textarea{width:100%;height:100%;border:0;background:transparent;resize:none;outline:0;padding:14px}.arrow-line{font-size:54px;color:#475569}.sheet-scroll,.database-table{height:calc(100% - 96px);overflow:auto}.sheet-wrap table,.database-wrap table{border-collapse:separate;border-spacing:0;min-width:max-content}.sheet-wrap th,.sheet-wrap td,.database-wrap th,.database-wrap td{border-right:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;background:white}.sheet-wrap th{min-width:96px;height:32px;background:#f1f5f9;color:#64748b;font-size:12px;position:sticky;top:0;z-index:2}.sheet-wrap tbody th{left:0;min-width:42px;position:sticky;z-index:1}.sheet-wrap input{width:96px;height:34px;border:0;outline:0;padding:5px 8px}.sheet-wrap input:focus{box-shadow:inset 0 0 0 2px #2563eb}.sheet-tabs{height:48px;display:flex;align-items:center;border-top:1px solid #e2e8f0;background:white;padding:0 12px}.database-wrap th{min-width:180px;padding:12px;text-align:left;position:sticky;top:0;z-index:1}.database-wrap th small{display:block;color:#94a3b8}.database-wrap td{padding:0 10px}.database-wrap td input{width:100%;min-height:44px;border:0;outline:0}.kanban{display:grid;grid-auto-flow:column;grid-auto-columns:280px;gap:16px;padding:20px;height:calc(100% - 48px);overflow:auto}
</style>
