<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { Explore, PublicContent, SearchResponse } from '../../../src/types'
import PublicLayout from '../../layouts/PublicLayout.vue'
import { messageOf, post } from '../../services/api'
const data=ref<Explore|null>(null);const query=ref('');const results=ref<PublicContent[]>([]);const loading=ref(true);const error=ref('')
onMounted(async()=>{try{data.value=await post('/api/public/v1/social/explore',{limit:18},false)}catch(value){error.value=messageOf(value)}finally{loading.value=false}})
async function search(){if(!query.value.trim()){results.value=[];return}const response=await post<SearchResponse>('/api/public/v1/search',{workspaceId:null,query:query.value.trim(),offset:0,limit:24},false);results.value=response.results.filter(item=>item.publicationId).map(item=>({publicationId:item.publicationId!,pageId:item.resourceId,knowledgeBaseId:item.knowledgeBaseId!,knowledgeBaseName:'公开知识',title:item.title,path:item.path??'',contentType:(item.contentType??'DOCUMENT') as PublicContent['contentType'],preview:item.snippet,authorId:'',authorSlug:'',authorName:'',authorAvatar:null,reactions:{},viewerReactions:[],publishedAt:item.updatedAt}))}
const contentIcon=(type:string)=>({DOCUMENT:'mdi-file-document-outline',WHITEBOARD:'mdi-drawing-box',SPREADSHEET:'mdi-table-large',DATABASE:'mdi-database-outline'} as Record<string,string>)[type]??'mdi-file-outline'
</script>
<template><PublicLayout><main class="public-page"><section class="explore-hero"><v-chip color="primary" variant="tonal" class="mb-5">公开知识网络</v-chip><h1>发现值得长期关注的知识</h1><p>浏览团队与创作者公开发布的文档、白板和结构化内容。</p><div class="public-search-box"><v-text-field v-model="query" placeholder="搜索公开内容" prepend-inner-icon="mdi-magnify" hide-details @keyup.enter="search"/><v-btn color="primary" size="large" @click="search">搜索</v-btn></div></section><v-progress-linear v-if="loading" indeterminate color="primary"/><v-alert v-if="error" type="error" variant="tonal">{{error}}</v-alert>
<section v-if="results.length" class="public-section"><h2>搜索结果</h2><div class="surface-grid"><v-card v-for="item in results" :key="item.publicationId" :to="`/p/${item.publicationId}`" class="section-card clickable pa-5"><v-icon color="primary" size="30">{{contentIcon(item.contentType)}}</v-icon><h3 class="mt-4">{{item.title}}</h3><p class="muted">{{item.preview}}</p></v-card></div></section>
<template v-if="data"><section class="public-section"><h2>正在流行</h2><p>近期阅读和互动较多的内容</p><div class="surface-grid"><v-card v-for="item in data.trending" :key="item.publicationId" :to="`/p/${item.publicationId}`" class="section-card clickable pa-5"><v-icon color="primary" size="30">{{contentIcon(item.contentType)}}</v-icon><h3 class="mt-4 mb-2">{{item.title}}</h3><p class="muted">{{item.preview}}</p><v-chip size="small" variant="tonal">{{item.authorName}}</v-chip></v-card></div></section><section class="public-section"><h2>刚刚发布</h2><div class="surface-grid"><v-card v-for="item in data.latest" :key="item.publicationId" :to="`/p/${item.publicationId}`" class="section-card clickable pa-5"><h3>{{item.title}}</h3><p class="muted">{{item.preview}}</p></v-card></div></section><section class="public-section"><h2>创作者</h2><div class="surface-grid"><v-card v-for="creator in data.creators" :key="creator.userId" :to="`/u/${creator.slug}`" class="section-card clickable pa-5"><div class="d-flex align-center"><v-avatar color="primary" class="mr-4">{{creator.displayName.slice(0,1)}}</v-avatar><div><h3>{{creator.displayName}}</h3><p class="muted mb-0">{{creator.bio||`@${creator.slug}`}}</p></div></div></v-card></div></section></template></main></PublicLayout></template>
<style scoped>.public-page{width:min(1280px,100%);margin:auto;padding:0 32px 80px}.explore-hero{text-align:center;padding:110px 20px 80px;background:radial-gradient(circle at 50% 0,#dbeafe,transparent 55%)}.explore-hero h1{font-size:clamp(42px,6vw,72px);letter-spacing:-.06em;line-height:1.05;margin:0 auto 22px;max-width:900px}.explore-hero>p{font-size:19px;color:#64748b}.public-search-box{display:flex;gap:12px;max-width:700px;margin:38px auto 0}.public-section{padding-top:64px}.public-section>h2{font-size:30px;letter-spacing:-.035em;margin-bottom:8px}.public-section>p{color:#64748b;margin-bottom:24px}</style>
