<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import type { Garden, PublicContent, SocialPage } from '../../../src/types'
import PublicLayout from '../../layouts/PublicLayout.vue'
import { messageOf, post } from '../../services/api'
const route=useRoute();const slug=String(route.params.slug);const garden=ref<Garden|null>(null);const items=ref<PublicContent[]>([]);const selected=ref('');const loading=ref(true);const error=ref('')
onMounted(async()=>{try{garden.value=await post('/api/public/v1/social/garden',{slug},false);await loadContent()}catch(value){error.value=messageOf(value)}finally{loading.value=false}});watch(selected,loadContent)
async function loadContent(){items.value=(await post<SocialPage<PublicContent>>('/api/public/v1/social/garden/content/page',{slug,knowledgeBaseId:selected.value||null,offset:0,limit:48},false)).items}
</script>
<template><PublicLayout><main v-if="garden" class="garden-public"><header :style="garden.coverUrl?{backgroundImage:`linear-gradient(#0f172a88,#0f172acc),url(${garden.coverUrl})`}:{}"><span class="garden-icon">{{garden.icon||'🌿'}}</span><p>{{garden.ownerName}} 的知识花园</p><h1>{{garden.title}}</h1><p>{{garden.description||'把知识种成一座可以漫游的花园。'}}</p><router-link :to="`/u/${garden.ownerSlug}`" class="text-white">查看创作者</router-link></header><nav><v-btn :color="!selected?'primary':undefined" variant="text" @click="selected=''">全部</v-btn><v-btn v-for="kb in garden.knowledgeBases" :key="kb.id" :color="selected===kb.id?'primary':undefined" variant="text" @click="selected=kb.id">{{kb.icon||'📘'}} {{kb.name}}</v-btn></nav><section><div class="surface-grid"><v-card v-for="item in items" :key="item.publicationId" :to="`/p/${item.publicationId}`" class="section-card clickable pa-5"><h3>{{item.title}}</h3><p class="muted">{{item.preview}}</p><v-chip size="x-small">{{item.knowledgeBaseName}}</v-chip></v-card></div><div v-if="!items.length" class="empty-state"><h3>这个分区还没有内容</h3></div></section></main><v-progress-linear v-else-if="loading" indeterminate/><v-alert v-else type="error">{{error}}</v-alert></PublicLayout></template>
<style scoped>.garden-public>header{padding:110px max(32px,calc((100% - 1120px)/2));background:#0f172a;color:white;background-size:cover;background-position:center}.garden-public>header h1{font-size:58px;letter-spacing:-.05em;margin:12px 0}.garden-icon{font-size:50px}.garden-public>nav,.garden-public>section{width:min(1120px,calc(100% - 40px));margin:auto}.garden-public>nav{display:flex;gap:8px;overflow:auto;padding:24px 0;border-bottom:1px solid #e2e8f0}.garden-public>section{padding:40px 0 80px}</style>
