<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import type { CurrentUser, OAuthAuthorizationInfo } from '../../../src/types'
import PublicLayout from '../../layouts/PublicLayout.vue'
import { get, messageOf } from '../../services/api'
const route=useRoute();const info=ref<OAuthAuthorizationInfo|null>(null);const me=ref<CurrentUser|null>(null);const csrf=ref<{parameterName:string;token:string}|null>(null);const loading=ref(true);const error=ref('')
const query=computed(()=>new URLSearchParams(Object.entries(route.query).flatMap(([key,value])=>typeof value==='string'?[[key,value]]:[])).toString())
onMounted(async()=>{try{[info.value,me.value]=await Promise.all([get(`/oauth/authorize?${query.value}`),get('/api/v1/auth/me')]);csrf.value=await get('/api/v1/auth/csrf')}catch(value){error.value=messageOf(value)}finally{loading.value=false}})
function deny(){if(!info.value)return;const target=new URL(info.value.redirectUri);target.searchParams.set('error','access_denied');if(route.query.state)target.searchParams.set('state',String(route.query.state));location.assign(target.toString())}
const fields=['client_id','redirect_uri','scope','state','code_challenge','code_challenge_method']
</script>
<template><PublicLayout><main class="consent-page"><v-progress-circular v-if="loading" indeterminate/><v-card v-else-if="!me" class="consent-card section-card pa-8"><v-icon color="primary" size="52">mdi-shield-account-outline</v-icon><h1>登录后继续授权</h1><p>{{error||'完成登录后会返回这个授权请求。'}}</p><v-btn :to="`/login?returnTo=${encodeURIComponent($route.fullPath)}`" color="primary" block>登录</v-btn></v-card><v-card v-else-if="info&&csrf" class="consent-card section-card pa-8"><v-avatar color="primary" variant="tonal" size="64"><v-icon size="34">mdi-application-brackets-outline</v-icon></v-avatar><p class="text-overline text-primary mt-5">OAuth 授权</p><h1>{{info.name}} 想访问你的知识</h1><p>当前账号 <strong>{{me.email}}</strong>。应用仍然受你的资源权限约束。</p><v-list class="scope-list my-5"><v-list-item v-for="scope in info.scopes" :key="scope" prepend-icon="mdi-check-circle-outline" :title="scope"/></v-list><v-alert type="info" variant="tonal" class="mb-5">强制 PKCE S256 · Redirect URI 精确匹配 · 可随时撤销</v-alert><form method="post" action="/oauth/authorize"><input v-for="field in fields" :key="field" type="hidden" :name="field" :value="String($route.query[field]||'')"/><input type="hidden" name="consent" value="true"/><input type="hidden" :name="csrf.parameterName" :value="csrf.token"/><div class="d-flex ga-3"><v-btn block variant="outlined" type="button" @click="deny">拒绝</v-btn><v-btn block color="primary" type="submit">允许访问</v-btn></div></form></v-card><v-card v-else class="consent-card section-card pa-8"><v-icon color="error" size="52">mdi-alert-circle-outline</v-icon><h1>无效的授权请求</h1><p>{{error}}</p><v-btn to="/app" variant="outlined" block>返回工作台</v-btn></v-card></main></PublicLayout></template>
<style scoped>.consent-page{min-height:calc(100vh - 64px);display:grid;place-items:center;background:#f8fafc;padding:30px}.consent-card{width:min(560px,100%);text-align:center}.consent-card h1{font-size:30px;letter-spacing:-.035em;margin:12px 0}.consent-card>p{color:#64748b}.scope-list{text-align:left;background:#f8fafc;border-radius:16px}</style>
