<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import type { PublicContent, PublicProfile, SocialPage } from '../../../src/types'
import PublicLayout from '../../layouts/PublicLayout.vue'
import { messageOf, post } from '../../services/api'
import { useSessionStore } from '../../stores/session'
const route=useRoute();const session=useSessionStore();const slug=String(route.params.slug);const profile=ref<PublicProfile|null>(null);const items=ref<PublicContent[]>([]);const error=ref('');const loading=ref(true)
const self=computed(()=>session.user?.userId===profile.value?.userId)
onMounted(async()=>{try{[profile.value,items.value]=await Promise.all([post('/api/public/v1/social/profile',{slug},false),post<SocialPage<PublicContent>>('/api/public/v1/social/profile/content/page',{slug,offset:0,limit:48},false).then(v=>v.items)])}catch(value){error.value=messageOf(value)}finally{loading.value=false}})
async function follow(){if(!profile.value)return;if(!session.user){location.href=`/login?returnTo=${encodeURIComponent(location.pathname)}`;return}await post(profile.value.followed?'/api/v1/social/unfollow':'/api/v1/social/follow',{targetType:'USER',targetId:profile.value.userId,notificationsEnabled:true});profile.value.followed=!profile.value.followed;profile.value.followerCount+=profile.value.followed?1:-1}
</script>
<template><PublicLayout><main class="profile-public"><v-progress-linear v-if="loading" indeterminate color="primary"/><v-alert v-if="error" type="error" variant="tonal" class="ma-6">{{error}}</v-alert><template v-if="profile"><div class="profile-cover" :style="profile.coverUrl?{backgroundImage:`url(${profile.coverUrl})`}:{}"/><header class="profile-head"><v-avatar color="primary" size="104" class="profile-avatar"><v-img v-if="profile.avatarUrl" :src="profile.avatarUrl"/><span v-else class="text-h3">{{profile.displayName.slice(0,1)}}</span></v-avatar><div class="profile-copy"><h1>{{profile.displayName}}</h1><p>@{{profile.slug}}</p><p>{{profile.bio||'正在持续整理和分享知识。'}}</p><div class="d-flex ga-5 text-body-2"><span><strong>{{profile.followerCount}}</strong> 关注者</span><span><strong>{{profile.followingCount}}</strong> 正在关注</span></div></div><v-spacer/><v-btn v-if="self" to="/app/profile" variant="outlined">编辑主页</v-btn><v-btn v-else :color="profile.followed?'secondary':'primary'" @click="follow">{{profile.followed?'已关注':'关注'}}</v-btn></header><section class="profile-content"><h2>公开内容</h2><div class="surface-grid"><v-card v-for="item in items" :key="item.publicationId" :to="`/p/${item.publicationId}`" class="section-card clickable pa-5"><v-chip size="x-small" variant="tonal">{{item.contentType}}</v-chip><h3 class="mt-4">{{item.title}}</h3><p class="muted">{{item.preview}}</p><small>{{new Date(item.publishedAt).toLocaleDateString('zh-CN')}}</small></v-card></div><div v-if="!items.length" class="empty-state"><div><v-icon size="44">mdi-file-eye-outline</v-icon><h3>暂无公开内容</h3></div></div></section></template></main></PublicLayout></template>
<style scoped>.profile-public{min-height:100vh}.profile-cover{height:280px;background:linear-gradient(135deg,#dbeafe,#ede9fe);background-size:cover;background-position:center}.profile-head{display:flex;align-items:flex-start;gap:24px;width:min(1120px,calc(100% - 40px));margin:-52px auto 0;position:relative;padding-bottom:48px}.profile-avatar{border:5px solid white}.profile-copy{padding-top:68px}.profile-copy h1{font-size:34px;margin:0}.profile-copy p{color:#64748b}.profile-head>.v-btn{margin-top:72px}.profile-content{width:min(1120px,calc(100% - 40px));margin:auto;padding-bottom:80px}.profile-content h2{font-size:28px;margin-bottom:22px}</style>
