import { useEffect, useMemo, useState } from 'react'
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import {
  Activity, Check, ChevronRight, CircleOff, Code2, Copy, ExternalLink, KeyRound, LoaderCircle,
  Play, Plus, Radio, RefreshCw, RotateCcw, ShieldCheck, Trash2, Webhook, X,
} from 'lucide-react'
import { Link, useLocation, useSearchParams } from 'react-router-dom'
import { messageOf, post, request } from '../lib/api'
import type {
  ApiKeyCredential, CurrentUser, OAuthAuthorizationInfo, OAuthClient, WebhookDeliveryPage,
  WebhookSubscription, Workspace,
} from '../types'

const scopeGroups = [
  ['读取', ['workspaces:read', 'users:read', 'teams:read', 'knowledge-bases:read', 'documents:read', 'catalog:read', 'search:read']],
  ['写入', ['documents:write', 'webhooks:read', 'webhooks:write']],
  ['OAuth', ['offline_access']],
] as const
const defaultScopes = ['workspaces:read', 'knowledge-bases:read', 'documents:read', 'documents:write', 'catalog:read', 'search:read']

export function OpenPlatformCenter({ workspaces }: { workspaces: Workspace[] }) {
  const [workspaceId, setWorkspaceId] = useState(workspaces[0]?.id ?? '')
  const [tab, setTab] = useState<'KEYS' | 'OAUTH' | 'WEBHOOKS' | 'DOCS'>('KEYS')
  useEffect(() => { if (!workspaceId && workspaces[0]) setWorkspaceId(workspaces[0].id) }, [workspaceId, workspaces])
  return <div className="content-page developer-page"><header className="page-header"><div><p className="eyebrow">开放平台</p><h1>把知识安全地连接出去</h1><p>API、OAuth、Webhook 与 MCP 共享同一套身份、scope 和资源权限。</p></div><label className="workspace-select"><span>当前空间</span><select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}>{workspaces.map((workspace) => <option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select></label></header>
    <nav className="developer-tabs"><button className={tab === 'KEYS' ? 'active' : ''} onClick={() => setTab('KEYS')}><KeyRound />API Keys</button><button className={tab === 'OAUTH' ? 'active' : ''} onClick={() => setTab('OAUTH')}><ShieldCheck />OAuth 应用</button><button className={tab === 'WEBHOOKS' ? 'active' : ''} onClick={() => setTab('WEBHOOKS')}><Webhook />Webhook</button><button className={tab === 'DOCS' ? 'active' : ''} onClick={() => setTab('DOCS')}><Code2 />API 与 MCP</button></nav>
    {workspaceId && tab === 'KEYS' && <ApiKeysPanel workspaceId={workspaceId} />}
    {workspaceId && tab === 'OAUTH' && <OAuthClientsPanel workspaceId={workspaceId} />}
    {workspaceId && tab === 'WEBHOOKS' && <WebhooksPanel workspaceId={workspaceId} />}
    {tab === 'DOCS' && <DeveloperDocs />}
  </div>
}

function ApiKeysPanel({ workspaceId }: { workspaceId: string }) {
  const queryClient = useQueryClient(); const [create, setCreate] = useState(false); const [revealed, setRevealed] = useState<string | null>(null)
  const query = useQuery({ queryKey: ['api-keys', workspaceId], queryFn: () => post<ApiKeyCredential[]>('/api/v1/open-platform/api-keys/list', { workspaceId }) })
  const revoke = useMutation({ mutationFn: (id: string) => post<void>('/api/v1/open-platform/api-keys/revoke', { workspaceId, id }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['api-keys', workspaceId] }) })
  return <DeveloperPanel icon={<KeyRound />} title="API Keys" description="适合脚本、自动化和 MCP 客户端。密钥仅在创建时显示一次。" action={<button className="button primary small" onClick={() => setCreate(true)}><Plus />创建密钥</button>}>
    <div className="credential-list">{(query.data ?? []).map((key) => <article key={key.id} className={key.revokedAt ? 'revoked' : ''}><span className="credential-icon"><KeyRound /></span><div><strong>{key.name}</strong><code>kp_live_{key.prefix}_••••••••</code><div className="scope-chips">{key.scopes.map((scope) => <span key={scope}>{scope}</span>)}</div><small>创建于 {date(key.createdAt)} · {key.lastUsedAt ? `最后使用 ${date(key.lastUsedAt)}` : '尚未使用'}{key.expiresAt ? ` · ${date(key.expiresAt)} 到期` : ''}</small></div><span className={`status-pill ${key.revokedAt ? 'danger' : 'success'}`}>{key.revokedAt ? '已撤销' : '有效'}</span>{!key.revokedAt && <button className="icon-button danger" onClick={() => revoke.mutate(key.id)} title="撤销" aria-label={`撤销 API Key ${key.name}`}><Trash2 /></button>}</article>)}{!query.isPending && !query.data?.length && <EmptyDeveloper title="还没有 API Key" description="创建后可使用 X-API-Key 或 Bearer 请求外部 API。" />}</div>
    {create && <CreateApiKeyDialog workspaceId={workspaceId} onClose={() => setCreate(false)} onCreated={(secret) => { setCreate(false); setRevealed(secret); void queryClient.invalidateQueries({ queryKey: ['api-keys', workspaceId] }) }} />}{revealed && <SecretDialog title="保存 API Key" secret={revealed} warning="关闭后无法再次查看。请立即存入密码管理器或部署环境的 Secret。" onClose={() => setRevealed(null)} />}
  </DeveloperPanel>
}

function CreateApiKeyDialog({ workspaceId, onClose, onCreated }: { workspaceId: string; onClose: () => void; onCreated: (secret: string) => void }) {
  const [name, setName] = useState('自动化'); const [scopes, setScopes] = useState(defaultScopes)
  const create = useMutation({ mutationFn: () => post<ApiKeyCredential>('/api/v1/open-platform/api-keys/create', { workspaceId, name, scopes }), onSuccess: (value) => onCreated(value.secret!) })
  return <DeveloperDialog eyebrow="API Key" title="创建访问密钥" onClose={onClose}><label className="field"><span className="field-label">名称</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><ScopePicker value={scopes} onChange={setScopes} />{create.error && <div className="form-error">{messageOf(create.error)}</div>}<div className="dialog-actions"><button className="button quiet" onClick={onClose}>取消</button><button className="button primary" disabled={!name || !scopes.length || create.isPending} onClick={() => create.mutate()}>{create.isPending && <LoaderCircle className="spin" />}创建</button></div></DeveloperDialog>
}

function OAuthClientsPanel({ workspaceId }: { workspaceId: string }) {
  const queryClient = useQueryClient();const [create, setCreate] = useState(false);const [secret, setSecret] = useState<string | null>(null)
  const query = useQuery({ queryKey: ['oauth-clients', workspaceId], queryFn: () => post<OAuthClient[]>('/api/v1/open-platform/oauth-clients/list', { workspaceId }) })
  const active = useMutation({ mutationFn: (value: OAuthClient) => post<void>('/api/v1/open-platform/oauth-clients/active', { workspaceId, id: value.id, active: !value.active }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['oauth-clients', workspaceId] }) })
  return <DeveloperPanel icon={<ShieldCheck />} title="OAuth 2.0 应用" description="Authorization Code + PKCE，redirect URI 必须完全匹配；Refresh Token 每次使用都会轮换。" action={<button className="button primary small" onClick={() => setCreate(true)}><Plus />注册应用</button>}>
    <div className="credential-list">{(query.data ?? []).map((client) => <article key={client.id}><span className="credential-icon oauth"><ShieldCheck /></span><div><strong>{client.name}</strong><code>{client.clientId}</code><p>{client.redirectUris.join(' · ')}</p><div className="scope-chips">{client.scopes.map((scope) => <span key={scope}>{scope}</span>)}</div><small>{client.publicClient ? '公开客户端 · 强制 PKCE' : '机密客户端 · Client Secret + PKCE'} · 创建于 {date(client.createdAt)}</small></div><span className={`status-pill ${client.active ? 'success' : 'danger'}`}>{client.active ? '启用' : '停用'}</span><button className="button quiet small" onClick={() => active.mutate(client)}>{client.active ? <CircleOff /> : <Play />}{client.active ? '停用' : '启用'}</button></article>)}{!query.isPending && !query.data?.length && <EmptyDeveloper title="还没有 OAuth 应用" description="注册第三方应用，让用户明确授权后访问知识。" />}</div>
    {create && <CreateOAuthDialog workspaceId={workspaceId} onClose={() => setCreate(false)} onCreated={(value) => { setCreate(false); if (value.clientSecret) setSecret(value.clientSecret); void queryClient.invalidateQueries({ queryKey: ['oauth-clients', workspaceId] }) }} />}{secret && <SecretDialog title="保存 Client Secret" secret={secret} warning="机密客户端的 Secret 只显示一次。公开客户端不需要 Secret，但始终必须使用 PKCE。" onClose={() => setSecret(null)} />}
  </DeveloperPanel>
}

function CreateOAuthDialog({ workspaceId, onClose, onCreated }: { workspaceId: string; onClose: () => void; onCreated: (value: OAuthClient) => void }) {
  const [name, setName] = useState('我的应用');const [redirects, setRedirects] = useState('https://example.com/oauth/callback');const [publicClient, setPublicClient] = useState(true);const [scopes, setScopes] = useState([...defaultScopes, 'offline_access'])
  const create = useMutation({ mutationFn: () => post<OAuthClient>('/api/v1/open-platform/oauth-clients/create', { workspaceId, name, redirectUris: redirects.split('\n').map((value) => value.trim()).filter(Boolean), scopes, publicClient }), onSuccess: onCreated })
  return <DeveloperDialog eyebrow="OAuth 2.0" title="注册应用" onClose={onClose}><label className="field"><span className="field-label">应用名称</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span className="field-label">Redirect URI（每行一个）</span><textarea rows={4} value={redirects} onChange={(event) => setRedirects(event.target.value)} /></label><label className="toggle-field"><div><strong>公开客户端</strong><small>桌面、移动端和 SPA；不保存 Client Secret</small></div><input type="checkbox" checked={publicClient} onChange={(event) => setPublicClient(event.target.checked)} /><i /></label><ScopePicker value={scopes} onChange={setScopes} />{create.error && <div className="form-error">{messageOf(create.error)}</div>}<div className="dialog-actions"><button className="button quiet" onClick={onClose}>取消</button><button className="button primary" onClick={() => create.mutate()} disabled={!name || !redirects.trim() || !scopes.length || create.isPending}>注册应用</button></div></DeveloperDialog>
}

export function WebhooksPanel({ workspaceId }: { workspaceId: string }) {
  const queryClient = useQueryClient();const [create, setCreate] = useState(false);const [secret, setSecret] = useState<string | null>(null);const [selected, setSelected] = useState<string>('')
  const hooks = useQuery({ queryKey: ['webhooks', workspaceId], queryFn: () => post<WebhookSubscription[]>('/api/v1/open-platform/webhooks/list', { workspaceId }), refetchInterval: 5_000 })
  useEffect(() => { if (!selected && hooks.data?.[0]) setSelected(hooks.data[0].id) }, [hooks.data, selected])
  const deliveries = useInfiniteQuery({ queryKey: ['webhook-deliveries', selected], initialPageParam: 0, queryFn: ({ pageParam }) => post<WebhookDeliveryPage>('/api/v1/open-platform/webhooks/deliveries/page', { webhookId: selected, limit: 30, offset: pageParam }), getNextPageParam: (lastPage) => lastPage.hasMore ? lastPage.nextOffset : undefined, enabled: Boolean(selected), refetchInterval: 2_000 })
  const active = useMutation({ mutationFn: (hook: WebhookSubscription) => post<void>('/api/v1/open-platform/webhooks/active', { workspaceId, id: hook.id, active: !hook.active }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['webhooks', workspaceId] }) })
  const test = useMutation({ mutationFn: (webhookId: string) => post<void>('/api/v1/open-platform/webhooks/test', { webhookId }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['webhook-deliveries', selected] }) })
  const replay = useMutation({ mutationFn: (deliveryId: string) => post<void>('/api/v1/open-platform/webhooks/replay', { webhookId: selected, deliveryId }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['webhook-deliveries', selected] }) })
  const deliveryValues = deliveries.data?.pages.flatMap((value) => value.items) ?? []
  return <DeveloperPanel icon={<Webhook />} title="Webhook" description="事件以 HMAC-SHA256 签名，失败后指数退避；连续失败会自动熔断，可人工重放。" action={<button className="button primary small" onClick={() => setCreate(true)}><Plus />新建订阅</button>}>
    <div className="webhook-layout"><div className="webhook-list">{(hooks.data ?? []).map((hook) => <button key={hook.id} className={selected === hook.id ? 'active' : ''} onClick={() => setSelected(hook.id)}><span className={`delivery-dot ${hook.suspendedAt ? 'dead' : hook.active ? 'delivered' : ''}`} /><div><strong>{hook.name}</strong><small>{hook.endpointUrl}</small><span>{hook.events.join(' · ')}</span></div><ChevronRight /></button>)}{!hooks.data?.length && <EmptyDeveloper title="还没有订阅" description="订阅 document.*、comment.* 或指定事件。" />}</div>{selected && <div className="delivery-panel">{hooks.data?.filter((hook) => hook.id === selected).map((hook) => <header key={hook.id}><div><h3>{hook.name}</h3><p>{hook.active ? hook.suspendedAt ? '失败熔断，需要重新启用或重放' : '正在投递' : '已暂停'}</p></div><button className="button quiet small" onClick={() => test.mutate(hook.id)}><Play />测试</button><button className="button quiet small" onClick={() => active.mutate(hook)}>{hook.active ? <CircleOff /> : <Play />}{hook.active ? '暂停' : '启用'}</button></header>)}<div className="delivery-list">{deliveryValues.map((delivery) => <article key={delivery.id}><span className={`delivery-dot ${delivery.status.toLowerCase()}`} /><div><strong>{delivery.eventType}</strong><small>{dateTime(delivery.createdAt)} · 第 {delivery.attempts} 次{delivery.responseStatus ? ` · HTTP ${delivery.responseStatus}` : ''}</small>{delivery.lastError && <p>{delivery.lastError}</p>}</div><span className={`status-pill ${delivery.status === 'DELIVERED' ? 'success' : delivery.status === 'DEAD' ? 'danger' : ''}`}>{delivery.status}</span>{delivery.status !== 'PENDING' && <button className="icon-button" onClick={() => replay.mutate(delivery.id)} title="重放" aria-label={`重放 ${delivery.eventType} 投递`}><RotateCcw /></button>}</article>)}{!deliveries.isPending && !deliveryValues.length && <EmptyDeveloper title="暂无投递记录" description="发送测试事件后可在这里观察签名投递。" />}</div>{deliveries.hasNextPage && <button className="button secondary delivery-more" disabled={deliveries.isFetchingNextPage} onClick={() => deliveries.fetchNextPage()}>{deliveries.isFetchingNextPage ? '加载中…' : '加载更多投递记录'}</button>}</div>}</div>
    {create && <CreateWebhookDialog workspaceId={workspaceId} onClose={() => setCreate(false)} onCreated={(value) => { setCreate(false); setSelected(value.id); setSecret(value.signingSecret); void queryClient.invalidateQueries({ queryKey: ['webhooks', workspaceId] }) }} />}{secret && <SecretDialog title="保存签名 Secret" secret={secret} warning="接收端使用此 Secret 验证 X-Knowledge-Signature；关闭后无法再次查看。" onClose={() => setSecret(null)} />}
  </DeveloperPanel>
}

function CreateWebhookDialog({ workspaceId, onClose, onCreated }: { workspaceId: string; onClose: () => void; onCreated: (value: WebhookSubscription) => void }) {
  const [name, setName] = useState('内容变更通知');const [endpointUrl, setEndpointUrl] = useState('https://example.com/webhooks/knowledge');const [events, setEvents] = useState('document.*\ncomment.created')
  const create = useMutation({ mutationFn: () => post<WebhookSubscription>('/api/v1/open-platform/webhooks/create', { workspaceId, name, endpointUrl, events: events.split('\n').map((value) => value.trim()).filter(Boolean) }), onSuccess: onCreated })
  return <DeveloperDialog eyebrow="Webhook" title="新建事件订阅" onClose={onClose}><label className="field"><span className="field-label">名称</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span className="field-label">HTTPS 接收地址</span><input value={endpointUrl} onChange={(event) => setEndpointUrl(event.target.value)} /></label><label className="field"><span className="field-label">事件（每行一个，支持 document.* 或 *）</span><textarea rows={5} value={events} onChange={(event) => setEvents(event.target.value)} /></label>{create.error && <div className="form-error">{messageOf(create.error)}</div>}<div className="dialog-actions"><button className="button quiet" onClick={onClose}>取消</button><button className="button primary" onClick={() => create.mutate()} disabled={!name || !endpointUrl || !events || create.isPending}>创建订阅</button></div></DeveloperDialog>
}

function DeveloperDocs() {
  const origin = window.location.origin
  const [copied, setCopied] = useState('')
  const copy = (name: string, value: string) => { void navigator.clipboard.writeText(value); setCopied(name); window.setTimeout(() => setCopied(''), 1_500) }
  const curl = `curl -H "X-API-Key: $KNOWLEDGE_API_KEY" \\\n+  "${origin}/api/v2/workspaces"`
  const mcp = JSON.stringify({ mcpServers: { knowledge: { type: 'http', url: `${origin}/mcp`, headers: { Authorization: 'Bearer ${KNOWLEDGE_API_KEY}' } } } }, null, 2)
  return <div className="docs-grid"><section className="developer-doc-card"><span><Code2 /></span><h2>REST API v2</h2><p>所有请求返回稳定 JSON，写入要求 Idempotency-Key。响应包含 X-Request-Id 和速率限制头。</p><CodeBlock value={curl} copied={copied === 'curl'} onCopy={() => copy('curl', curl)} /><div className="doc-links"><span>OpenAPI 3.1 契约位于 <code>contracts/openapi/api-v2.yaml</code></span></div></section><section className="developer-doc-card"><span><Activity /></span><h2>MCP Server</h2><p>直接使用同一把 API Key 或 OAuth Token，工具调用不会绕过 scope 与资源权限。</p><CodeBlock value={mcp} copied={copied === 'mcp'} onCopy={() => copy('mcp', mcp)} /><div className="doc-links"><span>协议版本 2025-06-18 · Streamable HTTP</span></div></section><section className="developer-doc-card wide"><span><Radio /></span><h2>Webhook 签名验证</h2><p>拼接 <code>timestamp + "." + rawBody</code>，使用 Signing Secret 做 HMAC-SHA256，并与 <code>X-Knowledge-Signature</code> 中的 <code>v1=</code> 值恒定时间比较。建议同时拒绝超过 5 分钟的时间戳并按 Delivery ID 去重。</p><div className="security-flow"><span>审计事件</span><ChevronRight /><span>持久化投递</span><ChevronRight /><span>HMAC 签名</span><ChevronRight /><span>指数退避</span><ChevronRight /><span>熔断 / 重放</span></div></section></div>
}

export function OAuthConsentPage() {
  const [params] = useSearchParams();const location = useLocation();const query = params.toString();const info = useQuery({ queryKey: ['oauth-consent', query], queryFn: () => request<OAuthAuthorizationInfo>(`/oauth/authorize?${query}`), retry: false });const me = useQuery({ queryKey: ['me'], queryFn: () => request<CurrentUser>('/api/v1/auth/me'), retry: false });const csrf = useQuery({ queryKey: ['csrf-consent'], queryFn: () => request<{ parameterName: string; token: string }>('/api/v1/auth/csrf'), enabled: Boolean(me.data) })
  const scopeLabels = useMemo(() => new Map([['workspaces:read', '读取工作区信息'], ['users:read', '读取成员目录'], ['teams:read', '读取团队'], ['knowledge-bases:read', '读取知识库'], ['documents:read', '读取文稿及正文'], ['documents:write', '创建和修改文稿'], ['catalog:read', '读取目录'], ['search:read', '搜索可访问内容'], ['webhooks:read', '读取 Webhook'], ['webhooks:write', '管理 Webhook'], ['offline_access', '在你离开后继续访问']]), [])
  if (info.isPending || me.isPending) return <main className="oauth-consent-page"><LoaderCircle className="spin" /></main>
  if (!me.data) return <main className="oauth-consent-page"><div className="oauth-consent-card"><span className="oauth-app-icon"><ShieldCheck /></span><h1>登录后继续授权</h1><p>完成登录后会回到这个授权请求。</p><Link className="button primary" to="/login" state={{ from: location.pathname + location.search }}>登录</Link></div></main>
  if (!info.data) return <main className="oauth-consent-page"><div className="oauth-consent-card"><CircleOff /><h1>无效的授权请求</h1><p>{messageOf(info.error)}</p><Link className="button secondary" to="/app">返回工作台</Link></div></main>
  const deny = () => { const target = new URL(info.data!.redirectUri);target.searchParams.set('error', 'access_denied');const state = params.get('state');if (state) target.searchParams.set('state', state);window.location.assign(target.toString()) }
  return <main className="oauth-consent-page"><div className="oauth-consent-card"><span className="oauth-app-icon"><ShieldCheck /></span><p className="eyebrow">OAuth 授权</p><h1>{info.data.name} 想访问你的知识</h1><p>当前账号 <strong>{me.data.email}</strong>。应用将只能访问你本来有权访问的内容。</p><div className="consent-scopes">{info.data.scopes.map((scope) => <div key={scope}><Check /><span><strong>{scopeLabels.get(scope) || scope}</strong><small>{scope}</small></span></div>)}</div><div className="consent-security"><ShieldCheck /><p>强制 PKCE S256 · Redirect URI 精确匹配 · 可随时在开放平台撤销</p></div>{csrf.data ? <form method="post" action="/oauth/authorize"><input type="hidden" name="client_id" value={params.get('client_id') || ''} /><input type="hidden" name="redirect_uri" value={params.get('redirect_uri') || ''} /><input type="hidden" name="scope" value={params.get('scope') || ''} /><input type="hidden" name="state" value={params.get('state') || ''} /><input type="hidden" name="code_challenge" value={params.get('code_challenge') || ''} /><input type="hidden" name="code_challenge_method" value={params.get('code_challenge_method') || ''} /><input type="hidden" name="consent" value="true" /><input type="hidden" name={csrf.data.parameterName} value={csrf.data.token} /><button type="button" className="button quiet" onClick={deny}>拒绝</button><button className="button primary" type="submit">允许访问</button></form> : <LoaderCircle className="spin" />}</div></main>
}

function DeveloperPanel({ icon, title, description, action, children }: { icon: React.ReactNode; title: string; description: string; action: React.ReactNode; children: React.ReactNode }) { return <section className="developer-panel"><header><span>{icon}</span><div><h2>{title}</h2><p>{description}</p></div>{action}</header>{children}</section> }
function DeveloperDialog({ eyebrow, title, onClose, children }: { eyebrow: string; title: string; onClose: () => void; children: React.ReactNode }) { return <div className="dialog-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="dialog developer-dialog"><div className="dialog-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label={`关闭${title}`}><X /></button></div>{children}</div></div> }
function ScopePicker({ value, onChange }: { value: string[]; onChange: (value: string[]) => void }) { const toggle = (scope: string) => onChange(value.includes(scope) ? value.filter((item) => item !== scope) : [...value, scope]);return <fieldset className="scope-picker"><legend>权限范围</legend>{scopeGroups.map(([group, scopes]) => <section key={group}><strong>{group}</strong>{scopes.map((scope) => <label key={scope}><input type="checkbox" checked={value.includes(scope)} onChange={() => toggle(scope)} /><span>{scope}</span></label>)}</section>)}</fieldset> }
function SecretDialog({ title, secret, warning, onClose }: { title: string; secret: string; warning: string; onClose: () => void }) { const [copied, setCopied] = useState(false);return <DeveloperDialog eyebrow="仅显示一次" title={title} onClose={onClose}><div className="secret-warning"><ShieldCheck /><p>{warning}</p></div><div className="secret-value"><code>{secret}</code><button className="button secondary small" onClick={() => { void navigator.clipboard.writeText(secret); setCopied(true) }}>{copied ? <Check /> : <Copy />}{copied ? '已复制' : '复制'}</button></div><div className="dialog-actions"><button className="button primary" onClick={onClose}>我已安全保存</button></div></DeveloperDialog> }
function CodeBlock({ value, copied, onCopy }: { value: string; copied: boolean; onCopy: () => void }) { return <div className="developer-code"><pre>{value}</pre><button onClick={onCopy}>{copied ? <Check /> : <Copy />}</button></div> }
function EmptyDeveloper({ title, description }: { title: string; description: string }) { return <div className="developer-empty"><Code2 /><strong>{title}</strong><p>{description}</p></div> }
function date(value: string) { return new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium' }).format(new Date(value)) }function dateTime(value: string) { return new Intl.DateTimeFormat('zh-CN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) }
