package io.knowledge.platform.integrationapi;

import io.knowledge.platform.integration.CredentialIdentity;import io.knowledge.platform.integration.ExternalApiModels.DocumentCreate;import io.knowledge.platform.integration.ExternalApiModels.DocumentUpdate;import io.knowledge.platform.integration.ExternalApiService;import jakarta.servlet.http.HttpServletRequest;import java.util.HashSet;import java.util.Set;import java.util.UUID;import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.PostMapping;import org.springframework.web.bind.annotation.RequestBody;import org.springframework.web.bind.annotation.RestController;import tools.jackson.databind.JsonNode;import tools.jackson.databind.ObjectMapper;import tools.jackson.databind.node.ArrayNode;import tools.jackson.databind.node.ObjectNode;

@RestController
@SuppressWarnings("deprecation")
final class McpController {
    private final ExternalApiService service;private final ObjectMapper mapper;McpController(ExternalApiService service,ObjectMapper mapper){this.service=service;this.mapper=mapper;}
    @PostMapping("/mcp") ResponseEntity<JsonNode> mcp(@RequestBody JsonNode message,HttpServletRequest request){JsonNode id=message.get("id");String method=message.path("method").asText();if("notifications/initialized".equals(method))return ResponseEntity.noContent().build();try{return ResponseEntity.ok(success(id,handle(method,message.path("params"),(CredentialIdentity)request.getAttribute(OpenPlatformAuthenticationFilter.IDENTITY_ATTRIBUTE))));}catch(IllegalArgumentException exception){return ResponseEntity.ok(error(id,-32602,exception.getMessage()));}catch(Exception exception){return ResponseEntity.ok(error(id,-32000,exception.getMessage()==null?"Tool call failed":exception.getMessage()));}}
    private JsonNode handle(String method,JsonNode params,CredentialIdentity identity){return switch(method){case"initialize"->initialize();case"ping"->mapper.createObjectNode();case"tools/list"->tools();case"tools/call"->call(params,identity);default->throw new IllegalArgumentException("Unsupported MCP method: "+method);};}
    private ObjectNode initialize(){ObjectNode result=mapper.createObjectNode();result.put("protocolVersion","2025-06-18");result.putObject("capabilities").putObject("tools").put("listChanged",false);result.putObject("serverInfo").put("name","knowledge-platform").put("version","1.0.0");return result;}
    private ObjectNode tools(){ArrayNode tools=mapper.createArrayNode();tool(tools,"list_workspaces","列出凭证可访问的工作区",schema());tool(tools,"list_users","列出工作区成员",schema().putObject("properties").set("workspaceId",stringSchema()));tool(tools,"list_teams","列出工作区团队",schema().putObject("properties").set("workspaceId",stringSchema()));tool(tools,"list_knowledge_bases","列出工作区知识库",schema().putObject("properties").set("workspaceId",stringSchema()));tool(tools,"list_documents","列出知识库文稿",schema().putObject("properties").set("knowledgeBaseId",stringSchema()));tool(tools,"get_document","读取文稿及结构化正文",schema().putObject("properties").set("pageId",stringSchema()));ObjectNode create=schema();ObjectNode cp=create.putObject("properties");cp.set("knowledgeBaseId",stringSchema());cp.set("title",stringSchema());cp.set("path",stringSchema());cp.set("contentType",stringSchema());cp.set("content",objectSchema());cp.set("idempotencyKey",stringSchema());create.putArray("required").add("knowledgeBaseId").add("title").add("path").add("idempotencyKey");tool(tools,"create_document","创建文稿，仍受用户权限与 scope 约束",create);ObjectNode update=schema();ObjectNode up=update.putObject("properties");up.set("pageId",stringSchema());up.set("expectedRevision",integerSchema());up.set("title",stringSchema());up.set("path",stringSchema());up.set("content",objectSchema());up.set("idempotencyKey",stringSchema());update.putArray("required").add("pageId").add("expectedRevision").add("idempotencyKey");tool(tools,"update_document","按乐观锁版本更新文稿",update);ObjectNode search=schema();ObjectNode sp=search.putObject("properties");sp.set("workspaceId",stringSchema());sp.set("query",stringSchema());sp.set("types",arraySchema());sp.set("limit",integerSchema());search.putArray("required").add("workspaceId").add("query");tool(tools,"search","权限过滤后的全文搜索",search);return mapper.createObjectNode().set("tools",tools);}
    private ObjectNode call(JsonNode params,CredentialIdentity identity){String name=params.path("name").asText();JsonNode a=params.path("arguments");Object value=switch(name){case"list_workspaces"->service.workspaces(identity);case"list_users"->service.users(identity,uuid(a,"workspaceId"));case"list_teams"->service.teams(identity,uuid(a,"workspaceId"));case"list_knowledge_bases"->service.knowledgeBases(identity,uuid(a,"workspaceId"));case"list_documents"->service.documents(identity,uuid(a,"knowledgeBaseId"));case"get_document"->service.document(identity,uuid(a,"pageId"));case"create_document"->service.createDocument(identity,text(a,"idempotencyKey"),new DocumentCreate(uuid(a,"knowledgeBaseId"),text(a,"title"),text(a,"path"),nullable(a,"contentType"),nullable(a,"icon"),nullable(a,"cover"),nullable(a,"publishMode"),nullable(a,"visibilityOverride"),a.get("documentSettings"),a.get("content")));case"update_document"->service.updateDocument(identity,text(a,"idempotencyKey"),new DocumentUpdate(uuid(a,"pageId"),a.path("expectedRevision").asLong(),nullable(a,"title"),nullable(a,"path"),nullable(a,"icon"),nullable(a,"cover"),nullable(a,"publishMode"),nullable(a,"visibilityOverride"),a.get("documentSettings"),a.get("content"),a.has("schemaVersion")?a.path("schemaVersion").asInt():null,nullable(a,"revisionKind"),nullable(a,"revisionDescription")));case"search"->service.search(identity,uuid(a,"workspaceId"),text(a,"query"),strings(a.path("types")),0,a.path("limit").asInt(20));default->throw new IllegalArgumentException("Unknown MCP tool: "+name);};JsonNode structured=mapper.valueToTree(value);ObjectNode result=mapper.createObjectNode();result.set("structuredContent",structured);result.putArray("content").addObject().put("type","text").put("text",mapper.writeValueAsString(value));result.put("isError",false);return result;}
    private ObjectNode success(JsonNode id,JsonNode result){ObjectNode response=mapper.createObjectNode();response.put("jsonrpc","2.0");response.set("id",id==null?mapper.nullNode():id);response.set("result",result);return response;}private ObjectNode error(JsonNode id,int code,String detail){ObjectNode response=mapper.createObjectNode();response.put("jsonrpc","2.0");response.set("id",id==null?mapper.nullNode():id);response.putObject("error").put("code",code).put("message",detail);return response;}
    private static void tool(ArrayNode values,String name,String description,ObjectNode schema){values.addObject().put("name",name).put("description",description).set("inputSchema",schema);}private ObjectNode schema(){return mapper.createObjectNode().put("type","object").put("additionalProperties",false);}private ObjectNode stringSchema(){return mapper.createObjectNode().put("type","string");}private ObjectNode integerSchema(){return mapper.createObjectNode().put("type","integer");}private ObjectNode objectSchema(){return mapper.createObjectNode().put("type","object");}private ObjectNode arraySchema(){return mapper.createObjectNode().put("type","array").set("items",stringSchema());}
    private static UUID uuid(JsonNode value,String name){return UUID.fromString(text(value,name));}private static String text(JsonNode value,String name){String result=value.path(name).asText();if(result.isBlank())throw new IllegalArgumentException(name+" is required");return result;}private static String nullable(JsonNode value,String name){JsonNode item=value.get(name);return item==null||item.isNull()?null:item.asText();}private static Set<String> strings(JsonNode value){if(!value.isArray())return Set.of();Set<String> result=new HashSet<>();value.forEach(item->result.add(item.asText()));return Set.copyOf(result);}
}
