package io.knowledge.platform.integrationapi;

import io.knowledge.platform.integration.OpenPlatformService;import io.knowledge.platform.integration.OpenPlatformViews.OAuthAuthorizationInfo;import io.knowledge.platform.integration.OpenPlatformViews.Token;import io.knowledge.platform.security.PlatformPrincipal;import jakarta.servlet.http.HttpServletRequest;import java.net.URI;import java.nio.charset.StandardCharsets;import java.util.Base64;import java.util.LinkedHashMap;import java.util.Map;import org.springframework.http.MediaType;import org.springframework.http.ResponseEntity;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.util.MultiValueMap;import org.springframework.web.bind.annotation.GetMapping;import org.springframework.web.bind.annotation.PostMapping;import org.springframework.web.bind.annotation.RequestBody;import org.springframework.web.bind.annotation.RequestParam;import org.springframework.web.bind.annotation.RestController;

@RestController
final class OAuthController {
    private final OpenPlatformService service;OAuthController(OpenPlatformService service){this.service=service;}
    @GetMapping("/oauth/authorize") ResponseEntity<?> info(@RequestParam("client_id")String clientId,@RequestParam("redirect_uri")String redirect,@RequestParam(value="scope",required=false)String scope,HttpServletRequest request){OAuthAuthorizationInfo info=service.authorizationInfo(clientId,redirect,scope);String accept=request.getHeader("Accept");if(accept!=null&&accept.contains(MediaType.TEXT_HTML_VALUE)){String query=request.getQueryString();return ResponseEntity.status(302).location(URI.create("/oauth/consent"+(query==null?"":"?"+query))).build();}return ResponseEntity.ok(info);}
    @PostMapping(value="/oauth/authorize",consumes=MediaType.APPLICATION_JSON_VALUE) ResponseEntity<Void> authorize(@RequestBody AuthorizationRequest r,@AuthenticationPrincipal PlatformPrincipal p){var grant=service.authorize(p.userId(),r.clientId(),r.redirectUri(),r.scope(),r.state(),r.codeChallenge(),r.codeChallengeMethod(),Boolean.TRUE.equals(r.consent()));return ResponseEntity.status(303).location(URI.create(grant.redirectUri())).build();}
    @PostMapping(value="/oauth/authorize",consumes=MediaType.APPLICATION_FORM_URLENCODED_VALUE) ResponseEntity<Void> authorizeForm(@RequestParam("client_id")String clientId,@RequestParam("redirect_uri")String redirectUri,@RequestParam(value="scope",required=false)String scope,@RequestParam(value="state",required=false)String state,@RequestParam("code_challenge")String challenge,@RequestParam("code_challenge_method")String method,@RequestParam(value="consent",defaultValue="false")boolean consent,@AuthenticationPrincipal PlatformPrincipal p){var grant=service.authorize(p.userId(),clientId,redirectUri,scope,state,challenge,method,consent);return ResponseEntity.status(303).location(URI.create(grant.redirectUri())).build();}
    @PostMapping(value="/oauth/token",consumes=MediaType.APPLICATION_FORM_URLENCODED_VALUE,produces=MediaType.APPLICATION_JSON_VALUE) Map<String,Object> token(@RequestParam MultiValueMap<String,String> form,HttpServletRequest request){ClientCredentials client=client(form,request.getHeader("Authorization"));String grant=form.getFirst("grant_type");Token token;if("authorization_code".equals(grant))token=service.exchangeCode(client.id(),client.secret(),form.getFirst("code"),form.getFirst("redirect_uri"),form.getFirst("code_verifier"));else if("refresh_token".equals(grant))token=service.refresh(client.id(),client.secret(),form.getFirst("refresh_token"));else throw new IllegalArgumentException("Unsupported OAuth grant_type");Map<String,Object> response=new LinkedHashMap<>();response.put("access_token",token.accessToken());response.put("token_type",token.tokenType());response.put("expires_in",token.expiresIn());if(token.refreshToken()!=null)response.put("refresh_token",token.refreshToken());response.put("scope",io.knowledge.platform.integration.OpenPlatformScopes.join(token.scopes()));return response;}
    private static ClientCredentials client(MultiValueMap<String,String> form,String authorization){if(authorization!=null&&authorization.regionMatches(true,0,"Basic ",0,6)){try{String value=new String(Base64.getDecoder().decode(authorization.substring(6).trim()),StandardCharsets.UTF_8);int separator=value.indexOf(':');if(separator>0)return new ClientCredentials(value.substring(0,separator),value.substring(separator+1));}catch(IllegalArgumentException exception){throw new IllegalArgumentException("OAuth client Basic authentication is invalid");}}return new ClientCredentials(form.getFirst("client_id"),form.getFirst("client_secret"));}
    record AuthorizationRequest(String clientId,String redirectUri,String scope,String state,String codeChallenge,String codeChallengeMethod,Boolean consent){}record ClientCredentials(String id,String secret){}
}
