package io.knowledge.platform.integrationapi;

import io.knowledge.platform.integration.CredentialIdentity;import io.knowledge.platform.integration.OpenPlatformService;import io.knowledge.platform.security.PlatformPrincipal;import jakarta.servlet.FilterChain;import jakarta.servlet.ServletException;import jakarta.servlet.http.HttpServletRequest;import jakarta.servlet.http.HttpServletResponse;import java.io.IOException;import java.time.Instant;import java.util.ArrayList;import java.util.List;import java.util.UUID;import java.util.concurrent.ConcurrentHashMap;import java.util.concurrent.atomic.AtomicInteger;import org.springframework.beans.factory.annotation.Value;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.GrantedAuthority;import org.springframework.security.core.authority.SimpleGrantedAuthority;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Component;import org.springframework.web.filter.OncePerRequestFilter;

@Component
public final class OpenPlatformAuthenticationFilter extends OncePerRequestFilter {
    public static final String IDENTITY_ATTRIBUTE=OpenPlatformAuthenticationFilter.class.getName()+".identity";private final OpenPlatformService service;private final int limit;private final ConcurrentHashMap<UUID,Window> windows=new ConcurrentHashMap<>();
    public OpenPlatformAuthenticationFilter(OpenPlatformService service,@Value("${platform.external-api.requests-per-minute:600}")int limit){this.service=service;this.limit=Math.max(10,limit);}
    @Override protected boolean shouldNotFilter(HttpServletRequest request){String path=request.getRequestURI();return !path.startsWith("/api/v2/")&&!path.equals("/mcp")&&!path.startsWith("/mcp/");}
    @Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain)throws ServletException,IOException{String requestId=requestId(request.getHeader("X-Request-Id"));response.setHeader("X-Request-Id",requestId);String credential=credential(request);CredentialIdentity identity=service.authenticate(credential);if(identity==null){problem(response,401,"INVALID_API_CREDENTIAL","A valid Bearer token or X-API-Key is required");return;}long minute=Instant.now().getEpochSecond()/60;Window window=windows.compute(identity.credentialId(),(key,current)->current==null||current.minute()!=minute?new Window(minute,new AtomicInteger()):current);int used=window.count().incrementAndGet();response.setHeader("X-RateLimit-Limit",Integer.toString(limit));response.setHeader("X-RateLimit-Remaining",Integer.toString(Math.max(0,limit-used)));if(used>limit){response.setHeader("Retry-After",Long.toString(60-Instant.now().getEpochSecond()%60));problem(response,429,"API_RATE_LIMITED","External API rate limit exceeded");return;}request.setAttribute(IDENTITY_ATTRIBUTE,identity);List<GrantedAuthority> authorities=new ArrayList<>();authorities.add(new SimpleGrantedAuthority("ROLE_USER"));for(String scope:identity.scopes())authorities.add(new SimpleGrantedAuthority("SCOPE_"+scope));if(identity.instanceAdmin())authorities.add(new SimpleGrantedAuthority("ROLE_INSTANCE_ADMIN"));var principal=new PlatformPrincipal(identity.userId(),identity.email(),identity.instanceAdmin());SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(principal,credential,List.copyOf(authorities)));try{chain.doFilter(request,response);}finally{SecurityContextHolder.clearContext();}}
    private static String credential(HttpServletRequest request){String authorization=request.getHeader("Authorization");if(authorization!=null&&authorization.regionMatches(true,0,"Bearer ",0,7))return authorization.substring(7).trim();return request.getHeader("X-API-Key");}
    private static String requestId(String value){return value!=null&&value.matches("[A-Za-z0-9._:-]{8,80}")?value:UUID.randomUUID().toString();}
    private static void problem(HttpServletResponse response,int status,String code,String detail)throws IOException{response.setStatus(status);response.setContentType("application/problem+json");response.getWriter().write("{\"type\":\"https://errors.knowledge.local/"+code+"\",\"title\":\"External API request failed\",\"status\":"+status+",\"code\":\""+code+"\",\"detail\":\""+detail+"\"}");}
    private record Window(long minute,AtomicInteger count){}
}
