package io.knowledge.platform.integrationapi;

import io.knowledge.platform.integration.OpenPlatformService;import io.knowledge.platform.integration.OpenPlatformViews.ApiKey;import io.knowledge.platform.integration.OpenPlatformViews.OAuthClient;import io.knowledge.platform.integration.OpenPlatformViews.Webhook;import io.knowledge.platform.integration.OpenPlatformViews.WebhookDelivery;import io.knowledge.platform.integration.OpenPlatformViews.WebhookDeliveryPage;import io.knowledge.platform.security.PlatformPrincipal;import java.time.OffsetDateTime;import java.util.List;import java.util.Set;import java.util.UUID;import org.springframework.http.ResponseEntity;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.PostMapping;import org.springframework.web.bind.annotation.RequestBody;import org.springframework.web.bind.annotation.RequestMapping;import org.springframework.web.bind.annotation.RestController;

@RestController @RequestMapping("/api/v1/open-platform")
final class OpenPlatformController {
    private final OpenPlatformService service;OpenPlatformController(OpenPlatformService service){this.service=service;}
    @PostMapping("/api-keys/create") ResponseEntity<ApiKey> createKey(@RequestBody ApiKeyCreate r,@AuthenticationPrincipal PlatformPrincipal p){return ResponseEntity.status(201).body(service.createApiKey(p.userId(),r.workspaceId(),r.name(),r.scopes(),r.expiresAt()));}
    @PostMapping("/api-keys/list") List<ApiKey> keys(@RequestBody Workspace r,@AuthenticationPrincipal PlatformPrincipal p){return service.apiKeys(p.userId(),r.workspaceId());}
    @PostMapping("/api-keys/revoke") ResponseEntity<Void> revokeKey(@RequestBody Resource r,@AuthenticationPrincipal PlatformPrincipal p){service.revokeApiKey(p.userId(),r.workspaceId(),r.id());return ResponseEntity.noContent().build();}
    @PostMapping("/oauth-clients/create") ResponseEntity<OAuthClient> createClient(@RequestBody ClientCreate r,@AuthenticationPrincipal PlatformPrincipal p){return ResponseEntity.status(201).body(service.createClient(p.userId(),r.workspaceId(),r.name(),r.redirectUris(),r.scopes(),Boolean.TRUE.equals(r.publicClient())));}
    @PostMapping("/oauth-clients/list") List<OAuthClient> clients(@RequestBody Workspace r,@AuthenticationPrincipal PlatformPrincipal p){return service.clients(p.userId(),r.workspaceId());}
    @PostMapping("/oauth-clients/active") ResponseEntity<Void> clientActive(@RequestBody Active r,@AuthenticationPrincipal PlatformPrincipal p){service.setClientActive(p.userId(),r.workspaceId(),r.id(),Boolean.TRUE.equals(r.active()));return ResponseEntity.noContent().build();}
    @PostMapping("/webhooks/create") ResponseEntity<Webhook> createWebhook(@RequestBody WebhookCreate r,@AuthenticationPrincipal PlatformPrincipal p){return ResponseEntity.status(201).body(service.createWebhook(p.userId(),r.workspaceId(),r.name(),r.endpointUrl(),r.events()));}
    @PostMapping("/webhooks/list") List<Webhook> webhooks(@RequestBody Workspace r,@AuthenticationPrincipal PlatformPrincipal p){return service.webhooks(p.userId(),r.workspaceId());}
    @PostMapping("/webhooks/active") ResponseEntity<Void> webhookActive(@RequestBody Active r,@AuthenticationPrincipal PlatformPrincipal p){service.setWebhookActive(p.userId(),r.workspaceId(),r.id(),Boolean.TRUE.equals(r.active()));return ResponseEntity.noContent().build();}
    @PostMapping("/webhooks/deliveries") List<WebhookDelivery> deliveries(@RequestBody Deliveries r,@AuthenticationPrincipal PlatformPrincipal p){return service.deliveries(p.userId(),r.webhookId(),r.limit()==null?50:r.limit());}
    @PostMapping("/webhooks/deliveries/page") WebhookDeliveryPage deliveryPage(@RequestBody Deliveries r,@AuthenticationPrincipal PlatformPrincipal p){return service.deliveryPage(p.userId(),r.webhookId(),r.limit()==null?30:r.limit(),r.offset()==null?0:r.offset());}
    @PostMapping("/webhooks/replay") ResponseEntity<Void> replay(@RequestBody Replay r,@AuthenticationPrincipal PlatformPrincipal p){service.replay(p.userId(),r.webhookId(),r.deliveryId());return ResponseEntity.noContent().build();}
    @PostMapping("/webhooks/test") ResponseEntity<Void> test(@RequestBody WebhookId r,@AuthenticationPrincipal PlatformPrincipal p){service.sendTest(p.userId(),r.webhookId());return ResponseEntity.accepted().build();}
    record Workspace(UUID workspaceId){}record Resource(UUID workspaceId,UUID id){}record ApiKeyCreate(UUID workspaceId,String name,Set<String> scopes,OffsetDateTime expiresAt){}record ClientCreate(UUID workspaceId,String name,List<String> redirectUris,Set<String> scopes,Boolean publicClient){}record Active(UUID workspaceId,UUID id,Boolean active){}record WebhookCreate(UUID workspaceId,String name,String endpointUrl,Set<String> events){}record WebhookId(UUID webhookId){}record Deliveries(UUID webhookId,Integer limit,Integer offset){}record Replay(UUID webhookId,UUID deliveryId){}
}
