#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo "Auto publication E2E failed at line $LINENO" >&2' ERR
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."&&pwd)";api_jar="${API_JAR:-$root/backend/app-api/build/libs/knowledge-platform-api.jar}";worker_jar="${WORKER_JAR:-$root/backend/app-worker/build/libs/knowledge-platform-worker.jar}";[[ -f "$api_jar" && -f "$worker_jar" ]];suffix="kp-auto-pub-$(date +%s)-$$";net="$suffix-net";db="$suffix-db";api="$suffix-api";worker="$suffix-worker";tmp="$(mktemp -d /tmp/kp-auto-pub.XXXXXX)"
cleanup(){ docker rm -f "$worker" "$api" "$db" >/dev/null 2>&1||true;docker network rm "$net" >/dev/null 2>&1||true;case "$tmp" in /tmp/kp-auto-pub.*)rm -rf -- "$tmp";;esac;};trap cleanup EXIT
wait_for(){ local label="$1";shift;for _ in $(seq 1 90);do "$@" >/dev/null 2>&1&&return;sleep 1;done;echo "timeout $label";docker logs "$api";docker logs "$worker" 2>/dev/null||true;return 1;};wait_sql(){ local label="$1" query="$2" expected="$3" actual;for _ in $(seq 1 90);do actual="$(docker exec "$db" psql -U knowledge -d knowledge -Atc "$query")";[[ "$actual" == "$expected" ]]&&return;sleep 1;done;echo "$label expected $expected, got $actual";return 1;};val(){ python3 -c 'import json,sys;print(json.load(sys.stdin)[sys.argv[1]])' "$1";};post(){ local path="$1" data="$2" out="$3";curl -sS -o "$out" -w '%{http_code}' -b "$cookie" -H "$header: $token" -H 'Content-Type: application/json' --data-binary "$data" "$url$path";}
docker network create "$net" >/dev/null;docker run -d --name "$db" --network "$net" --network-alias database -e POSTGRES_DB=knowledge -e POSTGRES_USER=knowledge -e POSTGRES_PASSWORD=knowledge postgres:17.6-alpine >/dev/null;wait_for db docker exec "$db" pg_isready -U knowledge -d knowledge
master="$(openssl rand -base64 32)";docker run -d --name "$api" --network "$net" -p 127.0.0.1::8080 --entrypoint java -e DATABASE_URL=jdbc:postgresql://database:5432/knowledge -e DATABASE_USER=knowledge -e DATABASE_PASSWORD=knowledge -e SESSION_COOKIE_SECURE=false -e SETTINGS_MASTER_KEY="$master" -v "$api_jar:/app.jar:ro" gradle:9.7.0-jdk25 -jar /app.jar >/dev/null;port="$(docker port "$api" 8080/tcp|sed -n 's/.*://p'|head -1)";url="http://127.0.0.1:$port";wait_for api curl -fsS "$url/actuator/health"
cookie="$tmp/admin-c";[[ "$(curl -sS -o "$tmp/setup" -w '%{http_code}' -c "$cookie" -H 'Content-Type: application/json' --data-binary '{"email":"admin@example.com","password":"Admin-Password-2026!","passwordConfirmation":"Admin-Password-2026!","workspaceName":"Auto Publish Workspace"}' "$url/api/v1/setup/initialize")" == 201 ]];admin="$(val userId < "$tmp/setup")";ws="$(val workspaceId < "$tmp/setup")";csrf="$(curl -fsS -b "$cookie" "$url/api/v1/auth/csrf")";header="$(printf %s "$csrf"|val headerName)";token="$(printf %s "$csrf"|val token)"
[[ "$(post /api/v1/knowledge-bases/create "{\"workspaceId\":\"$ws\",\"name\":\"Auto Knowledge\",\"slug\":\"auto-knowledge\",\"ownerType\":\"WORKSPACE\",\"ownerId\":\"$ws\",\"visibility\":\"PUBLIC\",\"publishMode\":\"AUTO\"}" "$tmp/kb")" == 201 ]];kb="$(val id < "$tmp/kb")"
[[ "$(post /api/v1/pages/create "{\"knowledgeBaseId\":\"$kb\",\"title\":\"自动发布文稿\",\"path\":\"automatic-publication\",\"contentType\":\"DOCUMENT\",\"publishMode\":\"INHERIT\",\"content\":{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"text\":\"版本零\"}]}}" "$tmp/page")" == 201 ]];page="$(val id < "$tmp/page")"
[[ "$(post /api/v1/pages/update "{\"pageId\":\"$page\",\"expectedRevision\":0,\"content\":{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"text\":\"版本一\"}]}}" "$tmp/update-1")" == 200 ]]
[[ "$(post /api/v1/pages/update "{\"pageId\":\"$page\",\"expectedRevision\":1,\"content\":{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"text\":\"版本二最终\"}]}}" "$tmp/update-2")" == 200 ]]
[[ "$(post /api/v1/pages/publication-state "{\"pageId\":\"$page\"}" "$tmp/pending-state")" == 200 ]];python3 -c 'import json,sys;d=json.load(sys.stdin);assert d["draftRevision"]==2;assert d["published"] is False;assert d["effectivePublishMode"]=="AUTO";assert d["automaticJobStatus"]=="PENDING"' < "$tmp/pending-state"
docker run -d --name "$worker" --network "$net" --entrypoint java -e DATABASE_URL=jdbc:postgresql://database:5432/knowledge -e DATABASE_USER=knowledge -e DATABASE_PASSWORD=knowledge -e SETTINGS_MASTER_KEY="$master" -e WORKER_ID="$worker" -e WORKER_POLL_DELAY=100ms -v "$worker_jar:/app.jar:ro" gradle:9.7.0-jdk25 -jar /app.jar >/dev/null
wait_sql initial-auto-publish "select coalesce((select source_draft_revision::text from page_publications where page_id='$page' and superseded_at is null),'')" 2
[[ "$(post /api/v1/pages/publication-history "{\"pageId\":\"$page\",\"limit\":20}" "$tmp/history-1")" == 200 ]];python3 -c 'import json,sys;d=json.load(sys.stdin);assert len(d)==1;assert d[0]["sourceDraftRevision"]==2;assert d[0]["plainText"]=="版本二最终"' < "$tmp/history-1"
[[ "$(post /api/v1/pages/update "{\"pageId\":\"$page\",\"expectedRevision\":2,\"publishMode\":\"MANUAL\"}" "$tmp/disable")" == 200 ]]
[[ "$(post /api/v1/pages/update "{\"pageId\":\"$page\",\"expectedRevision\":3,\"content\":{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"text\":\"手动模式未发布\"}]}}" "$tmp/manual-edit")" == 200 ]]
sleep 3
[[ "$(docker exec "$db" psql -U knowledge -d knowledge -Atc "select source_draft_revision from page_publications where page_id='$page' and superseded_at is null")" == 2 ]]
[[ "$(post /api/v1/pages/update "{\"pageId\":\"$page\",\"expectedRevision\":4,\"publishMode\":\"AUTO\",\"content\":{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"text\":\"重新开启自动发布\"}]}}" "$tmp/re-enable")" == 200 ]]
wait_sql resumed-auto-publish "select coalesce((select source_draft_revision::text from page_publications where page_id='$page' and superseded_at is null),'')" 5
[[ "$(post /api/v1/pages/publication-history "{\"pageId\":\"$page\",\"limit\":20}" "$tmp/history-2")" == 200 ]];python3 -c 'import json,sys;d=json.load(sys.stdin);assert len(d)==2;assert d[0]["sourceDraftRevision"]==5;assert d[0]["plainText"]=="重新开启自动发布";assert d[1]["sourceDraftRevision"]==2' < "$tmp/history-2"
[[ "$(post /api/v1/pages/publication-history/page "{\"pageId\":\"$page\",\"limit\":1,\"offset\":0}" "$tmp/history-page-1")" == 200 ]];history_next="$(val nextOffset < "$tmp/history-page-1")"
[[ "$(post /api/v1/pages/publication-history/page "{\"pageId\":\"$page\",\"limit\":1,\"offset\":$history_next}" "$tmp/history-page-2")" == 200 ]]
python3 - "$tmp/history-page-1" "$tmp/history-page-2" <<'PY'
import json,sys
one,two=json.load(open(sys.argv[1])),json.load(open(sys.argv[2]))
assert one['hasMore'] is True and one['nextOffset']==1 and len(one['items'])==1,one
assert two['hasMore'] is False and two['nextOffset']==2 and len(two['items'])==1,two
assert [one['items'][0]['sourceDraftRevision'],two['items'][0]['sourceDraftRevision']]==[5,2],(one,two)
assert one['items'][0]['id']!=two['items'][0]['id'],(one,two)
PY
wait_sql jobs-complete "select count(*) from durable_jobs where job_type='page.auto-publish' and status='SUCCEEDED'" 4
[[ "$(docker exec "$db" psql -U knowledge -d knowledge -Atc "select (select count(*) from page_publications where page_id='$page'),(select count(*) from audit_events where action='page.publish-auto' and resource_id='$page'),(select count(*) from outbox_events where event_type='PagePublished' and aggregate_id='$page'),(select count(*) from durable_jobs where job_type='page.auto-publish')")" == '2|2|2|4' ]]
echo AUTO_PUBLICATION_E2E_COUNTS;docker exec "$db" psql -U knowledge -d knowledge -Atc "select (select count(*) from page_publications),(select count(*) from durable_jobs where job_type='page.auto-publish' and status='SUCCEEDED'),(select count(*) from audit_events where action='page.publish-auto')";echo AUTO_PUBLICATION_E2E_SUCCESS
