package io.knowledge.platform.search;

import static org.jooq.impl.DSL.field;
import static org.jooq.impl.DSL.name;
import static org.jooq.impl.DSL.table;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.DSLContext;
import org.jooq.JSONB;
import org.jooq.Record;
import org.jooq.Table;
import org.springframework.stereotype.Repository;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ObjectNode;

@Repository
class SearchRebuildRepository {
    private static final Table<Record> JOBS=table(name("search_rebuilds"));
    private final DSLContext dsl;private final ObjectMapper mapper;
    SearchRebuildRepository(DSLContext dsl,ObjectMapper mapper){this.dsl=dsl;this.mapper=mapper;}

    void insert(UUID id,UUID workspaceId,UUID actor,OffsetDateTime now){dsl.insertInto(JOBS).columns(uuid("id"),uuid("workspace_id"),string("status"),string("cursor_type"),number("processed_count"),number("error_count"),uuid("requested_by"),time("started_at"),time("updated_at")).values(id,workspaceId,"RUNNING","KNOWLEDGE_BASE",0L,0L,actor,now,now).execute();}
    SearchRebuildView find(UUID id,boolean lock){var query=dsl.select(uuid("id"),uuid("workspace_id"),string("status"),string("cursor_type"),uuid("cursor_id"),number("processed_count"),number("error_count"),uuid("requested_by"),time("started_at"),time("updated_at"),time("completed_at"),string("last_error")).from(JOBS).where(uuid("id").eq(id));Record record=lock?query.forUpdate().fetchOne():query.fetchOne();return record==null?null:map(record);}
    List<SearchRebuildView> list(UUID workspaceId){return list(workspaceId,20,0);}
    List<SearchRebuildView> list(UUID workspaceId,int limit,int offset){return dsl.select(uuid("id"),uuid("workspace_id"),string("status"),string("cursor_type"),uuid("cursor_id"),number("processed_count"),number("error_count"),uuid("requested_by"),time("started_at"),time("updated_at"),time("completed_at"),string("last_error")).from(JOBS).where(uuid("workspace_id").eq(workspaceId)).orderBy(time("updated_at").desc(),uuid("id").desc()).limit(Math.max(1,Math.min(limit,101))).offset(Math.max(0,offset)).fetch(SearchRebuildRepository::map);}
    void progress(UUID id,String phase,UUID cursor,long processed,OffsetDateTime now){dsl.update(JOBS).set(string("cursor_type"),phase).set(uuid("cursor_id"),cursor).set(number("processed_count"),processed).set(time("updated_at"),now).where(uuid("id").eq(id)).execute();}
    void status(UUID id,String status,OffsetDateTime now,boolean complete){var query=dsl.update(JOBS).set(string("status"),status).set(time("updated_at"),now);if(complete)query.set(time("completed_at"),now);query.where(uuid("id").eq(id)).execute();}
    void failed(UUID id,long errors,String message,OffsetDateTime now){dsl.update(JOBS).set(string("status"),"FAILED").set(number("error_count"),errors).set(string("last_error"),message).set(time("updated_at"),now).set(time("completed_at"),now).where(uuid("id").eq(id)).execute();}

    List<SearchDocumentCommand> batch(String phase,UUID workspaceId,UUID cursor,int limit){String after=cursor==null?"":" and x.id > ?::uuid";List<Object> bindings=new ArrayList<>();bindings.add(workspaceId);if(cursor!=null)bindings.add(cursor);bindings.add(limit);String sql=switch(phase){
        case "KNOWLEDGE_BASE"->"select x.id,x.workspace_id,x.name title,coalesce(x.description,'') body,x.slug path,x.created_by owner_id,null::text content_type,x.visibility,null::uuid publication_id,x.created_at,x.updated_at,jsonb_build_object('ownerType',x.owner_type,'ownerId',x.owner_id,'allowPublicIndex',x.allow_public_index) metadata from knowledge_bases x where x.workspace_id=?::uuid and x.archived_at is null"+after+" order by x.id limit ?";
        case "TEAM"->"select x.id,x.workspace_id,x.name title,coalesce(x.description,'') body,x.slug path,x.created_by owner_id,null::text content_type,x.visibility,null::uuid publication_id,x.created_at,x.updated_at,jsonb_build_object('avatar',x.avatar) metadata from teams x where x.workspace_id=?::uuid and x.deleted_at is null"+after+" order by x.id limit ?";
        case "PAGE"->"select x.id,x.workspace_id,x.title,coalesce(d.plain_text,'') body,x.path,x.created_by owner_id,x.content_type,case when x.visibility_override='INHERIT' then kb.visibility else x.visibility_override end visibility,null::uuid publication_id,x.created_at,x.updated_at,jsonb_build_object('knowledgeBaseId',x.knowledge_base_id,'draftRevision',x.draft_revision,'icon',x.icon,'publicationStatus',case when x.published_revision_id is null then 'UNPUBLISHED' when x.draft_revision>pp.source_draft_revision then 'CHANGED' else 'PUBLISHED' end) metadata,coalesce((select array_agg(pl.name order by pl.position) from page_labels pl where pl.page_id=x.id),array[]::text[]) labels from pages x join page_drafts d on d.page_id=x.id join knowledge_bases kb on kb.id=x.knowledge_base_id left join page_publications pp on pp.id=x.published_revision_id where x.workspace_id=?::uuid and x.deleted_at is null"+after+" order by x.id limit ?";
        case "QUICK_NOTE"->"select x.id,x.workspace_id,left(coalesce(nullif(split_part(x.plain_text,E'\\n',1),''),'Quick note'),120) title,x.plain_text body,null::text path,x.user_id owner_id,'DOCUMENT'::text content_type,'PRIVATE'::text visibility,null::uuid publication_id,x.created_at,x.updated_at,jsonb_build_object('status',x.status,'source',x.source,'revision',x.revision_no) metadata from quick_notes x where x.workspace_id=?::uuid and x.status<>'DELETED'"+after+" order by x.id limit ?";
        case "TEMPLATE"->"select x.id,x.workspace_id,x.name title,coalesce(x.description,'') body,null::text path,x.created_by owner_id,x.template_type content_type,x.visibility,null::uuid publication_id,x.created_at,x.updated_at,jsonb_build_object('templateType',x.template_type,'category',x.category,'thumbnail',x.thumbnail) metadata from templates x where x.workspace_id=?::uuid and x.deleted_at is null"+after+" order by x.id limit ?";
        case "ATTACHMENT"->"select x.id,x.workspace_id,x.original_name title,concat_ws(E'\\n',p.title,x.media_type,x.extracted_text) body,x.page_id::text path,x.uploaded_by owner_id,case when lower(x.original_name)~'\\.[a-z0-9]{1,16}$' then upper(substring(lower(x.original_name) from '\\.([a-z0-9]{1,16})$')) else 'FILE' end content_type,'WORKSPACE'::text visibility,null::uuid publication_id,x.created_at,coalesce(x.extracted_at,x.created_at) updated_at,jsonb_strip_nulls(jsonb_build_object('pageId',x.page_id,'knowledgeBaseId',p.knowledge_base_id,'pageTitle',p.title,'mediaType',x.media_type,'sizeBytes',x.size_bytes,'extractionStatus',x.extraction_status,'contentUrl','/api/v1/attachments/'||x.id||'/content')) metadata from attachments x left join pages p on p.id=x.page_id and p.deleted_at is null where x.workspace_id=?::uuid and x.deleted_at is null"+after+" order by x.id limit ?";
        case "PUBLICATION"->"select x.id,x.workspace_id,x.title_snapshot title,x.plain_text_snapshot body,p.path,x.published_by owner_id,x.content_type,case when p.visibility_override='INHERIT' then kb.visibility else p.visibility_override end visibility,x.id publication_id,p.created_at created_at,x.published_at updated_at,x.metadata_snapshot || jsonb_build_object('knowledgeBaseId',x.knowledge_base_id) metadata,x.page_id resource_id,coalesce(array(select jsonb_array_elements_text(coalesce(x.metadata_snapshot->'labels','[]'::jsonb))),array[]::text[]) labels from page_publications x join pages p on p.id=x.page_id join knowledge_bases kb on kb.id=x.knowledge_base_id where x.workspace_id=?::uuid and x.superseded_at is null and p.deleted_at is null"+after+" order by x.id limit ?";
        default->throw new IllegalArgumentException("Search rebuild phase is invalid");};
        return dsl.fetch(sql,bindings.toArray()).map(record->command(phase,record));}

    long cleanup(UUID workspaceId){return dsl.execute("delete from search_documents s where s.workspace_id=?::uuid and ((s.resource_type='PAGE' and s.source_scope='DRAFT' and not exists(select 1 from pages p where p.id=s.resource_id and p.deleted_at is null)) or (s.resource_type='PAGE' and s.source_scope='PUBLISHED' and not exists(select 1 from page_publications p where p.id=s.id and p.superseded_at is null)) or (s.resource_type='KNOWLEDGE_BASE' and not exists(select 1 from knowledge_bases k where k.id=s.resource_id and k.archived_at is null)) or (s.resource_type='TEAM' and not exists(select 1 from teams t where t.id=s.resource_id and t.deleted_at is null)) or (s.resource_type='QUICK_NOTE' and not exists(select 1 from quick_notes q where q.id=s.resource_id and q.status<>'DELETED')) or (s.resource_type='TEMPLATE' and not exists(select 1 from templates t where t.id=s.resource_id and t.deleted_at is null)) or (s.resource_type='ATTACHMENT' and not exists(select 1 from attachments a where a.id=s.resource_id and a.deleted_at is null)))",workspaceId);}

    private SearchDocumentCommand command(String phase,Record record){UUID id=record.get("id",UUID.class);UUID resourceId="PUBLICATION".equals(phase)?record.get("resource_id",UUID.class):id;String type=switch(phase){case "KNOWLEDGE_BASE"->"KNOWLEDGE_BASE";case "QUICK_NOTE"->"QUICK_NOTE";case "TEMPLATE"->"TEMPLATE";case "TEAM"->"TEAM";case "ATTACHMENT"->"ATTACHMENT";default->"PAGE";};String scope="PUBLICATION".equals(phase)?"PUBLISHED":SetScopes.canonical(type);JSONB raw=record.get("metadata",JSONB.class);ObjectNode metadata=raw==null?mapper.createObjectNode():(ObjectNode)mapper.readTree(raw.data());String[] values=record.field("labels")==null?new String[0]:record.get("labels",String[].class);return new SearchDocumentCommand(id,record.get("workspace_id",UUID.class),type,resourceId,scope,record.get("title",String.class),record.get("body",String.class),values==null?List.of():Arrays.asList(values),record.get("path",String.class),record.get("owner_id",UUID.class),record.get("content_type",String.class),record.get("visibility",String.class),record.get("publication_id",UUID.class),0,metadata,record.get("created_at",OffsetDateTime.class),record.get("updated_at",OffsetDateTime.class));}
    private static SearchRebuildView map(Record r){return new SearchRebuildView(r.get("id",UUID.class),r.get("workspace_id",UUID.class),r.get("status",String.class),r.get("cursor_type",String.class),r.get("cursor_id",UUID.class),r.get("processed_count",Long.class),r.get("error_count",Long.class),r.get("requested_by",UUID.class),r.get("started_at",OffsetDateTime.class),r.get("updated_at",OffsetDateTime.class),r.get("completed_at",OffsetDateTime.class),r.get("last_error",String.class));}
    private static final class SetScopes{static String canonical(String type){return "PAGE".equals(type)?"DRAFT":"CANONICAL";}}
    private static org.jooq.Field<UUID> uuid(String v){return field(name(v),UUID.class);}private static org.jooq.Field<String> string(String v){return field(name(v),String.class);}private static org.jooq.Field<Long> number(String v){return field(name(v),Long.class);}private static org.jooq.Field<OffsetDateTime> time(String v){return field(name(v),OffsetDateTime.class);}
}
